version: "3.7"

services:
    db:
        image: "mariadb:bionic"
        container_name: "rathena-dev_db"
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "rathenadb:/var/lib/mysql" # save database to local disk
            - "../../sql-files/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok
    server:
        container_name: "rathena-dev"
        ports:
            - "5121:5121" # map server
            - "6121:6121" # char server
            - "6900:6900" # login server
        volumes:
            - "../../..:/rathena" # mount git repo directory inside container
            - "../asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "../asset/char_conf.txt:/rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "../asset/map_conf.txt:/rathena/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: ../
            dockerfile: ./development/Dockerfile
        depends_on:
            - db

volumes:
    rathenadb:
