#!/bin/bash
# modified by shazeya@syafi.com (NL130240)

./athena-start start
sleep 30

while [ true ]; do
    if [ "      0" = "$(ps | grep -e log | wc -l)" ] ||
#    if [ "      0" = "$(ps | grep -e login | wc -l)" ] ||
       [ "      0" = "$(ps | grep -e char  | wc -l)" ] ||
       [ "      0" = "$(ps | grep -e map   | wc -l)" ]; then
        printf "Error:"
        date
        sleep 10
        printf "Checking:"
        date
        if [ "      0" = "$(ps | grep -e log | wc -l)" ] ||
#        if [ "      0" = "$(ps | grep -e login | wc -l)" ] ||
           [ "      0" = "$(ps | grep -e char  | wc -l)" ] ||
           [ "      0" = "$(ps | grep -e map   | wc -l)" ]; then
            printf "Error Confirmation:"
            date
            printf "Restoration:"
            date
            ./athena-start start
        else
            printf "Check Miss Sorry:"
            date
        fi
#    else
#        printf "Check OK:"
#        date
    fi
    sleep 10
done
