// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#include "skill_factory_elemental.hpp"

#include <config/core.hpp>

#include "../skill_impl.hpp"

// Include .cpp files into the TU to optimize compile time
// For reference see unity builds or amalgamated builds
#include "ageofice.cpp"
#include "aquaplay.cpp"
#include "avalanche.cpp"
#include "blast.cpp"
#include "circleoffire.cpp"
#include "coldforce.cpp"
#include "coolair.cpp"
#include "cooler.cpp"
#include "crystalarmor.cpp"
#include "cursedsoil.cpp"
#include "deadlypoison.cpp"
#include "deeppoisoning.cpp"
#include "earthcare.cpp"
#include "eyesofstorm.cpp"
#include "firearrow.cpp"
#include "firebomb.cpp"
#include "firecloak.cpp"
#include "firemantle.cpp"
#include "firewave.cpp"
#include "flamearmor.cpp"
#include "flamerock.cpp"
#include "flametechnic.cpp"
#include "gracebreeze.cpp"
#include "gust.cpp"
#include "heater.cpp"
#include "hurricanerage.cpp"
#include "iceneedle.cpp"
#include "petrology.cpp"
#include "poisonshield.cpp"
#include "powerofgaia.cpp"
#include "pyrotechnic.cpp"
#include "rocklauncher.cpp"
#include "solidskin.cpp"
#include "stonehammer.cpp"
#include "stonerain.cpp"
#include "stoneshield.cpp"
#include "stormwind.cpp"
#include "strongprotection.cpp"
#include "tidalweapon.cpp"
#include "tropic.cpp"
#include "typhoonmissile.cpp"
#include "upheaval.cpp"
#include "waterbarrier.cpp"
#include "waterdrop.cpp"
#include "waterscreen.cpp"
#include "waterscrew.cpp"
#include "wildstorm.cpp"
#include "windcurtain.cpp"
#include "windslasher.cpp"
#include "windstep.cpp"
#include "zephyr.cpp"

std::unique_ptr<const SkillImpl> SkillFactoryElemental::create(const e_skill skill_id) const {
	switch (skill_id) {
		case EL_AQUAPLAY:
			return std::make_unique<SkillAquaPlay>();
		case EL_BLAST:
			return std::make_unique<SkillBlast>();
		case EL_CHILLY_AIR:
			return std::make_unique<SkillCoolAir>();
		case EL_CIRCLE_OF_FIRE:
			return std::make_unique<SkillCircleOfFire>();
		case EL_COOLER:
			return std::make_unique<SkillCooler>();
		case EL_CURSED_SOIL:
			return std::make_unique<SkillCursedSoil>();
		case EL_FIRE_ARROW:
			return std::make_unique<SkillFireArrow>();
		case EL_FIRE_BOMB:
			return std::make_unique<SkillFireBomb>();
		case EL_FIRE_BOMB_ATK:
			return std::make_unique<SkillFireBombAttack>();
		case EL_FIRE_CLOAK:
			return std::make_unique<SkillFireCloak>();
		case EL_FIRE_MANTLE:
			return std::make_unique<SkillFireMantle>();
		case EL_FIRE_WAVE:
			return std::make_unique<SkillFireWave>();
		case EL_FIRE_WAVE_ATK:
			return std::make_unique<SkillFireWaveAttack>();
		case EL_GUST:
			return std::make_unique<SkillGust>();
		case EL_HEATER:
			return std::make_unique<SkillHeater>();
		case EL_HURRICANE:
			return std::make_unique<SkillHurricaneRage>();
		case EL_HURRICANE_ATK:
			return std::make_unique<SkillHurricaneRageAttack>();
		case EL_ICE_NEEDLE:
			return std::make_unique<SkillIceNeedle>();
		case EL_PETROLOGY:
			return std::make_unique<SkillPetrology>();
		case EL_POWER_OF_GAIA:
			return std::make_unique<SkillPowerOfGaia>();
		case EL_PYROTECHNIC:
			return std::make_unique<SkillPyrotechnic>();
		case EL_ROCK_CRUSHER:
			return std::make_unique<SkillRockLauncher>();
		case EL_ROCK_CRUSHER_ATK:
			return std::make_unique<SkillRockLauncherAttack>();
		case EL_SOLID_SKIN:
			return std::make_unique<SkillSolidSkin>();
		case EL_STONE_HAMMER:
			return std::make_unique<SkillStoneHammer>();
		case EL_STONE_RAIN:
			return std::make_unique<SkillStoneRain>();
		case EL_STONE_SHIELD:
			return std::make_unique<SkillStoneShield>();
		case EL_TIDAL_WEAPON:
			return std::make_unique<SkillTidalWeapon>();
		case EL_TROPIC:
			return std::make_unique<SkillTropic>();
		case EL_TYPOON_MIS:
			return std::make_unique<SkillTyphoonMissile>();
		case EL_TYPOON_MIS_ATK:
			return std::make_unique<SkillTyphoonMissileAttack>();
		case EL_UPHEAVAL:
			return std::make_unique<SkillUpheaval>();
		case EL_WATER_BARRIER:
			return std::make_unique<SkillWaterBarrier>();
		case EL_WATER_DROP:
			return std::make_unique<SkillWaterDrop>();
		case EL_WATER_SCREEN:
			return std::make_unique<SkillWaterScreen>();
		case EL_WATER_SCREW:
			return std::make_unique<SkillWaterScrew>();
		case EL_WATER_SCREW_ATK:
			return std::make_unique<SkillWaterScrewAttack>();
		case EL_WILD_STORM:
			return std::make_unique<SkillWildStorm>();
		case EL_WIND_CURTAIN:
			return std::make_unique<SkillWindCurtain>();
		case EL_WIND_SLASH:
			return std::make_unique<SkillWindSlasher>();
		case EL_WIND_STEP:
			return std::make_unique<SkillWindStep>();
		case EL_ZEPHYR:
			return std::make_unique<SkillZephyr>();
		case EM_EL_AGE_OF_ICE:
			return std::make_unique<SkillAgeOfIce>();
		case EM_EL_AVALANCHE:
			return std::make_unique<SkillAvalanche>();
		case EM_EL_COLD_FORCE:
			return std::make_unique<SkillColdForce>();
		case EM_EL_CRYSTAL_ARMOR:
			return std::make_unique<SkillCrystalArmor>();
		case EM_EL_DEADLY_POISON:
			return std::make_unique<SkillDeadlyPoison>();
		case EM_EL_DEEP_POISONING:
			return std::make_unique<SkillDeepPoisoning>();
		case EM_EL_EARTH_CARE:
			return std::make_unique<SkillEarthCare>();
		case EM_EL_EYES_OF_STORM:
			return std::make_unique<SkillEyesOfStorm>();
		case EM_EL_FLAMEARMOR:
			return std::make_unique<SkillFlameArmor>();
		case EM_EL_FLAMEROCK:
			return std::make_unique<SkillFlameRock>();
		case EM_EL_FLAMETECHNIC:
			return std::make_unique<SkillFlameTechnic>();
		case EM_EL_GRACE_BREEZE:
			return std::make_unique<SkillGraceBreeze>();
		case EM_EL_POISON_SHIELD:
			return std::make_unique<SkillPoisonShield>();
		case EM_EL_STORM_WIND:
			return std::make_unique<SkillStormWind>();
		case EM_EL_STRONG_PROTECTION:
			return std::make_unique<SkillStrongProtection>();

		default:
			return nullptr;
	}
}
