#
# Table structure for table `item_db`
#

DROP TABLE IF EXISTS `item_db`;
CREATE TABLE `item_db` (
  `id` int unsigned NOT NULL DEFAULT 0,
  `name_aegis` varchar(50) NOT NULL DEFAULT '',
  `name_english` varchar(100) NOT NULL DEFAULT '',
  `type` varchar(20) DEFAULT NULL,
  `subtype` varchar(20) DEFAULT NULL,
  `price_buy` mediumint unsigned DEFAULT NULL,
  `price_sell` mediumint unsigned DEFAULT NULL,
  `weight` smallint unsigned DEFAULT NULL,
  `attack` smallint unsigned DEFAULT NULL,
  `defense` smallint unsigned DEFAULT NULL,
  `range` tinyint unsigned DEFAULT NULL,
  `slots` tinyint unsigned DEFAULT NULL,
  `job_all` tinyint unsigned DEFAULT NULL,
  `job_acolyte` tinyint unsigned DEFAULT NULL,
  `job_alchemist` tinyint unsigned DEFAULT NULL,
  `job_archer` tinyint unsigned DEFAULT NULL,
  `job_assassin` tinyint unsigned DEFAULT NULL,
  `job_barddancer` tinyint unsigned DEFAULT NULL,
  `job_blacksmith` tinyint unsigned DEFAULT NULL,
  `job_crusader` tinyint unsigned DEFAULT NULL,
  `job_gunslinger` tinyint unsigned DEFAULT NULL,
  `job_hunter` tinyint unsigned DEFAULT NULL,
  `job_knight` tinyint unsigned DEFAULT NULL,
  `job_mage` tinyint unsigned DEFAULT NULL,
  `job_merchant` tinyint unsigned DEFAULT NULL,
  `job_monk` tinyint unsigned DEFAULT NULL,
  `job_ninja` tinyint unsigned DEFAULT NULL,
  `job_novice` tinyint unsigned DEFAULT NULL,
  `job_priest` tinyint unsigned DEFAULT NULL,
  `job_rogue` tinyint unsigned DEFAULT NULL,
  `job_sage` tinyint unsigned DEFAULT NULL,
  `job_soullinker` tinyint unsigned DEFAULT NULL,
  `job_stargladiator` tinyint unsigned DEFAULT NULL,
  `job_supernovice` tinyint unsigned DEFAULT NULL,
  `job_swordman` tinyint unsigned DEFAULT NULL,
  `job_taekwon` tinyint unsigned DEFAULT NULL,
  `job_thief` tinyint unsigned DEFAULT NULL,
  `job_wizard` tinyint unsigned DEFAULT NULL,
  `class_all` tinyint unsigned DEFAULT NULL,
  `class_normal` tinyint unsigned DEFAULT NULL,
  `class_upper` tinyint unsigned DEFAULT NULL,
  `class_baby` tinyint unsigned DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `location_head_top` tinyint unsigned DEFAULT NULL,
  `location_head_mid` tinyint unsigned DEFAULT NULL,
  `location_head_low` tinyint unsigned DEFAULT NULL,
  `location_armor` tinyint unsigned DEFAULT NULL,
  `location_right_hand` tinyint unsigned DEFAULT NULL,
  `location_left_hand` tinyint unsigned DEFAULT NULL,
  `location_garment` tinyint unsigned DEFAULT NULL,
  `location_shoes` tinyint unsigned DEFAULT NULL,
  `location_right_accessory` tinyint unsigned DEFAULT NULL,
  `location_left_accessory` tinyint unsigned DEFAULT NULL,
  `location_costume_head_top` tinyint unsigned DEFAULT NULL,
  `location_costume_head_mid` tinyint unsigned DEFAULT NULL,
  `location_costume_head_low` tinyint unsigned DEFAULT NULL,
  `location_costume_garment` tinyint unsigned DEFAULT NULL,
  `location_ammo` tinyint unsigned DEFAULT NULL,
  `location_shadow_armor` tinyint unsigned DEFAULT NULL,
  `location_shadow_weapon` tinyint unsigned DEFAULT NULL,
  `location_shadow_shield` tinyint unsigned DEFAULT NULL,
  `location_shadow_shoes` tinyint unsigned DEFAULT NULL,
  `location_shadow_right_accessory` tinyint unsigned DEFAULT NULL,
  `location_shadow_left_accessory` tinyint unsigned DEFAULT NULL,
  `weapon_level` tinyint unsigned DEFAULT NULL,
  `armor_level` tinyint unsigned DEFAULT NULL,
  `equip_level_min` tinyint unsigned DEFAULT NULL,
  `equip_level_max` tinyint unsigned DEFAULT NULL,
  `refineable` tinyint unsigned DEFAULT NULL,
  `view` smallint unsigned DEFAULT NULL,
  `alias_name` varchar(50) DEFAULT NULL,
  `flag_buyingstore` tinyint unsigned DEFAULT NULL,
  `flag_deadbranch` tinyint unsigned DEFAULT NULL,
  `flag_container` tinyint unsigned DEFAULT NULL,
  `flag_uniqueid` tinyint unsigned DEFAULT NULL,
  `flag_bindonequip` tinyint unsigned DEFAULT NULL,
  `flag_dropannounce` tinyint unsigned DEFAULT NULL,
  `flag_noconsume` tinyint unsigned DEFAULT NULL,
  `flag_dropeffect` varchar(20) DEFAULT NULL,
  `delay_duration` bigint unsigned DEFAULT NULL,
  `delay_status` varchar(30) DEFAULT NULL,
  `stack_amount` smallint unsigned DEFAULT NULL,
  `stack_inventory` tinyint unsigned DEFAULT NULL,
  `stack_cart` tinyint unsigned DEFAULT NULL,
  `stack_storage` tinyint unsigned DEFAULT NULL,
  `stack_guildstorage` tinyint unsigned DEFAULT NULL,
  `nouse_override` smallint unsigned DEFAULT NULL,
  `nouse_sitting` tinyint unsigned DEFAULT NULL,
  `trade_override` smallint unsigned DEFAULT NULL,
  `trade_nodrop` tinyint unsigned DEFAULT NULL,
  `trade_notrade` tinyint unsigned DEFAULT NULL,
  `trade_tradepartner` tinyint unsigned DEFAULT NULL,
  `trade_nosell` tinyint unsigned DEFAULT NULL,
  `trade_nocart` tinyint unsigned DEFAULT NULL,
  `trade_nostorage` tinyint unsigned DEFAULT NULL,
  `trade_noguildstorage` tinyint unsigned DEFAULT NULL,
  `trade_nomail` tinyint unsigned DEFAULT NULL,
  `trade_noauction` tinyint unsigned DEFAULT NULL,
  `script` text,
  `equip_script` text,
  `unequip_script` text,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueAegisName` (`name_aegis`)
) ENGINE=MyISAM;
