#
# Table structure for table `mob_skill_db2_re`
#

DROP TABLE IF EXISTS `mob_skill_db2_re`;
CREATE TABLE IF NOT EXISTS `mob_skill_db2_re` (
  `MOB_AEGIS_NAME` varchar(24) NOT NULL,
  `INDEX` int(11) unsigned NOT NULL,
  `SKILL_NAME` varchar(24) NOT NULL,
  `SKILL_LV` tinyint(4) unsigned DEFAULT NULL,
  `STATE` varchar(50) DEFAULT NULL,
  `RATE` smallint(4) DEFAULT NULL,
  `CASTTIME` mediumint(9) DEFAULT NULL,
  `DELAY` int(9) DEFAULT NULL,
  `CANCELABLE` tinyint(1) unsigned DEFAULT NULL,
  `TARGET` varchar(50) DEFAULT NULL,
  `CONDITION` varchar(50) DEFAULT NULL,
  `CONDITION_VALUE1` varchar(50) DEFAULT NULL,
  `CONDITION_VALUE2` tinyint(4) DEFAULT NULL,
  `AI` varchar(2) DEFAULT NULL,
  `SUMMON1` varchar(24) DEFAULT NULL,
  `SUMMON2` varchar(24) DEFAULT NULL,
  `SUMMON3` varchar(24) DEFAULT NULL,
  `SUMMON4` varchar(24) DEFAULT NULL,
  `SUMMON5` varchar(24) DEFAULT NULL,
  `SUMMON6` varchar(24) DEFAULT NULL,
  `EMOTION` varchar(50) DEFAULT NULL,
  `CHAT` smallint(4) unsigned DEFAULT NULL
) ENGINE=MyISAM;

-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('VALARIS',0,'AL_TELEPORT',1,'IDLE',10000,0,0,true,'SELF','RUDEATTACKED');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('VALARIS',1,'AL_TELEPORT',1,'WALK',500,0,5000,true,'SELF','RUDEATTACKED');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS',2,'KN_BRANDISHSPEAR',10,'ATTACK',2000,500,5000,false,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('VALARIS',3,'MO_BODYRELOCATION',1,'CHASE',200,200,1000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('VALARIS',4,'NPC_ARMORBRAKE',10,'ATTACK',2000,0,5000,false,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('VALARIS',5,'NPC_CALLSLAVE',1,'ATTACK',10000,0,30000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('VALARIS',6,'NPC_CALLSLAVE',1,'IDLE',10000,0,30000,true,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS',7,'NPC_DARKBREATH',5,'ATTACK',2000,800,5000,false,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('VALARIS',8,'NPC_DARKSTRIKE',10,'CHASE',200,0,1000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('VALARIS',9,'NPC_GUIDEDATTACK',5,'ATTACK',500,0,20000,false,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`EMOTION`) VALUES ('VALARIS',10,'NPC_POWERUP',5,'ATTACK',10000,0,30000,true,'SELF','MYHPLTMAXRATE','30','ET_FRET');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`SUMMON1`) VALUES ('VALARIS',11,'NPC_SUMMONSLAVE',6,'ATTACK',10000,700,10000,false,'SELF','SLAVELE','3','MC_CAMERI');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`SUMMON1`) VALUES ('VALARIS',12,'NPC_SUMMONSLAVE',6,'IDLE',10000,700,10000,false,'SELF','SLAVELE','3','MC_CAMERI');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS',13,'WZ_VERMILION',10,'ATTACK',2000,500,2000,false,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS',14,'WZ_VERMILION',10,'CHASE',200,500,2000,false,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`EMOTION`) VALUES ('VALARIS',15,'WZ_VERMILION',10,'CHASE',500,500,2000,false,'TARGET','SKILLUSED','MG_FIREWALL','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('VALARIS_WORSHIPPER',0,'AL_TELEPORT',1,'IDLE',10000,0,0,true,'SELF','RUDEATTACKED');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS_WORSHIPPER',1,'NPC_CURSEATTACK',3,'ATTACK',500,800,5000,false,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS_WORSHIPPER',2,'NPC_DARKNESSATTACK',2,'ATTACK',500,500,5000,false,'TARGET','ALWAYS','ET_FRET');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS_WORSHIPPER',3,'NPC_EMOTION',1,'WALK',200,0,5000,true,'SELF','ALWAYS','ET_DELIGHT');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS_WORSHIPPER',4,'NPC_HALLUCINATION',1,'ATTACK',500,500,5000,true,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS_WORSHIPPER',5,'NPC_HALLUCINATION',1,'CHASE',50,500,5000,true,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('VALARIS_WORSHIPPER',6,'SA_DISPELL',1,'ATTACK',0,0,30000,true,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('MC_CAMERI',0,'AL_TELEPORT',1,'IDLE',10000,0,0,true,'SELF','RUDEATTACKED');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('MC_CAMERI',1,'AL_TELEPORT',1,'WALK',500,0,5000,true,'SELF','RUDEATTACKED');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('MC_CAMERI',2,'KN_BRANDISHSPEAR',10,'ATTACK',2000,500,5000,false,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('MC_CAMERI',3,'MO_BODYRELOCATION',1,'CHASE',200,200,1000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('MC_CAMERI',4,'NPC_ARMORBRAKE',10,'ATTACK',2000,0,5000,false,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('MC_CAMERI',5,'NPC_DARKBREATH',5,'ATTACK',2000,800,5000,false,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('MC_CAMERI',6,'NPC_DARKSTRIKE',10,'CHASE',200,0,1000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('MC_CAMERI',7,'NPC_GUIDEDATTACK',5,'ATTACK',500,0,20000,false,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`EMOTION`) VALUES ('MC_CAMERI',8,'NPC_POWERUP',5,'ATTACK',10000,0,30000,true,'SELF','MYHPLTMAXRATE','30','ET_FRET');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('MC_CAMERI',9,'WZ_VERMILION',10,'ATTACK',2000,500,2000,false,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('MC_CAMERI',10,'WZ_VERMILION',10,'CHASE',200,500,2000,false,'TARGET','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`EMOTION`) VALUES ('MC_CAMERI',11,'WZ_VERMILION',10,'CHASE',500,500,2000,false,'TARGET','SKILLUSED','MG_FIREWALL','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',0,'AC_DOUBLE',10,'ATTACK',500,1000,5000,false,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`) VALUES ('POKI',1,'AC_SHOWER',8,'ATTACK',2000,1000,5000,false,'TARGET','ATTACKPCGT','2');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',2,'BS_MAXIMIZE',5,'CHASE',500,1000,5000,false,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',3,'BS_MAXIMIZE',5,'ATTACK',500,1000,5000,false,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',4,'NPC_AGIUP',5,'CHASE',2500,0,5000,false,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`) VALUES ('POKI',5,'NPC_POWERUP',5,'ATTACK',500,0,30000,true,'SELF','MYHPLTMAXRATE','30');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',6,'SN_SHARPSHOOTING',5,'ATTACK',500,1000,5000,false,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('POKI',7,'HT_SKIDTRAP',5,'IDLE',50,0,5000,true,'SELF','ALWAYS','ET_KIK');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',8,'HT_FLASHER',5,'IDLE',50,0,300000,true,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',9,'HT_FREEZINGTRAP',5,'IDLE',50,0,300000,true,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',10,'AC_CHARGEARROW',1,'ATTACK',500,0,5000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',11,'HT_FLASHER',5,'IDLE',50,0,300000,true,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`SUMMON1`,`SUMMON2`,`SUMMON3`,`SUMMON4`,`SUMMON5`,`EMOTION`) VALUES ('POKI',12,'NPC_SUMMONSLAVE',5,'IDLE',10000,2000,120000,false,'SELF','SLAVELE','1','G_WHIKEBAIN','G_ARMAIA','G_EREND','G_KAVAC','G_RAWREL','ET_SURPRISE');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',13,'NPC_CALLSLAVE',1,'ATTACK',2000,0,10000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',14,'NPC_CALLSLAVE',1,'IDLE',2000,0,10000,true,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`) VALUES ('POKI',15,'NPC_CHANGEWATER',1,'ATTACK',10000,2000,600000,false,'SELF','MYHPLTMAXRATE','30');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`EMOTION`) VALUES ('POKI',16,'NPC_CHANGETELEKINESIS',1,'ATTACK',500,2000,5000,false,'SELF','MYHPLTMAXRATE','10','ET_ANGER');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('POKI',17,'AL_TELEPORT',1,'IDLE',10000,0,0,true,'SELF','RUDEATTACKED');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`SUMMON1`) VALUES ('MOROCC_4',0,'NPC_SUMMONSLAVE',5,'ATTACK',10000,3000,10000,false,'SELF','SLAVELE','2','LUNATIC');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`SUMMON1`) VALUES ('MOROCC_4',1,'NPC_SUMMONSLAVE',5,'IDLE',5000,2000,40000,false,'SELF','ALWAYS','2','MOROCC_3');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('FIRE_PORING',0,'AL_HEAL',10,'IDLE',10000,0,2000,true,'SELF','ALWAYS','ET_SWEAT');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('FIRE_PORING',1,'AL_HEAL',10,'WALK',10000,0,2000,true,'SELF','ALWAYS','ET_SWEAT');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`) VALUES ('FIRE_PORING',2,'AL_TELEPORT',1,'ATTACK',1000,5000,60000,false,'SELF','MYHPLTMAXRATE','30');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('FIRE_PORING',3,'AL_TELEPORT',1,'IDLE',10000,0,0,true,'SELF','RUDEATTACKED');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`EMOTION`) VALUES ('FIRE_PORING',4,'NPC_DARKBLESSING',1,'ATTACK',1000,2000,5000,false,'TARGET','ALWAYS','ET_SMILE');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`SUMMON1`,`SUMMON2`,`SUMMON3`,`EMOTION`) VALUES ('FIRE_PORING',5,'NPC_SUMMONSLAVE',16,'ATTACK',10000,2000,10000,false,'SELF','SLAVELE','3','G_DOKEBI','G_BAPHOMET_','G_DEVIRUCHI','ET_SMILE');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`CONDITION_VALUE1`,`SUMMON1`,`SUMMON2`,`SUMMON3`,`EMOTION`) VALUES ('FIRE_PORING',6,'NPC_SUMMONSLAVE',16,'IDLE',10000,2000,10000,false,'SELF','SLAVELE','3','G_DOKEBI','G_BAPHOMET_','G_DEVIRUCHI','ET_SMILE');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('FIRE_PORING',7,'RG_INTIMIDATE',5,'ATTACK',1000,0,3000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('FIRE_PORING',8,'RG_STRIPARMOR',5,'ATTACK',2000,0,3000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('FIRE_PORING',9,'RG_STRIPHELM',5,'ATTACK',2000,0,3000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('FIRE_PORING',10,'RG_STRIPSHIELD',5,'ATTACK',2000,0,3000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('FIRE_PORING',11,'RG_STRIPWEAPON',5,'ATTACK',2000,0,3000,true,'TARGET','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('HALLOWEEN_WHISPER',0,'AS_CLOAKING',1,'IDLE',2000,200,5000,true,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('HALLOWEEN_WHISPER',1,'AS_CLOAKING',1,'CHASE',2000,200,5000,true,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`) VALUES ('HALLOWEEN_WHISPER',2,'NPC_EMOTION',1,'IDLE',2000,0,5000,true,'SELF','ALWAYS');
-- REPLACE INTO `mob_skill_db2_re` (`MOB_AEGIS_NAME`,`INDEX`,`SKILL_NAME`,`SKILL_LV`,`STATE`,`RATE`,`CASTTIME`,`DELAY`,`CANCELABLE`,`TARGET`,`CONDITION`,`AI`,`EMOTION`) VALUES ('HALLOWEEN_WHISPER',3,'NPC_EMOTION',1,'CHASE',200,0,5000,true,'SELF','ALWAYS','01','ET_PROFUSELY_SWEAT');
