-- ----------------------------
-- Table structure for storage2
-- ----------------------------
CREATE TABLE IF NOT EXISTS `storage2`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int UNSIGNED NOT NULL DEFAULT 0,
  `nameid` int UNSIGNED NOT NULL DEFAULT 0,
  `amount` smallint UNSIGNED NOT NULL DEFAULT 0,
  `equip` int UNSIGNED NOT NULL DEFAULT 0,
  `identify` smallint UNSIGNED NOT NULL DEFAULT 0,
  `refine` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `attribute` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `card0` int UNSIGNED NOT NULL DEFAULT 0,
  `card1` int UNSIGNED NOT NULL DEFAULT 0,
  `card2` int UNSIGNED NOT NULL DEFAULT 0,
  `card3` int UNSIGNED NOT NULL DEFAULT 0,
  `option_id0` smallint NOT NULL DEFAULT 0,
  `option_val0` smallint NOT NULL DEFAULT 0,
  `option_parm0` tinyint NOT NULL DEFAULT 0,
  `option_id1` smallint NOT NULL DEFAULT 0,
  `option_val1` smallint NOT NULL DEFAULT 0,
  `option_parm1` tinyint NOT NULL DEFAULT 0,
  `option_id2` smallint NOT NULL DEFAULT 0,
  `option_val2` smallint NOT NULL DEFAULT 0,
  `option_parm2` tinyint NOT NULL DEFAULT 0,
  `option_id3` smallint NOT NULL DEFAULT 0,
  `option_val3` smallint NOT NULL DEFAULT 0,
  `option_parm3` tinyint NOT NULL DEFAULT 0,
  `option_id4` smallint NOT NULL DEFAULT 0,
  `option_val4` smallint NOT NULL DEFAULT 0,
  `option_parm4` tinyint NOT NULL DEFAULT 0,
  `expire_time` int UNSIGNED NOT NULL DEFAULT 0,
  `bound` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `unique_id` bigint UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `account_id`(`account_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1;

-- ----------------------------
-- Table structure for storage3
-- ----------------------------
CREATE TABLE IF NOT EXISTS `storage3`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int UNSIGNED NOT NULL DEFAULT 0,
  `nameid` int UNSIGNED NOT NULL DEFAULT 0,
  `amount` smallint UNSIGNED NOT NULL DEFAULT 0,
  `equip` int UNSIGNED NOT NULL DEFAULT 0,
  `identify` smallint UNSIGNED NOT NULL DEFAULT 0,
  `refine` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `attribute` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `card0` int UNSIGNED NOT NULL DEFAULT 0,
  `card1` int UNSIGNED NOT NULL DEFAULT 0,
  `card2` int UNSIGNED NOT NULL DEFAULT 0,
  `card3` int UNSIGNED NOT NULL DEFAULT 0,
  `option_id0` smallint NOT NULL DEFAULT 0,
  `option_val0` smallint NOT NULL DEFAULT 0,
  `option_parm0` tinyint NOT NULL DEFAULT 0,
  `option_id1` smallint NOT NULL DEFAULT 0,
  `option_val1` smallint NOT NULL DEFAULT 0,
  `option_parm1` tinyint NOT NULL DEFAULT 0,
  `option_id2` smallint NOT NULL DEFAULT 0,
  `option_val2` smallint NOT NULL DEFAULT 0,
  `option_parm2` tinyint NOT NULL DEFAULT 0,
  `option_id3` smallint NOT NULL DEFAULT 0,
  `option_val3` smallint NOT NULL DEFAULT 0,
  `option_parm3` tinyint NOT NULL DEFAULT 0,
  `option_id4` smallint NOT NULL DEFAULT 0,
  `option_val4` smallint NOT NULL DEFAULT 0,
  `option_parm4` tinyint NOT NULL DEFAULT 0,
  `expire_time` int UNSIGNED NOT NULL DEFAULT 0,
  `bound` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `unique_id` bigint UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `account_id`(`account_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1;

-- ----------------------------
-- Table structure for storage4
-- ----------------------------
CREATE TABLE IF NOT EXISTS `storage4`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int UNSIGNED NOT NULL DEFAULT 0,
  `nameid` int UNSIGNED NOT NULL DEFAULT 0,
  `amount` smallint UNSIGNED NOT NULL DEFAULT 0,
  `equip` int UNSIGNED NOT NULL DEFAULT 0,
  `identify` smallint UNSIGNED NOT NULL DEFAULT 0,
  `refine` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `attribute` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `card0` int UNSIGNED NOT NULL DEFAULT 0,
  `card1` int UNSIGNED NOT NULL DEFAULT 0,
  `card2` int UNSIGNED NOT NULL DEFAULT 0,
  `card3` int UNSIGNED NOT NULL DEFAULT 0,
  `option_id0` smallint NOT NULL DEFAULT 0,
  `option_val0` smallint NOT NULL DEFAULT 0,
  `option_parm0` tinyint NOT NULL DEFAULT 0,
  `option_id1` smallint NOT NULL DEFAULT 0,
  `option_val1` smallint NOT NULL DEFAULT 0,
  `option_parm1` tinyint NOT NULL DEFAULT 0,
  `option_id2` smallint NOT NULL DEFAULT 0,
  `option_val2` smallint NOT NULL DEFAULT 0,
  `option_parm2` tinyint NOT NULL DEFAULT 0,
  `option_id3` smallint NOT NULL DEFAULT 0,
  `option_val3` smallint NOT NULL DEFAULT 0,
  `option_parm3` tinyint NOT NULL DEFAULT 0,
  `option_id4` smallint NOT NULL DEFAULT 0,
  `option_val4` smallint NOT NULL DEFAULT 0,
  `option_parm4` tinyint NOT NULL DEFAULT 0,
  `expire_time` int UNSIGNED NOT NULL DEFAULT 0,
  `bound` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `unique_id` bigint UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `account_id`(`account_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1;

-- ----------------------------
-- Table structure for storage5
-- ----------------------------
CREATE TABLE IF NOT EXISTS `storage5`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int UNSIGNED NOT NULL DEFAULT 0,
  `nameid` int UNSIGNED NOT NULL DEFAULT 0,
  `amount` smallint UNSIGNED NOT NULL DEFAULT 0,
  `equip` int UNSIGNED NOT NULL DEFAULT 0,
  `identify` smallint UNSIGNED NOT NULL DEFAULT 0,
  `refine` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `attribute` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `card0` int UNSIGNED NOT NULL DEFAULT 0,
  `card1` int UNSIGNED NOT NULL DEFAULT 0,
  `card2` int UNSIGNED NOT NULL DEFAULT 0,
  `card3` int UNSIGNED NOT NULL DEFAULT 0,
  `option_id0` smallint NOT NULL DEFAULT 0,
  `option_val0` smallint NOT NULL DEFAULT 0,
  `option_parm0` tinyint NOT NULL DEFAULT 0,
  `option_id1` smallint NOT NULL DEFAULT 0,
  `option_val1` smallint NOT NULL DEFAULT 0,
  `option_parm1` tinyint NOT NULL DEFAULT 0,
  `option_id2` smallint NOT NULL DEFAULT 0,
  `option_val2` smallint NOT NULL DEFAULT 0,
  `option_parm2` tinyint NOT NULL DEFAULT 0,
  `option_id3` smallint NOT NULL DEFAULT 0,
  `option_val3` smallint NOT NULL DEFAULT 0,
  `option_parm3` tinyint NOT NULL DEFAULT 0,
  `option_id4` smallint NOT NULL DEFAULT 0,
  `option_val4` smallint NOT NULL DEFAULT 0,
  `option_parm4` tinyint NOT NULL DEFAULT 0,
  `expire_time` int UNSIGNED NOT NULL DEFAULT 0,
  `bound` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `unique_id` bigint UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `account_id`(`account_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1;

-- ----------------------------
-- Table structure for storage6
-- ----------------------------
CREATE TABLE IF NOT EXISTS `storage6`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int UNSIGNED NOT NULL DEFAULT 0,
  `nameid` int UNSIGNED NOT NULL DEFAULT 0,
  `amount` smallint UNSIGNED NOT NULL DEFAULT 0,
  `equip` int UNSIGNED NOT NULL DEFAULT 0,
  `identify` smallint UNSIGNED NOT NULL DEFAULT 0,
  `refine` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `attribute` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `card0` int UNSIGNED NOT NULL DEFAULT 0,
  `card1` int UNSIGNED NOT NULL DEFAULT 0,
  `card2` int UNSIGNED NOT NULL DEFAULT 0,
  `card3` int UNSIGNED NOT NULL DEFAULT 0,
  `option_id0` smallint NOT NULL DEFAULT 0,
  `option_val0` smallint NOT NULL DEFAULT 0,
  `option_parm0` tinyint NOT NULL DEFAULT 0,
  `option_id1` smallint NOT NULL DEFAULT 0,
  `option_val1` smallint NOT NULL DEFAULT 0,
  `option_parm1` tinyint NOT NULL DEFAULT 0,
  `option_id2` smallint NOT NULL DEFAULT 0,
  `option_val2` smallint NOT NULL DEFAULT 0,
  `option_parm2` tinyint NOT NULL DEFAULT 0,
  `option_id3` smallint NOT NULL DEFAULT 0,
  `option_val3` smallint NOT NULL DEFAULT 0,
  `option_parm3` tinyint NOT NULL DEFAULT 0,
  `option_id4` smallint NOT NULL DEFAULT 0,
  `option_val4` smallint NOT NULL DEFAULT 0,
  `option_parm4` tinyint NOT NULL DEFAULT 0,
  `expire_time` int UNSIGNED NOT NULL DEFAULT 0,
  `bound` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `unique_id` bigint UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `account_id`(`account_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1;

-- ----------------------------
-- Table structure for storage7
-- ----------------------------
CREATE TABLE IF NOT EXISTS `storage7`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int UNSIGNED NOT NULL DEFAULT 0,
  `nameid` int UNSIGNED NOT NULL DEFAULT 0,
  `amount` smallint UNSIGNED NOT NULL DEFAULT 0,
  `equip` int UNSIGNED NOT NULL DEFAULT 0,
  `identify` smallint UNSIGNED NOT NULL DEFAULT 0,
  `refine` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `attribute` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `card0` int UNSIGNED NOT NULL DEFAULT 0,
  `card1` int UNSIGNED NOT NULL DEFAULT 0,
  `card2` int UNSIGNED NOT NULL DEFAULT 0,
  `card3` int UNSIGNED NOT NULL DEFAULT 0,
  `option_id0` smallint NOT NULL DEFAULT 0,
  `option_val0` smallint NOT NULL DEFAULT 0,
  `option_parm0` tinyint NOT NULL DEFAULT 0,
  `option_id1` smallint NOT NULL DEFAULT 0,
  `option_val1` smallint NOT NULL DEFAULT 0,
  `option_parm1` tinyint NOT NULL DEFAULT 0,
  `option_id2` smallint NOT NULL DEFAULT 0,
  `option_val2` smallint NOT NULL DEFAULT 0,
  `option_parm2` tinyint NOT NULL DEFAULT 0,
  `option_id3` smallint NOT NULL DEFAULT 0,
  `option_val3` smallint NOT NULL DEFAULT 0,
  `option_parm3` tinyint NOT NULL DEFAULT 0,
  `option_id4` smallint NOT NULL DEFAULT 0,
  `option_val4` smallint NOT NULL DEFAULT 0,
  `option_parm4` tinyint NOT NULL DEFAULT 0,
  `expire_time` int UNSIGNED NOT NULL DEFAULT 0,
  `bound` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `unique_id` bigint UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `account_id`(`account_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1;

-- ----------------------------
-- Table structure for storage8
-- ----------------------------
CREATE TABLE IF NOT EXISTS `storage8`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int UNSIGNED NOT NULL DEFAULT 0,
  `nameid` int UNSIGNED NOT NULL DEFAULT 0,
  `amount` smallint UNSIGNED NOT NULL DEFAULT 0,
  `equip` int UNSIGNED NOT NULL DEFAULT 0,
  `identify` smallint UNSIGNED NOT NULL DEFAULT 0,
  `refine` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `attribute` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `card0` int UNSIGNED NOT NULL DEFAULT 0,
  `card1` int UNSIGNED NOT NULL DEFAULT 0,
  `card2` int UNSIGNED NOT NULL DEFAULT 0,
  `card3` int UNSIGNED NOT NULL DEFAULT 0,
  `option_id0` smallint NOT NULL DEFAULT 0,
  `option_val0` smallint NOT NULL DEFAULT 0,
  `option_parm0` tinyint NOT NULL DEFAULT 0,
  `option_id1` smallint NOT NULL DEFAULT 0,
  `option_val1` smallint NOT NULL DEFAULT 0,
  `option_parm1` tinyint NOT NULL DEFAULT 0,
  `option_id2` smallint NOT NULL DEFAULT 0,
  `option_val2` smallint NOT NULL DEFAULT 0,
  `option_parm2` tinyint NOT NULL DEFAULT 0,
  `option_id3` smallint NOT NULL DEFAULT 0,
  `option_val3` smallint NOT NULL DEFAULT 0,
  `option_parm3` tinyint NOT NULL DEFAULT 0,
  `option_id4` smallint NOT NULL DEFAULT 0,
  `option_val4` smallint NOT NULL DEFAULT 0,
  `option_parm4` tinyint NOT NULL DEFAULT 0,
  `expire_time` int UNSIGNED NOT NULL DEFAULT 0,
  `bound` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `unique_id` bigint UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `account_id`(`account_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1;

-- ----------------------------
-- Table structure for storage9
-- ----------------------------
CREATE TABLE IF NOT EXISTS `storage9`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int UNSIGNED NOT NULL DEFAULT 0,
  `nameid` int UNSIGNED NOT NULL DEFAULT 0,
  `amount` smallint UNSIGNED NOT NULL DEFAULT 0,
  `equip` int UNSIGNED NOT NULL DEFAULT 0,
  `identify` smallint UNSIGNED NOT NULL DEFAULT 0,
  `refine` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `attribute` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `card0` int UNSIGNED NOT NULL DEFAULT 0,
  `card1` int UNSIGNED NOT NULL DEFAULT 0,
  `card2` int UNSIGNED NOT NULL DEFAULT 0,
  `card3` int UNSIGNED NOT NULL DEFAULT 0,
  `option_id0` smallint NOT NULL DEFAULT 0,
  `option_val0` smallint NOT NULL DEFAULT 0,
  `option_parm0` tinyint NOT NULL DEFAULT 0,
  `option_id1` smallint NOT NULL DEFAULT 0,
  `option_val1` smallint NOT NULL DEFAULT 0,
  `option_parm1` tinyint NOT NULL DEFAULT 0,
  `option_id2` smallint NOT NULL DEFAULT 0,
  `option_val2` smallint NOT NULL DEFAULT 0,
  `option_parm2` tinyint NOT NULL DEFAULT 0,
  `option_id3` smallint NOT NULL DEFAULT 0,
  `option_val3` smallint NOT NULL DEFAULT 0,
  `option_parm3` tinyint NOT NULL DEFAULT 0,
  `option_id4` smallint NOT NULL DEFAULT 0,
  `option_val4` smallint NOT NULL DEFAULT 0,
  `option_parm4` tinyint NOT NULL DEFAULT 0,
  `expire_time` int UNSIGNED NOT NULL DEFAULT 0,
  `bound` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `unique_id` bigint UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `account_id`(`account_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1;

-- ----------------------------
-- Table structure for storage10
-- ----------------------------
CREATE TABLE IF NOT EXISTS `storage10`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int UNSIGNED NOT NULL DEFAULT 0,
  `nameid` int UNSIGNED NOT NULL DEFAULT 0,
  `amount` smallint UNSIGNED NOT NULL DEFAULT 0,
  `equip` int UNSIGNED NOT NULL DEFAULT 0,
  `identify` smallint UNSIGNED NOT NULL DEFAULT 0,
  `refine` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `attribute` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `card0` int UNSIGNED NOT NULL DEFAULT 0,
  `card1` int UNSIGNED NOT NULL DEFAULT 0,
  `card2` int UNSIGNED NOT NULL DEFAULT 0,
  `card3` int UNSIGNED NOT NULL DEFAULT 0,
  `option_id0` smallint NOT NULL DEFAULT 0,
  `option_val0` smallint NOT NULL DEFAULT 0,
  `option_parm0` tinyint NOT NULL DEFAULT 0,
  `option_id1` smallint NOT NULL DEFAULT 0,
  `option_val1` smallint NOT NULL DEFAULT 0,
  `option_parm1` tinyint NOT NULL DEFAULT 0,
  `option_id2` smallint NOT NULL DEFAULT 0,
  `option_val2` smallint NOT NULL DEFAULT 0,
  `option_parm2` tinyint NOT NULL DEFAULT 0,
  `option_id3` smallint NOT NULL DEFAULT 0,
  `option_val3` smallint NOT NULL DEFAULT 0,
  `option_parm3` tinyint NOT NULL DEFAULT 0,
  `option_id4` smallint NOT NULL DEFAULT 0,
  `option_val4` smallint NOT NULL DEFAULT 0,
  `option_parm4` tinyint NOT NULL DEFAULT 0,
  `expire_time` int UNSIGNED NOT NULL DEFAULT 0,
  `bound` tinyint UNSIGNED NOT NULL DEFAULT 0,
  `unique_id` bigint UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `account_id`(`account_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1;
