-	script	GiveGift	-1,{
	end;
	OnPCLoginEvent:

	if(getcharid(3) <= 2000203) {
		if(#GOTKAHO == 0) {
			getitem 27232,1;
			dispbottom "MUITO OBRIGADO! VOCE FOI UM DOS PRIMEIROS A CRIAR SUA CONTA NO RAGNAMANIA CHRONOS";
			dispbottom "E COM ISSO NOS MANTEVE MOTIVADOS A TRABALHAR NESTE PROJETO!";
			dispbottom "COMO FORMA DE AGRADECIMENTO, LHE ENTREGAMOS UM PEQUENO APRECO. CHEQUE SEUS EUIPS!";
			dispbottom "ESPERAMOS QUE VOCE GOSTE DA SURPRESA! MUIGO OBRIGADO, MAIS UMA VEZ! LETS ROK!";
			set #GOTKAHO, 1;
		}
	}
	end;
}