// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#include "skill_factory_npc.hpp"

#include "../skill_impl.hpp"
#include "attributechange.cpp"
#include "blindattack.cpp"
#include "curseattack.cpp"
#include "darkpiercing.cpp"
#include "deathsummon.cpp"
#include "demonshockattack.cpp"
#include "defensedisregardattack.cpp"
#include "earthattributeattack.cpp"
#include "earthattributechange.cpp"
#include "fireattributeattack.cpp"
#include "fireattributechange.cpp"
#include "ghostattributeattack.cpp"
#include "ghostattributechange.cpp"
#include "hellburning.cpp"
#include "holyattributeattack.cpp"
#include "holyattributechange.cpp"
#include "jackfrost2.cpp"
#include "maxpainattack.cpp"
#include "metamorphosis.cpp"
#include "multistageattack.cpp"
#include "poisonattack.cpp"
#include "poisonattributeattack.cpp"
#include "poisonattributechange.cpp"
#include "provocation.cpp"
#include "petrifyattack.cpp"
#include "piercingattack.cpp"
#include "randomattack.cpp"
#include "shadowattributeattack.cpp"
#include "shadowattributechange.cpp"
#include "splashattack.cpp"
#include "silenceattack.cpp"
#include "sleepattack.cpp"
#include "spiritdestruction.cpp"
#include "standoffattack.cpp"
#include "stunattack.cpp"
#include "suicide.cpp"
#include "suicidebombing.cpp"
#include "waterattributeattack.cpp"
#include "waterattributechange.cpp"
#include "windattributeattack.cpp"
#include "windattributechange.cpp"
#include "widesuck.cpp"
#include "wideweb.cpp"

std::unique_ptr<const SkillImpl> SkillFactoryNpc::create(const e_skill skill_id) const {
	switch( skill_id ){
		case NPC_ARMORBRAKE:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_ATTRICHANGE:
			return std::make_unique<SkillAttributeChange>();
		case NPC_BARRIER:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_BLEEDING:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_BLEEDING2:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_BLINDATTACK:
			return std::make_unique<SkillBlindAttack>();
		case NPC_CHANGEGROUND:
			return std::make_unique<SkillEarthAttributeChange>();
		case NPC_CHANGEFIRE:
			return std::make_unique<SkillFireAttributeChange>();
		case NPC_CHANGEUNDEAD:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_CHANGEWATER:
			return std::make_unique<SkillWaterAttributeChange>();
		case NPC_CHANGEWIND:
			return std::make_unique<SkillWindAttributeChange>();
		case NPC_CHANGEPOISON:
			return std::make_unique<SkillPoisonAttributeChange>();
		case NPC_CHANGEHOLY:
			return std::make_unique<SkillHolyAttributeChange>();
		case NPC_CHANGEDARKNESS:
			return std::make_unique<SkillShadowAttributeChange>();
		case NPC_CHANGETELEKINESIS:
			return std::make_unique<SkillGhostAttributeChange>();
		case NPC_COMBOATTACK:
			return std::make_unique<SkillMultiStageAttack>();
		case NPC_CRITICALSLASH:
			return std::make_unique<SkillDefenseDisregardAttack>();
		case NPC_CRITICALWOUND:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_CURSEATTACK:
			return std::make_unique<SkillCurseAttack>();
		case NPC_DAMAGE_HEAL:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_DARKCROSS:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_DARKNESSATTACK:
			return std::make_unique<SkillShadowAttributeAttack>();
		case NPC_DARKPIERCING:
			return std::make_unique<SkillDarkPiercing>();
		case NPC_DEATHSUMMON:
			return std::make_unique<SkillDeathSummon>();
		case NPC_DEFENDER:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_FIREATTACK:
			return std::make_unique<SkillFireAttributeAttack>();
		case NPC_GROUNDATTACK:
			return std::make_unique<SkillEarthAttributeAttack>();
		case NPC_GUIDEDATTACK:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_HALLUCINATIONWALK:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_HELLBURNING:
			return std::make_unique<SkillHellBurning>();
		case NPC_HELLPOWER:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_HELMBRAKE:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_HOLYATTACK:
			return std::make_unique<SkillHolyAttributeAttack>();
		case NPC_INVINCIBLE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_JACKFROST:
			return std::make_unique<SkillJackFrost2>();
		case NPC_KEEPING:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_KILLING_AURA:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_MAGICMIRROR:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_MAGICALATTACK:
			return std::make_unique<SkillDemonShockAttack>();
		case NPC_METAMORPHOSIS:
			return std::make_unique<SkillMetamorphosis>();
		case NPC_MAGMA_ERUPTION:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_MAXPAIN:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_MAXPAIN_ATK:
			return std::make_unique<SkillMaxPainAttack>();
		case NPC_MENTALBREAKER:
			return std::make_unique<SkillSpiritDestruction>();
		case NPC_PETRIFYATTACK:
			return std::make_unique<SkillPetrifyAttack>();
		case NPC_PIERCINGATT:
			return std::make_unique<SkillPiercingAttack>();
		case NPC_POISON:
			return std::make_unique<SkillPoisonAttack>();
		case NPC_POISONATTACK:
			return std::make_unique<SkillPoisonAttributeAttack>();
		case NPC_PROVOCATION:
			return std::make_unique<SkillProvocation>();
		case NPC_RANDOMATTACK:
			return std::make_unique<SkillRandomAttack>();
		case NPC_RANGEATTACK:
			return std::make_unique<SkillStandOffAttack>();
		case NPC_SELFDESTRUCTION:
			return std::make_unique<SkillSuicideBombing>();
		case NPC_RELIEVE_OFF:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_RELIEVE_ON:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_SHIELDBRAKE:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_SILENCEATTACK:
			return std::make_unique<SkillSilenceAttack>();
		case NPC_SPLASHATTACK:
			return std::make_unique<SkillSplashAttack>();
		case NPC_SLEEPATTACK:
			return std::make_unique<SkillSleepAttack>();
		case NPC_STUNATTACK:
			return std::make_unique<SkillStunAttack>();
		case NPC_SUICIDE:
			return std::make_unique<SkillNpcSuicide>();
		case NPC_TELEKINESISATTACK:
			return std::make_unique<SkillGhostAttributeAttack>();
		case NPC_UNDEADATTACK:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case NPC_WATERATTACK:
			return std::make_unique<SkillWaterAttributeAttack>();
		case NPC_WIDEWEB:
			return std::make_unique<SkillWideWeb>();
		case NPC_WIDESUCK:
			return std::make_unique<SkillWideSuck>();
		case NPC_WEAPONBRAKER:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NPC_WINDATTACK:
			return std::make_unique<SkillWindAttributeAttack>();

		default:
			return nullptr;
	}
}
