/**
 * DB/Jobs/BabyTable.js
 *
 * List all babies
 *
 * This file is part of ROBrowser, (http://www.robrowser.com/).
 *
 * @author Vincent Thibault
 */

import JobId from './JobConst.js';

export default [
	JobId.NOVICE_B,
	JobId.SUPERNOVICE_B,

	JobId.SWORDMAN_B,
	JobId.MAGICIAN_B,
	JobId.ARCHER_B,
	JobId.ACOLYTE_B,
	JobId.MERCHANT_B,
	JobId.THIEF_B,

	JobId.KNIGHT_B,
	JobId.KNIGHT2_B,
	JobId.PRIEST_B,
	JobId.WIZARD_B,
	JobId.BLACKSMITH_B,
	JobId.HUNTER_B,
	JobId.ASSASSIN_B,
	JobId.CRUSADER_B,
	JobId.CRUSADER2_B,
	JobId.MONK_B,
	JobId.SAGE_B,
	JobId.ROGUE_B,
	JobId.ALCHEMIST_B,
	JobId.BARD_B,
	JobId.DANCER_B,

	JobId.RUNE_KNIGHT_B,
	JobId.RUNE_KNIGHT2_B,
	JobId.ARCHBISHOP_B,
	JobId.WARLOCK_B,
	JobId.MECHANIC_B,
	JobId.RANGER_B,
	JobId.GUILLOTINE_CROSS_B,
	JobId.ROYAL_GUARD_B,
	JobId.ROYAL_GUARD2_B,
	JobId.SURA_B,
	JobId.SORCERER_B,
	JobId.SHADOW_CHASER_B,
	JobId.GENETIC_B,
	JobId.MINSTREL_B,
	JobId.WANDERER_B,

	JobId.SUPERNOVICE2_B,
	JobId.NINJA_B,
	JobId.KAGEROU_B,
	JobId.OBORO_B,
	JobId.TAEKWON_B,
	JobId.STAR_B,
	JobId.LINKER_B,
	JobId.GUNSLINGER_B,
	JobId.REBELLION_B,
	JobId.STAR2_B,
	JobId.STAR_EMPEROR_B,
	JobId.SOUL_REAPER_B,
	JobId.SOUL_REAPER2_B,
	JobId.STAR_EMPEROR2_B,

	JobId.PORING_NOVICE_B,
	JobId.PECO_SWORD_B,
	JobId.FOX_MAGICIAN_B,
	JobId.OSTRICH_ARCHER_B,
	JobId.SHEEP_ACO_B,
	JobId.PIG_MERCHANT_B,
	JobId.OSTRICH_HUNTER_B,
	JobId.DOG_ASSASSIN_B,
	JobId.SHEEP_MONK_B,
	JobId.FOX_SAGE_B,
	JobId.DOG_ROGUE_B,
	JobId.PIG_ALCHE_B,
	JobId.OSTRICH_BARD_B,
	JobId.OSTRICH_DANCER_B,
	JobId.PORING_SNOVICE_B,
	JobId.FOX_WARLOCK_B,
	JobId.SHEEP_ARCB_B,
	JobId.DOG_G_CROSS_B,
	JobId.FOX_SORCERER_B,
	JobId.OSTRICH_MINSTREL_B,
	JobId.OSTRICH_WANDER_B,
	JobId.SHEEP_SURA_B,
	JobId.PIG_GENETIC_B,
	JobId.DOG_THIEF_B,
	JobId.DOG_CHASER_B,
	JobId.PORING_SNOVICE2_B,
	JobId.SHEEP_PRIEST_B,
	JobId.FOX_WIZ_B,
	JobId.PIG_BLACKSMITH_B,
	JobId.PIG_MECHANIC_B,
	JobId.OSTRICH_RANGER_B,
	JobId.LION_KNIGHT_B,
	JobId.LION_ROYAL_GUARD_B,
	JobId.LION_RUNE_KNIGHT_B,
	JobId.LION_CRUSADER_B,

	JobId.DO_SUMMONER_B
];
