// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),

//eduardo
ACMD_DEF2R("clonea", clonea, ATCMD_NOCONSOLE),
ACMD_DEF2R("clonepe", clonepe, ATCMD_NOCONSOLE),
ACMD_DEF2R("clonemp", clonemp, ATCMD_NOCONSOLE),
