// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/

/**
* Extended Vending system [Lilith]
**/
int extended_vending;
int show_broadcast_info;
int show_item_vending;
int ex_vending_info;
int ex_vending_report;
int ex_buying_bound;
int item_zeny;
int item_cash;
