// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/

	//eduardo
	int clone_skill_rate;
	int more_exp_rate;
	int more_exp_rate_f;
	int mvp_raid_mode;
	int mvp_raid_mode_m;
	int sclonepartyexpdist;
	int cur_mstat;
	int cur_attprob;
	int slaveclonepet;	
	int hyperactivesc;
	int scskillbyhotkeys;
	int sceasymode;
	//////
	int nv_a;
	int al_a;	
	int sm_a;
	int ac_a;
	int mg_a;
	int mc_a;
	int tf_a;
	int tk_a;
	int gs_a;
	int nj_a;
	int su_a;
	int snv_a;
	int pr_a;
	int kn_a;
	int ht_a;
	int bs_a;
	int wz_a;
	int sj_a;
	int as_a;
	int rl_a;
	int kg_a;
	int cr_a;
	int sa_a;
	int ba_a;
	int mo_a;
	int am_a;
	int rg_a;
	int sl_a;
