// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
BUILDIN_DEF(itemlink, "i?????"),
BUILDIN_DEF2(itemlink, "itemlink2", "iiiiiirrr"),
BUILDIN_DEF(base62_encode, "i"),
BUILDIN_DEF(base62_decode, "s"),
