// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#include "skill_factory_archer.hpp"

#include "../status_skill_impl.hpp"
#include "../weapon_skill_impl.hpp"

#include "aimedbolt.hpp"
#include "anklesnare.hpp"
#include "arrowshower.hpp"
#include "arrowstorm.hpp"
#include "beaststrafing.hpp"
#include "blastmine.hpp"
#include "blitzbeat.hpp"
#include "camouflage.hpp"
#include "chargearrow.hpp"
#include "claymoretrap.hpp"
#include "clusterbomb.hpp"
#include "cobalttrap.hpp"
#include "concentration.hpp"
#include "crescivebolt.hpp"
#include "deepblindtrap.hpp"
#include "detect.hpp"
#include "detonator.hpp"
#include "doublestrafe.hpp"
#include "electricshocker.hpp"
#include "falconassault.hpp"
#include "fearbreeze.hpp"
#include "firingtrap.hpp"
#include "flametrap.hpp"
#include "flasher.hpp"
#include "focusedarrowstrike.hpp"
#include "freezingtrap.hpp"
#include "galestorm.hpp"
#include "hawkboomerang.hpp"
#include "hawkmastery.hpp"
#include "hawkrush.hpp"
#include "iceboundtrap.hpp"
#include "landmine.hpp"
#include "magentatrap.hpp"
#include "maizetrap.hpp"
#include "makingarrow.hpp"
#include "phantasmicarrow.hpp"
#include "removetrap.hpp"
#include "sandman.hpp"
#include "sensitivekeen.hpp"
#include "shockwavetrap.hpp"
#include "skidtrap.hpp"
#include "solidtrap.hpp"
#include "springtrap.hpp"
#include "swifttrap.hpp"
#include "talkiebox.hpp"
#include "verduretrap.hpp"
#include "wargbite.hpp"
#include "wargdash.hpp"
#include "wargmastery.hpp"
#include "wargrider.hpp"
#include "wargstrike.hpp"
#include "wildwalk.hpp"
#include "windwalker.hpp"

std::unique_ptr<const SkillImpl> SkillFactoryArcher::create(const e_skill skill_id) const {
	switch( skill_id ){
		case AC_CHARGEARROW:
			return std::make_unique<SkillChargeArrow>();
		case AC_CONCENTRATION:
			return std::make_unique<SkillConcentration>();
		case AC_DOUBLE:
			return std::make_unique<SkillDoubleStrafe>();
		case AC_MAKINGARROW:
			return std::make_unique<SkillMakingArrow>();
		case AC_SHOWER:
			return std::make_unique<SkillArrowShower>();
		case BA_DISSONANCE:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case BA_MUSICALSTRIKE:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case CG_ARROWVULCAN:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case DC_THROWARROW:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case HT_ANKLESNARE:
			return std::make_unique<SkillAnkleSnare>();
		case HT_BLASTMINE:
			return std::make_unique<SkillBlastMine>();
		case HT_BLITZBEAT:
			return std::make_unique<SkillBlitzBeat>();
		case HT_CLAYMORETRAP:
			return std::make_unique<SkillClaymoreTrap>();
		case HT_DETECTING:
			return std::make_unique<SkillDetect>();
		case HT_FLASHER:
			return std::make_unique<SkillFlasher>();
		case HT_FREEZINGTRAP:
			return std::make_unique<SkillFreezingTrap>();
		case HT_LANDMINE:
			return std::make_unique<SkillLandMine>();
		case HT_PHANTASMIC:
			return std::make_unique<SkillPhantasmicArrow>();
		case HT_POWER:
			return std::make_unique<SkillBeastStrafing>();
		case HT_REMOVETRAP:
			return std::make_unique<SkillRemoveTrap>();
		case HT_SANDMAN:
			return std::make_unique<SkillSandman>();
		case HT_SHOCKWAVE:
			return std::make_unique<SkillShockwaveTrap>();
		case HT_SKIDTRAP:
			return std::make_unique<SkillSkidTrap>();
		case HT_SPRINGTRAP:
			return std::make_unique<SkillSpringTrap>();
		case HT_TALKIEBOX:
			return std::make_unique<SkillTalkieBox>();
		case RA_AIMEDBOLT:
			return std::make_unique<SkillAimedBolt>();
		case RA_ARROWSTORM:
			return std::make_unique<SkillArrowStorm>();
		case RA_CAMOUFLAGE:
			return std::make_unique<SkillCamouflage>();
		case RA_CLUSTERBOMB:
			return std::make_unique<SkillClusterBomb>();
		case RA_COBALTTRAP:
			return std::make_unique<SkillCobaltTrap>();
		case RA_DETONATOR:
			return std::make_unique<SkillDetonator>();
		case RA_ELECTRICSHOCKER:
			return std::make_unique<SkillElectricShocker>();
		case RA_FEARBREEZE:
			return std::make_unique<SkillFearBreeze>();
		case RA_FIRINGTRAP:
			return std::make_unique<SkillFiringTrap>();
		case RA_ICEBOUNDTRAP:
			return std::make_unique<SkillIceboundTrap>();
		case RA_MAGENTATRAP:
			return std::make_unique<SkillMagentaTrap>();
		case RA_MAIZETRAP:
			return std::make_unique<SkillMaizeTrap>();
		case RA_SENSITIVEKEEN:
			return std::make_unique<SkillSensitiveKeen>();
		case RA_UNLIMIT:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case RA_VERDURETRAP:
			return std::make_unique<SkillVerdureTrap>();
		case RA_WUGBITE:
			return std::make_unique<SkillWargBite>();
		case RA_WUGDASH:
			return std::make_unique<SkillWargDash>();
		case RA_WUGMASTERY:
			return std::make_unique<SkillWargMastery>();
		case RA_WUGRIDER:
			return std::make_unique<SkillWargRider>();
		case RA_WUGSTRIKE:
			return std::make_unique<SkillWargStrike>();
		case SN_FALCONASSAULT:
			return std::make_unique<SkillFalconAssault>();
		case SN_SHARPSHOOTING:
			return std::make_unique<SkillFocusedArrowStrike>();
		case SN_SIGHT:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SN_WINDWALK:
			return std::make_unique<SkillWindWalker>();
		case TR_KVASIR_SONATA:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case TR_MYSTIC_SYMPHONY:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WH_CALAMITYGALE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WH_CRESCIVE_BOLT:
			return std::make_unique<SkillCresciveBolt>();
		case WH_DEEPBLINDTRAP:
			return std::make_unique<SkillDeepBlindTrap>();
		case WH_FLAMETRAP:
			return std::make_unique<SkillFlameTrap>();
		case WH_GALESTORM:
			return std::make_unique<SkillGaleStorm>();
		case WH_HAWKBOOMERANG:
			return std::make_unique<SkillHawkBoomerang>();
		case WH_HAWKRUSH:
			return std::make_unique<SkillHawkRush>();
		case WH_HAWK_M:
			return std::make_unique<SkillHawkMastery>();
		case WH_SOLIDTRAP:
			return std::make_unique<SkillSolidTrap>();
		case WH_SWIFTTRAP:
			return std::make_unique<SkillSwiftTrap>();
		case WH_WILD_WALK:
			return std::make_unique<SkillWildWalk>();
		case WH_WIND_SIGN:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WM_GREAT_ECHO:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case WM_SEVERE_RAINSTORM_MELEE:
			return std::make_unique<WeaponSkillImpl>(skill_id);

		default:
			return nullptr;
	}
	return nullptr;
}
