// Ambient declarations for the host-injected scripting API.
//
// IMPLEMENTATION STATUS: dialog primitives (mes / next / select / close)
// are hand-implemented in C++. ctx.player carries a per-click snapshot
// of identity + stats + vitals + location, auto-generated by the
// libclang-driven binding tool (tools/scripting/gen_bindings.py). The
// full action surface (player ops, world ops, party/guild/instance/…)
// is wired in follow-up milestones.
//
// SYNC-LOOKING SCRIPTS: all the awaits are inserted at build time by
// npc-ts/build/auto-await-plugin.mjs. Authors write `ctx.mes("…")` /
// `const c = ctx.select([…])` as if synchronous; the build emits the
// equivalent `await ctx.mes(…)` so V8 actually suspends correctly.

// PlayerInfo is auto-generated from rAthena's mmo_charstatus +
// map_session_data structs via libclang. Re-exported here so authors
// can reference `PlayerInfo` without knowing about the codegen file
// path. The generated file lives in npc-ts/generated/ (gitignored).
export type { PlayerInfo } from "../generated/player.generated";
import type { PlayerInfo as _PlayerInfo } from "../generated/player.generated";

declare global {
    /**
     * Register one or more world-placed NPCs. Variadic.
     *
     * @example
     * registerNpc({ name: "kafra#01", map: "prontera", x: 155, y: 183,
     *               sprite: 115, async onClick(ctx) { ctx.mes("Hi!"); } });
     */
    function registerNpc(...npcs: NpcRegistration[]): void;

    type NpcContext      = import("./api").NpcContext;
    type NpcHandler      = import("./api").NpcHandler;
    type NpcRegistration = import("./api").NpcRegistration;
    type NpcDuplicate    = import("./api").NpcDuplicate;
    type PlayerInfo      = import("./api").PlayerInfo;
}

/** Async handler — MUST be declared `async`. The auto-await build step
 *  inserts awaits in the body, which only work inside async. */
export type NpcHandler = (ctx: NpcContext) => Promise<void>;

export interface NpcRegistration {
    map: string;
    x: number;
    y: number;
    dir?: number;
    sprite: number;
    name: string;
    triggerArea?: { xs: number; ys: number };

    onClick?: NpcHandler;

    /**
     * Placed copies of this NPC. Each duplicate spawns at its own
     * `(map, x, y)` with its own `name` but SHARES the parent's
     * hook closures. Mirrors rAthena's `duplicate(Name)` syntax.
     */
    duplicates?: NpcDuplicate[];
}

export interface NpcDuplicate {
    name: string;
    map: string;
    x: number;
    y: number;
    dir?: number;
    sprite?: number;
}

/**
 * The `ctx` argument every NPC hook receives. Dialog primitives are
 * the only methods wired today; the broader surface lands in
 * follow-up milestones.
 */
export interface NpcContext {
    /** Append a line to the open dialog window. Non-suspending. */
    mes(text: string): void;
    /** Render a "Next" button; suspend until clicked. */
    next(): void;
    /** Render a menu; 0-based index, -1 on cancel. */
    select(options: string[]): number;
    /** Alias of {@link select}. */
    menu(options: string[]): number;
    /** Render a "Close" button; suspend then end the dialog. */
    close(): void;

    /**
     * Snapshot of the clicking player. Read at click time — does NOT
     * track mutations made later in the dialog. `null` for hooks
     * without an attached player (onInit / onTimer / onClock).
     */
    player: _PlayerInfo | null;
}
