/**
 * DB/Monsters/AttackEffectTable.js
 *
 * Monster/Entity Special Attack Effect Table
 *
 * This file is part of ROBrowser, (http://www.robrowser.com/).
 */

const AE = {
	PROJECTILE: {},
	SPAWN: {}
};

// We don't have a complete job const table with monster and other ids, so i put this here. When we do have it, replace with the Job Const require.
const JOB = {
	ARCHER_GUARDIAN: 1285,
	ARCHER_SKELETON: 1016,
	G_ARCHER_SKELETON: 1420,
	MUTANT_ARCHER_SKELETON: 3034,
	P_ARCHER_SKELETON: 3445,
	ILL_ARCHER_SKELETON: 3763,

	ORC_ARCHER: 1189,
	G_ORC_ARCHER: 1473,
	I_ORC_ARCHER: 1982,
	ORC_ARCHER_ANNIV: 3130,
	MD_ORC_ARCHER: 3900,

	GOBLIN_ARCHER: 1258,
	G_GOBLIN_ARCHER: 1577,

	RAYDRIC_ARCHER: 1276,
	G_RAYDRIC_ARCHER: 1453,
	MG_RAYDRIC_ARCHER: 2469,
	MG_RAYDRIC_ARCHER_H: 3144,
	RAYDRIC_ARCHER_H: 20368,
	MD_C_RAYDRIC_ARCHER: 20578,
	MD_T_RAYDRIC_ARCHER: 21010,

	KOBOLD_ARCHER: 1282,
	G_KOBOLD_ARCHER: 1455,
	GLD_KOBOLD_ARCHER: 2287,
	C1_KOBOLD_ARCHER: 2784,

	GARGOYLE: 1253,
	G_GARGOYLE: 1597,
	C3_GARGOYLE: 2826,
	C4_GARGOYLE: 2827,
	MM_M_GARGOYLE: 3197,
	MIN_G_GARGOYLE: 3435,
	GARGOYLE_STATUE: 10070,
	GARGOYLE_H: 20369,
	MD_T_GARGOYLE: 21028,
	BIO_ICE_GARGOYLE: 22256,

	MER_ARCHER01: 6017,
	MER_ARCHER02: 6018,
	MER_ARCHER03: 6019,
	MER_ARCHER04: 6020,
	MER_ARCHER05: 6021,
	MER_ARCHER06: 6022,
	MER_ARCHER07: 6023,
	MER_ARCHER08: 6024,
	MER_ARCHER09: 6025,
	MER_ARCHER10: 6026,

	PARASITE: 1500,
	G_PARASITE: 1555,
	C2_PARASITE: 2720,
	MD_T_PARASITE1: 21005,

	STONE_SHOOTER: 1495,
	ILL_STONE_SHOOTER: 20274,
	MD_T_STONE_SHOOTER: 20999,

	WOOTAN_SHOOTER: 1498,
	ILL_WOOTAN_SHOOTER: 20275,
	G_ILL_WOOTAN_SHOOTER: 20279,

	LIVE_PEACH_TREE: 1410,
	G_LIVE_PEACH_TREE: 1550,
	C2_LIVE_PEACH_TREE: 2775,

	EVIL_CLOUD_HERMIT: 1412,
	G_EVIL_CLOUD_HERMIT: 1531,
	T_EVIL_CLOUD_HERMIT: 2935,
	MD_T_EVIL_CLOUD_HERMIT: 21023,

	RAGGED_ZOMBIE: 1865,
	RAGGED_ZOMBIE_H: 20371,
	ECO_RAGGED_ZOMBIE: 21574,

	POTON_CANON: 1664,
	POTON_CANON_1: 1665,
	POTON_CANON_2: 1666,
	POTON_CANON_3: 1667,
	G_POTON_CANON: 1683,
	A_POTON_CANON: 1724,

	LADY_TANEE: 1688,
	MH_LADY_TANEE: 3288,
	VH_LADY_TANEE1: 20238,

	MANDRAGORA: 1020,
	G_MANDRAGORA: 1589,
	E_MANDRAGORA: 1859,
	C2_MANDRAGORA: 2765,
	DR_MANDRAGORA: 3506,

	HYDRA: 1068,
	G_HYDRA: 1579,
	E_HYDRA: 2081,

	THA_ODIUM: 1704,
	G_THA_ODIUM: 1709,
	MD_THA_ODIUM: 20796,

	DROSERA: 1781,
	C2_DROSERA: 2844,

	MAVKA: 1884,
	G_MAVKA: 1886,

	ENTWEIHEN: 1957,
	G_ENTWEIHEN_R: 1958,
	G_ENTWEIHEN_H: 1959,
	G_ENTWEIHEN_M: 1960,
	G_ENTWEIHEN_S: 1961,
	VH_ENTWEIHEN: 20207,
	VH_ENTWEIHEN_R: 20250,
	VH_ENTWEIHEN_H: 20251,
	VH_ENTWEIHEN_M: 20252,
	VH_ENTWEIHEN_S: 20253,
	MD_G_ENTWEIHEN_M: 20997
};

// Arrow projectile
AE.PROJECTILE[JOB.ARCHER_GUARDIAN] =
	AE.PROJECTILE[JOB.ARCHER_SKELETON] =
	AE.PROJECTILE[JOB.G_ARCHER_SKELETON] =
	AE.PROJECTILE[JOB.MUTANT_ARCHER_SKELETON] =
	AE.PROJECTILE[JOB.P_ARCHER_SKELETON] =
	AE.PROJECTILE[JOB.ILL_ARCHER_SKELETON] =
	AE.PROJECTILE[JOB.ORC_ARCHER] =
	AE.PROJECTILE[JOB.G_ORC_ARCHER] =
	AE.PROJECTILE[JOB.I_ORC_ARCHER] =
	AE.PROJECTILE[JOB.ORC_ARCHER_ANNIV] =
	AE.PROJECTILE[JOB.MD_ORC_ARCHER] =
	AE.PROJECTILE[JOB.GOBLIN_ARCHER] =
	AE.PROJECTILE[JOB.G_GOBLIN_ARCHER] =
	AE.PROJECTILE[JOB.RAYDRIC_ARCHER] =
	AE.PROJECTILE[JOB.G_RAYDRIC_ARCHER] =
	AE.PROJECTILE[JOB.MG_RAYDRIC_ARCHER] =
	AE.PROJECTILE[JOB.MG_RAYDRIC_ARCHER_H] =
	AE.PROJECTILE[JOB.RAYDRIC_ARCHER_H] =
	AE.PROJECTILE[JOB.MD_C_RAYDRIC_ARCHER] =
	AE.PROJECTILE[JOB.MD_T_RAYDRIC_ARCHER] =
	AE.PROJECTILE[JOB.KOBOLD_ARCHER] =
	AE.PROJECTILE[JOB.G_KOBOLD_ARCHER] =
	AE.PROJECTILE[JOB.GLD_KOBOLD_ARCHER] =
	AE.PROJECTILE[JOB.C1_KOBOLD_ARCHER] =
	AE.PROJECTILE[JOB.GARGOYLE] =
	AE.PROJECTILE[JOB.G_GARGOYLE] =
	AE.PROJECTILE[JOB.C3_GARGOYLE] =
	AE.PROJECTILE[JOB.C4_GARGOYLE] =
	AE.PROJECTILE[JOB.MM_M_GARGOYLE] =
	AE.PROJECTILE[JOB.MIN_G_GARGOYLE] =
	AE.PROJECTILE[JOB.GARGOYLE_STATUE] =
	AE.PROJECTILE[JOB.GARGOYLE_H] =
	AE.PROJECTILE[JOB.MD_T_GARGOYLE] =
	AE.PROJECTILE[JOB.BIO_ICE_GARGOYLE] =
	AE.PROJECTILE[JOB.MER_ARCHER01] =
	AE.PROJECTILE[JOB.MER_ARCHER02] =
	AE.PROJECTILE[JOB.MER_ARCHER03] =
	AE.PROJECTILE[JOB.MER_ARCHER04] =
	AE.PROJECTILE[JOB.MER_ARCHER05] =
	AE.PROJECTILE[JOB.MER_ARCHER06] =
	AE.PROJECTILE[JOB.MER_ARCHER07] =
	AE.PROJECTILE[JOB.MER_ARCHER08] =
	AE.PROJECTILE[JOB.MER_ARCHER09] =
	AE.PROJECTILE[JOB.MER_ARCHER10] =
		'ef_arrow_projectile';

// Special projectile
AE.PROJECTILE[JOB.PARASITE] =
	AE.PROJECTILE[JOB.G_PARASITE] =
	AE.PROJECTILE[JOB.C2_PARASITE] =
	AE.PROJECTILE[JOB.MD_T_PARASITE1] =
		'ef_parasite_projectile';

AE.PROJECTILE[JOB.STONE_SHOOTER] =
	AE.PROJECTILE[JOB.ILL_STONE_SHOOTER] =
	AE.PROJECTILE[JOB.MD_T_STONE_SHOOTER] =
		'ef_stone_shooter_projectile';

AE.PROJECTILE[JOB.WOOTAN_SHOOTER] =
	AE.PROJECTILE[JOB.ILL_WOOTAN_SHOOTER] =
	AE.PROJECTILE[JOB.G_ILL_WOOTAN_SHOOTER] =
		'ef_wootan_shooter_projectile';

AE.PROJECTILE[JOB.LIVE_PEACH_TREE] =
	AE.PROJECTILE[JOB.G_LIVE_PEACH_TREE] =
	AE.PROJECTILE[JOB.C2_LIVE_PEACH_TREE] =
		'ef_peach_tree_projectile';

AE.PROJECTILE[JOB.EVIL_CLOUD_HERMIT] =
	AE.PROJECTILE[JOB.G_EVIL_CLOUD_HERMIT] =
	AE.PROJECTILE[JOB.T_EVIL_CLOUD_HERMIT] =
	AE.PROJECTILE[JOB.MD_T_EVIL_CLOUD_HERMIT] =
		'ef_hermit_projectile';

AE.PROJECTILE[JOB.RAGGED_ZOMBIE] =
	AE.PROJECTILE[JOB.RAGGED_ZOMBIE_H] =
	AE.PROJECTILE[JOB.ECO_RAGGED_ZOMBIE] =
		'ef_ragged_projectile';

AE.PROJECTILE[JOB.POTON_CANON] = 'ef_canon_projectile';
AE.PROJECTILE[JOB.POTON_CANON_1] = 'ef_canon1_projectile';
AE.PROJECTILE[JOB.POTON_CANON_2] = 'ef_canon2_projectile';
AE.PROJECTILE[JOB.POTON_CANON_3] = 'ef_canon3_projectile';
AE.PROJECTILE[JOB.G_POTON_CANON] = 'ef_canon_projectile';
AE.PROJECTILE[JOB.A_POTON_CANON] = 'ef_canon_projectile';

AE.PROJECTILE[JOB.LADY_TANEE] =
	AE.PROJECTILE[JOB.MH_LADY_TANEE] =
	AE.PROJECTILE[JOB.VH_LADY_TANEE1] =
		'ef_tanee_projectile';

// Spawn
AE.SPAWN[JOB.MANDRAGORA] =
	AE.SPAWN[JOB.G_MANDRAGORA] =
	AE.SPAWN[JOB.E_MANDRAGORA] =
	AE.SPAWN[JOB.C2_MANDRAGORA] =
	AE.SPAWN[JOB.DR_MANDRAGORA] =
		'ef_mandragora_attack';

AE.SPAWN[JOB.HYDRA] = AE.SPAWN[JOB.G_HYDRA] = AE.SPAWN[JOB.E_HYDRA] = 'ef_hydra_attack';

AE.SPAWN[JOB.THA_ODIUM] = AE.SPAWN[JOB.G_THA_ODIUM] = AE.SPAWN[JOB.MD_THA_ODIUM] = 'ef_odium_attack';

AE.SPAWN[JOB.DROSERA] = AE.SPAWN[JOB.C2_DROSERA] = 'ef_drosera_attack';

AE.SPAWN[JOB.MAVKA] = AE.SPAWN[JOB.G_MAVKA] = 'ef_mavka_attack';

AE.SPAWN[JOB.ENTWEIHEN] =
	AE.SPAWN[JOB.G_ENTWEIHEN_R] =
	AE.SPAWN[JOB.G_ENTWEIHEN_H] =
	AE.SPAWN[JOB.G_ENTWEIHEN_M] =
	AE.SPAWN[JOB.G_ENTWEIHEN_S] =
	AE.SPAWN[JOB.VH_ENTWEIHEN] =
	AE.SPAWN[JOB.VH_ENTWEIHEN_R] =
	AE.SPAWN[JOB.VH_ENTWEIHEN_H] =
	AE.SPAWN[JOB.VH_ENTWEIHEN_M] =
	AE.SPAWN[JOB.VH_ENTWEIHEN_S] =
	AE.SPAWN[JOB.MD_G_ENTWEIHEN_M] =
		'ef_entweihen_attack';

export default AE;
