import SK from './SkillConst.js';
import JobId from 'DB/Jobs/JobConst.js';

const SkillTreeView = {};

SkillTreeView[JobId.NOVICE] = {
	list: 1,
	beforeJob: null,
	[SK.NV_BASIC]: 0,
	[SK.NV_FIRSTAID]: 7,
	[SK.NV_TRICKDEAD]: 14
};
SkillTreeView[JobId.SWORDMAN] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.SM_SWORD]: 1,
	[SK.SM_RECOVERY]: 2,
	[SK.SM_BASH]: 3,
	[SK.SM_PROVOKE]: 4,
	[SK.SM_AUTOBERSERK]: 5,
	[SK.SM_MOVINGRECOVERY]: 6,
	[SK.SM_TWOHAND]: 8,
	[SK.SM_MAGNUM]: 10,
	[SK.SM_ENDURE]: 11,
	[SK.SM_FATALBLOW]: 12
};
SkillTreeView[JobId.MAGICIAN] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.MG_STONECURSE]: 1,
	[SK.MG_COLDBOLT]: 2,
	[SK.MG_LIGHTNINGBOLT]: 3,
	[SK.MG_NAPALMBEAT]: 4,
	[SK.MG_FIREBOLT]: 5,
	[SK.MG_SIGHT]: 6,
	[SK.MG_SRECOVERY]: 8,
	[SK.MG_FROSTDIVER]: 9,
	[SK.MG_THUNDERSTORM]: 10,
	[SK.MG_SOULSTRIKE]: 11,
	[SK.MG_FIREBALL]: 12,
	[SK.MG_ENERGYCOAT]: 13,
	[SK.MG_SAFETYWALL]: 18,
	[SK.MG_FIREWALL]: 19
};
SkillTreeView[JobId.ARCHER] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.AC_DOUBLE]: 2,
	[SK.AC_OWL]: 3,
	[SK.AC_CHARGEARROW]: 5,
	[SK.AC_SHOWER]: 9,
	[SK.AC_VULTURE]: 10,
	[SK.AC_MAKINGARROW]: 12,
	[SK.AC_CONCENTRATION]: 17
};
SkillTreeView[JobId.ACOLYTE] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.AL_RUWACH]: 1,
	[SK.AL_HEAL]: 2,
	[SK.AL_HOLYWATER]: 3,
	[SK.AL_DP]: 5,
	[SK.AL_HOLYLIGHT]: 6,
	[SK.AL_TELEPORT]: 8,
	[SK.AL_CURE]: 9,
	[SK.AL_INCAGI]: 10,
	[SK.AL_BLESSING]: 11,
	[SK.AL_DEMONBANE]: 12,
	[SK.AL_ANGELUS]: 13,
	[SK.AL_WARP]: 15,
	[SK.AL_DECAGI]: 17,
	[SK.AL_CRUCIS]: 19,
	[SK.AL_PNEUMA]: 22
};
SkillTreeView[JobId.MERCHANT] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.MC_INCCARRY]: 1,
	[SK.MC_MAMMONITE]: 3,
	[SK.MC_IDENTIFY]: 4,
	[SK.MC_LOUD]: 5,
	[SK.MC_DISCOUNT]: 8,
	[SK.MC_PUSHCART]: 9,
	[SK.MC_CHANGECART]: 12,
	[SK.MC_CARTDECORATE]: 13,
	[SK.MC_OVERCHARGE]: 15,
	[SK.MC_VENDING]: 16,
	[SK.MC_CARTREVOLUTION]: 19
};
SkillTreeView[JobId.THIEF] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.TF_DOUBLE]: 1,
	[SK.TF_STEAL]: 2,
	[SK.TF_POISON]: 3,
	[SK.TF_SPRINKLESAND]: 4,
	[SK.TF_THROWSTONE]: 5,
	[SK.TF_MISS]: 8,
	[SK.TF_HIDING]: 9,
	[SK.TF_DETOXIFY]: 10,
	[SK.TF_BACKSLIDING]: 11,
	[SK.TF_PICKSTONE]: 12
};
SkillTreeView[JobId.KNIGHT] = {
	list: 2,
	beforeJob: JobId.SWORDMAN,
	[SK.KN_TWOHANDQUICKEN]: 0,
	[SK.KN_AUTOCOUNTER]: 1,
	[SK.KN_RIDING]: 2,
	[SK.KN_SPEARMASTERY]: 3,
	[SK.KN_CHARGEATK]: 6,
	[SK.KN_BOWLINGBASH]: 8,
	[SK.KN_CAVALIERMASTERY]: 9,
	[SK.KN_PIERCE]: 10,
	[SK.KN_ONEHAND]: 13,
	[SK.KN_SPEARBOOMERANG]: 16,
	[SK.KN_SPEARSTAB]: 17,
	[SK.KN_BRANDISHSPEAR]: 24
};
SkillTreeView[JobId.PRIEST] = {
	list: 2,
	beforeJob: JobId.ACOLYTE,
	[SK.PR_KYRIE]: 0,
	[SK.PR_MAGNIFICAT]: 1,
	[SK.PR_STRECOVERY]: 2,
	[SK.MG_SRECOVERY]: 3,
	[SK.PR_LEXDIVINA]: 4,
	[SK.PR_IMPOSITIO]: 5,
	[SK.PR_SANCTUARY]: 6,
	[SK.PR_GLORIA]: 7,
	[SK.PR_SLOWPOISON]: 8,
	[SK.ALL_RESURRECTION]: 9,
	[SK.PR_LEXAETERNA]: 11,
	[SK.PR_SUFFRAGIUM]: 12,
	[SK.PR_ASPERSIO]: 13,
	[SK.PR_BENEDICTIO]: 14,
	[SK.PR_MACEMASTERY]: 15,
	[SK.PR_TURNUNDEAD]: 16,
	[SK.MG_SAFETYWALL]: 20,
	[SK.PR_MAGNUS]: 25,
	[SK.PR_REDEMPTIO]: 27
};
SkillTreeView[JobId.WIZARD] = {
	list: 2,
	beforeJob: JobId.MAGICIAN,
	[SK.WZ_ESTIMATION]: 0,
	[SK.WZ_ICEWALL]: 1,
	[SK.WZ_JUPITEL]: 2,
	[SK.WZ_EARTHSPIKE]: 3,
	[SK.WZ_SIGHTRASHER]: 4,
	[SK.WZ_FIREPILLAR]: 5,
	[SK.WZ_SIGHTBLASTER]: 6,
	[SK.WZ_FROSTNOVA]: 8,
	[SK.WZ_VERMILION]: 9,
	[SK.WZ_HEAVENDRIVE]: 10,
	[SK.WZ_METEOR]: 11,
	[SK.WZ_WATERBALL]: 15,
	[SK.WZ_QUAGMIRE]: 17,
	[SK.WZ_STORMGUST]: 22
};
SkillTreeView[JobId.BLACKSMITH] = {
	list: 2,
	beforeJob: JobId.MERCHANT,
	[SK.BS_IRON]: 0,
	[SK.BS_HILTBINDING]: 1,
	[SK.BS_SKINTEMPER]: 2,
	[SK.BS_HAMMERFALL]: 3,
	[SK.BS_DAGGER]: 5,
	[SK.BS_STEEL]: 7,
	[SK.BS_ENCHANTEDSTONE]: 8,
	[SK.BS_WEAPONRESEARCH]: 9,
	[SK.BS_ADRENALINE]: 10,
	[SK.BS_SPEAR]: 11,
	[SK.BS_SWORD]: 12,
	[SK.BS_KNUCKLE]: 13,
	[SK.BS_FINDINGORE]: 14,
	[SK.BS_ORIDEOCON]: 15,
	[SK.BS_REPAIRWEAPON]: 16,
	[SK.BS_WEAPONPERFECT]: 17,
	[SK.BS_OVERTHRUST]: 18,
	[SK.BS_TWOHANDSWORD]: 19,
	[SK.BS_MACE]: 20,
	[SK.BS_MAXIMIZE]: 24,
	[SK.BS_AXE]: 26,
	[SK.BS_ADRENALINE2]: 31,
	[SK.BS_GREED]: 33,
	[SK.BS_UNFAIRLYTRICK]: 34
};
SkillTreeView[JobId.HUNTER] = {
	list: 2,
	beforeJob: JobId.ARCHER,
	[SK.HT_BEASTBANE]: 0,
	[SK.HT_SKIDTRAP]: 2,
	[SK.HT_LANDMINE]: 4,
	[SK.HT_POWER]: 6,
	[SK.HT_FALCON]: 7,
	[SK.HT_FLASHER]: 9,
	[SK.HT_ANKLESNARE]: 10,
	[SK.HT_REMOVETRAP]: 11,
	[SK.HT_PHANTASMIC]: 13,
	[SK.HT_BLITZBEAT]: 14,
	[SK.HT_SANDMAN]: 15,
	[SK.HT_FREEZINGTRAP]: 16,
	[SK.HT_SHOCKWAVE]: 17,
	[SK.HT_SPRINGTRAP]: 18,
	[SK.HT_DETECTING]: 19,
	[SK.HT_STEELCROW]: 21,
	[SK.HT_BLASTMINE]: 22,
	[SK.HT_TALKIEBOX]: 24,
	[SK.HT_CLAYMORETRAP]: 29
};
SkillTreeView[JobId.ASSASSIN] = {
	list: 2,
	beforeJob: JobId.THIEF,
	[SK.AS_RIGHT]: 0,
	[SK.AS_KATAR]: 1,
	[SK.AS_CLOAKING]: 2,
	[SK.AS_ENCHANTPOISON]: 3,
	[SK.AS_VENOMKNIFE]: 6,
	[SK.AS_LEFT]: 7,
	[SK.AS_SONICBLOW]: 8,
	[SK.AS_VENOMDUST]: 10,
	[SK.AS_POISONREACT]: 11,
	[SK.AS_SONICACCEL]: 13,
	[SK.AS_GRIMTOOTH]: 15,
	[SK.AS_SPLASHER]: 17
};
SkillTreeView[JobId.CRUSADER] = {
	list: 2,
	beforeJob: JobId.SWORDMAN,
	[SK.CR_TRUST]: 0,
	[SK.CR_AUTOGUARD]: 2,
	[SK.KN_SPEARMASTERY]: 4,
	[SK.KN_RIDING]: 5,
	[SK.CR_SHRINK]: 6,
	[SK.AL_CURE]: 7,
	[SK.CR_HOLYCROSS]: 8,
	[SK.CR_SHIELDCHARGE]: 9,
	[SK.CR_SPEARQUICKEN]: 11,
	[SK.KN_CAVALIERMASTERY]: 12,
	[SK.AL_DP]: 14,
	[SK.CR_GRANDCROSS]: 15,
	[SK.CR_SHIELDBOOMERANG]: 16,
	[SK.AL_DEMONBANE]: 21,
	[SK.CR_REFLECTSHIELD]: 23,
	[SK.CR_DEFENDER]: 24,
	[SK.AL_HEAL]: 28,
	[SK.CR_DEVOTION]: 29,
	[SK.CR_PROVIDENCE]: 35
};
SkillTreeView[JobId.MONK] = {
	list: 2,
	beforeJob: JobId.ACOLYTE,
	[SK.MO_IRONHAND]: 0,
	[SK.MO_CALLSPIRITS]: 1,
	[SK.MO_DODGE]: 2,
	[SK.MO_TRIPLEATTACK]: 3,
	[SK.MO_KITRANSLATION]: 5,
	[SK.MO_ABSORBSPIRITS]: 7,
	[SK.MO_INVESTIGATE]: 8,
	[SK.MO_BLADESTOP]: 9,
	[SK.MO_CHAINCOMBO]: 10,
	[SK.MO_BALKYOUNG]: 12,
	[SK.MO_EXPLOSIONSPIRITS]: 14,
	[SK.MO_FINGEROFFENSIVE]: 15,
	[SK.MO_SPIRITSRECOVERY]: 16,
	[SK.MO_COMBOFINISH]: 17,
	[SK.MO_EXTREMITYFIST]: 22,
	[SK.MO_STEELBODY]: 24,
	[SK.MO_BODYRELOCATION]: 30
};
SkillTreeView[JobId.SAGE] = {
	list: 2,
	beforeJob: JobId.MAGICIAN,
	[SK.SA_ADVANCEDBOOK]: 0,
	[SK.WZ_ESTIMATION]: 1,
	[SK.SA_ELEMENTWATER]: 2,
	[SK.SA_ELEMENTWIND]: 3,
	[SK.SA_ELEMENTGROUND]: 4,
	[SK.SA_ELEMENTFIRE]: 5,
	[SK.SA_CREATECON]: 6,
	[SK.SA_DRAGONOLOGY]: 7,
	[SK.SA_SEISMICWEAPON]: 8,
	[SK.SA_CASTCANCEL]: 9,
	[SK.SA_MAGICROD]: 10,
	[SK.SA_FROSTWEAPON]: 11,
	[SK.SA_LIGHTNINGLOADER]: 12,
	[SK.SA_FLAMELAUNCHER]: 13,
	[SK.WZ_EARTHSPIKE]: 15,
	[SK.SA_FREECAST]: 16,
	[SK.SA_SPELLBREAKER]: 17,
	[SK.SA_DELUGE]: 18,
	[SK.SA_VIOLENTGALE]: 19,
	[SK.SA_VOLCANO]: 20,
	[SK.WZ_HEAVENDRIVE]: 22,
	[SK.SA_AUTOSPELL]: 23,
	[SK.SA_DISPELL]: 24,
	[SK.SA_LANDPROTECTOR]: 26,
	[SK.SA_ABRACADABRA]: 33
};
SkillTreeView[JobId.ROGUE] = {
	list: 2,
	beforeJob: JobId.THIEF,
	[SK.AC_VULTURE]: 0,
	[SK.RG_TUNNELDRIVE]: 1,
	[SK.RG_SNATCHER]: 2,
	[SK.RG_STRIPHELM]: 3,
	[SK.SM_SWORD]: 4,
	[SK.RG_CLOSECONFINE]: 5,
	[SK.AC_DOUBLE]: 7,
	[SK.RG_STEALCOIN]: 9,
	[SK.RG_STRIPSHIELD]: 10,
	[SK.RG_GANGSTER]: 11,
	[SK.HT_REMOVETRAP]: 14,
	[SK.RG_BACKSTAP]: 16,
	[SK.RG_STRIPARMOR]: 17,
	[SK.RG_CLEANER]: 18,
	[SK.RG_COMPULSION]: 19,
	[SK.RG_RAID]: 22,
	[SK.RG_STRIPWEAPON]: 24,
	[SK.RG_FLAGGRAFFITI]: 25,
	[SK.RG_INTIMIDATE]: 29,
	[SK.RG_GRAFFITI]: 32,
	[SK.RG_PLAGIARISM]: 36
};
SkillTreeView[JobId.ALCHEMIST] = {
	list: 2,
	beforeJob: JobId.MERCHANT,
	[SK.AM_LEARNINGPOTION]: 0,
	[SK.AM_SPHEREMINE]: 1,
	[SK.AM_AXEMASTERY]: 2,
	[SK.AM_CP_HELM]: 3,
	[SK.AM_BIOETHICS]: 4,
	[SK.AM_TWILIGHT1]: 6,
	[SK.AM_PHARMACY]: 7,
	[SK.AM_POTIONPITCHER]: 8,
	[SK.AM_CP_SHIELD]: 10,
	[SK.AM_REST]: 11,
	[SK.AM_BERSERKPITCHER]: 12,
	[SK.AM_TWILIGHT2]: 13,
	[SK.AM_DEMONSTRATION]: 15,
	[SK.AM_CP_ARMOR]: 17,
	[SK.AM_CALLHOMUN]: 18,
	[SK.AM_TWILIGHT3]: 20,
	[SK.AM_ACIDTERROR]: 22,
	[SK.AM_CP_WEAPON]: 24,
	[SK.AM_RESURRECTHOMUN]: 25,
	[SK.AM_CANNIBALIZE]: 29
};
SkillTreeView[JobId.BARD] = {
	list: 2,
	beforeJob: JobId.ARCHER,
	[SK.BD_ADAPTATION]: 0,
	[SK.BA_MUSICALLESSON]: 1,
	[SK.BA_DISSONANCE]: 3,
	[SK.BA_PANGVOICE]: 5,
	[SK.BD_ENCORE]: 7,
	[SK.BA_MUSICALSTRIKE]: 8,
	[SK.BA_WHISTLE]: 9,
	[SK.BA_ASSASSINCROSS]: 10,
	[SK.BA_POEMBRAGI]: 11,
	[SK.BA_APPLEIDUN]: 12,
	[SK.BA_FROSTJOKE]: 14,
	[SK.BD_LULLABY]: 16,
	[SK.BD_ROKISWEIL]: 17,
	[SK.BD_SIEGFRIED]: 18,
	[SK.BD_DRUMBATTLEFIELD]: 19,
	[SK.BD_INTOABYSS]: 23,
	[SK.BD_ETERNALCHAOS]: 24,
	[SK.BD_RICHMANKIM]: 25,
	[SK.BD_RINGNIBELUNGEN]: 26
};
SkillTreeView[JobId.DANCER] = {
	list: 2,
	beforeJob: JobId.ARCHER,
	[SK.BD_ADAPTATION]: 0,
	[SK.DC_DANCINGLESSON]: 1,
	[SK.DC_UGLYDANCE]: 3,
	[SK.DC_WINKCHARM]: 5,
	[SK.BD_ENCORE]: 7,
	[SK.DC_THROWARROW]: 8,
	[SK.DC_HUMMING]: 9,
	[SK.DC_DONTFORGETME]: 10,
	[SK.DC_FORTUNEKISS]: 11,
	[SK.DC_SERVICEFORYOU]: 12,
	[SK.DC_SCREAM]: 14,
	[SK.BD_LULLABY]: 16,
	[SK.BD_ROKISWEIL]: 17,
	[SK.BD_SIEGFRIED]: 18,
	[SK.BD_DRUMBATTLEFIELD]: 19,
	[SK.BD_INTOABYSS]: 23,
	[SK.BD_ETERNALCHAOS]: 24,
	[SK.BD_RICHMANKIM]: 25,
	[SK.BD_RINGNIBELUNGEN]: 26
};
SkillTreeView[JobId.SUPERNOVICE] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.SM_SWORD]: 1,
	[SK.SM_BASH]: 2,
	[SK.SM_PROVOKE]: 3,
	[SK.TF_DOUBLE]: 4,
	[SK.TF_STEAL]: 5,
	[SK.TF_POISON]: 6,
	[SK.SM_RECOVERY]: 8,
	[SK.SM_MAGNUM]: 9,
	[SK.SM_ENDURE]: 10,
	[SK.TF_MISS]: 11,
	[SK.TF_HIDING]: 12,
	[SK.TF_DETOXIFY]: 13,
	[SK.MG_STONECURSE]: 15,
	[SK.MG_COLDBOLT]: 16,
	[SK.MG_LIGHTNINGBOLT]: 17,
	[SK.MG_NAPALMBEAT]: 18,
	[SK.MG_FIREBOLT]: 19,
	[SK.MG_SIGHT]: 20,
	[SK.MG_SRECOVERY]: 22,
	[SK.MG_FROSTDIVER]: 23,
	[SK.MG_THUNDERSTORM]: 24,
	[SK.MG_SOULSTRIKE]: 25,
	[SK.MG_FIREBALL]: 26,
	[SK.AL_RUWACH]: 28,
	[SK.AL_HEAL]: 29,
	[SK.AL_HOLYWATER]: 30,
	[SK.AL_DP]: 31,
	[SK.MG_SAFETYWALL]: 32,
	[SK.MG_FIREWALL]: 33,
	[SK.AC_OWL]: 34,
	[SK.AL_TELEPORT]: 35,
	[SK.AL_CURE]: 36,
	[SK.AL_INCAGI]: 37,
	[SK.AL_BLESSING]: 38,
	[SK.AL_DEMONBANE]: 39,
	[SK.AL_ANGELUS]: 40,
	[SK.AC_VULTURE]: 41,
	[SK.AL_WARP]: 42,
	[SK.MC_INCCARRY]: 43,
	[SK.AL_DECAGI]: 44,
	[SK.MC_IDENTIFY]: 45,
	[SK.AL_CRUCIS]: 46,
	[SK.MC_MAMMONITE]: 47,
	[SK.AC_CONCENTRATION]: 48,
	[SK.AL_PNEUMA]: 49,
	[SK.MC_DISCOUNT]: 50,
	[SK.MC_OVERCHARGE]: 51,
	[SK.MC_PUSHCART]: 52,
	[SK.MC_VENDING]: 53
};
SkillTreeView[JobId.GUNSLINGER] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.GS_GLITTERING]: 1,
	[SK.GS_SINGLEACTION]: 3,
	[SK.GS_CRACKER]: 8,
	[SK.GS_MAGICALBULLET]: 9,
	[SK.GS_CHAINACTION]: 10,
	[SK.GS_TRACKING]: 11,
	[SK.GS_DUST]: 12,
	[SK.GS_SPREADATTACK]: 13,
	[SK.GS_INCREASING]: 15,
	[SK.GS_FLING]: 16,
	[SK.GS_RAPIDSHOWER]: 17,
	[SK.GS_PIERCINGSHOT]: 18,
	[SK.GS_FULLBUSTER]: 19,
	[SK.GS_GROUNDDRIFT]: 20,
	[SK.GS_MADNESSCANCEL]: 22,
	[SK.GS_TRIPLEACTION]: 23,
	[SK.GS_DESPERADO]: 24,
	[SK.GS_DISARM]: 25,
	[SK.GS_ADJUSTMENT]: 29,
	[SK.GS_GATLINGFEVER]: 31,
	[SK.GS_SNAKEEYE]: 34,
	[SK.GS_BULLSEYE]: 36
};
SkillTreeView[JobId.NINJA] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.NJ_TOBIDOUGU]: 1,
	[SK.NJ_TATAMIGAESHI]: 2,
	[SK.NJ_NINPOU]: 5,
	[SK.NJ_SYURIKEN]: 8,
	[SK.NJ_SHADOWJUMP]: 9,
	[SK.NJ_NEN]: 10,
	[SK.NJ_KOUENKA]: 11,
	[SK.NJ_HYOUSENSOU]: 12,
	[SK.NJ_HUUJIN]: 13,
	[SK.NJ_KUNAI]: 15,
	[SK.NJ_KASUMIKIRI]: 16,
	[SK.NJ_UTSUSEMI]: 17,
	[SK.NJ_KAENSIN]: 18,
	[SK.NJ_SUITON]: 19,
	[SK.NJ_RAIGEKISAI]: 20,
	[SK.NJ_HUUMA]: 22,
	[SK.NJ_KIRIKAGE]: 23,
	[SK.NJ_BAKUENRYU]: 25,
	[SK.NJ_HYOUSYOURAKU]: 26,
	[SK.NJ_KAMAITACHI]: 27,
	[SK.NJ_ZENYNAGE]: 29,
	[SK.NJ_BUNSINJYUTSU]: 30,
	[SK.NJ_ISSEN]: 31
};
SkillTreeView[JobId.PRIEST_H] = {
	list: 2,
	beforeJob: JobId.PRIEST,
	[SK.HP_ASSUMPTIO]: 10,
	[SK.HP_BASILICA]: 17,
	[SK.HP_MANARECHARGE]: 22,
	[SK.HP_MEDITATIO]: 19
};
SkillTreeView[JobId.BLACKSMITH_H] = {
	list: 2,
	beforeJob: JobId.BLACKSMITH,
	[SK.WS_CARTBOOST]: 21,
	[SK.WS_CARTTERMINATION]: 28,
	[SK.WS_MELTDOWN]: 22,
	[SK.WS_OVERTHRUSTMAX]: 25,
	[SK.WS_WEAPONREFINE]: 23
};
SkillTreeView[JobId.ASSASSIN_H] = {
	list: 2,
	beforeJob: JobId.ASSASSIN,
	[SK.ASC_BREAKER]: 18,
	[SK.ASC_CDP]: 12,
	[SK.ASC_EDP]: 19,
	[SK.ASC_KATAR]: 9,
	[SK.ASC_METEORASSAULT]: 25
};
SkillTreeView[JobId.TAEKWON] = {
	list: 1,
	beforeJob: JobId.NOVICE,
	[SK.TK_RUN]: 1,
	[SK.TK_STORMKICK]: 2,
	[SK.TK_DOWNKICK]: 3,
	[SK.TK_TURNKICK]: 4,
	[SK.TK_COUNTER]: 5,
	[SK.TK_JUMPKICK]: 6,
	[SK.TK_HIGHJUMP]: 8,
	[SK.TK_READYSTORM]: 9,
	[SK.TK_READYDOWN]: 10,
	[SK.TK_READYTURN]: 11,
	[SK.TK_READYCOUNTER]: 12,
	[SK.TK_DODGE]: 13,
	[SK.TK_HPTIME]: 16,
	[SK.TK_SPTIME]: 17,
	[SK.TK_POWER]: 18,
	[SK.TK_SEVENWIND]: 24,
	[SK.TK_MISSION]: 25
};
SkillTreeView[JobId.SAGE_H] = {
	list: 2,
	beforeJob: JobId.SAGE,
	[SK.PF_SPIDERWEB]: 14,
	[SK.PF_SOULCHANGE]: 21,
	[SK.PF_FOGWALL]: 25,
	[SK.PF_HPCONVERSION]: 28,
	[SK.PF_DOUBLECASTING]: 29,
	[SK.PF_MEMORIZE]: 30,
	[SK.PF_SOULBURN]: 31,
	[SK.PF_MINDBREAKER]: 32
};
SkillTreeView[JobId.ALCHEMIST_H] = {
	list: 2,
	beforeJob: JobId.ALCHEMIST,
	[SK.CR_SLIMPITCHER]: 9,
	[SK.CR_ACIDDEMONSTRATION]: 23,
	[SK.CR_FULLPROTECTION]: 31
};
SkillTreeView[JobId.DANCER_H] = {
	list: 2,
	beforeJob: JobId.DANCER,
	[SK.CG_ARROWVULCAN]: 29,
	[SK.CG_MOONLIT]: 30,
	[SK.CG_MARIONETTE]: 31,
	[SK.CG_HERMODE]: 32,
	[SK.CG_LONGINGFREEDOM]: 38,
	[SK.CG_SPECIALSINGER]: 38,
	[SK.CG_TAROTCARD]: 39
};
SkillTreeView[JobId.RUNE_KNIGHT] = {
	list: 3,
	beforeJob: JobId.KNIGHT_H,
	[SK.RK_RUNEMASTERY]: 1,
	[SK.RK_PHANTOMTHRUST]: 3,
	[SK.RK_DRAGONTRAINING]: 4,
	[SK.RK_ENCHANTBLADE]: 8,
	[SK.RK_HUNDREDSPEAR]: 10,
	[SK.RK_DRAGONHOWLING]: 11,
	[SK.RK_DRAGONBREATH]: 12,
	[SK.RK_DEATHBOUND]: 14,
	[SK.RK_SONICWAVE]: 15,
	[SK.RK_WINDCUTTER]: 16,
	[SK.RK_DRAGONBREATH_WATER]: 19,
	[SK.RK_IGNITIONBREAK]: 23,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.RANGER] = {
	list: 3,
	beforeJob: JobId.HUNTER_H,
	[SK.RA_AIMEDBOLT]: 0,
	[SK.RA_RESEARCHTRAP]: 1,
	[SK.RA_RANGERMAIN]: 3,
	[SK.RA_ELECTRICSHOCKER]: 4,
	[SK.RA_WUGMASTERY]: 5,
	[SK.RA_ARROWSTORM]: 7,
	[SK.RA_CLUSTERBOMB]: 8,
	[SK.RA_DETONATOR]: 9,
	[SK.RA_CAMOUFLAGE]: 10,
	[SK.RA_TOOTHOFWUG]: 12,
	[SK.RA_WUGRIDER]: 13,
	[SK.RA_FEARBREEZE]: 14,
	[SK.RA_MAGENTATRAP]: 15,
	[SK.RA_FIRINGTRAP]: 16,
	[SK.RA_ICEBOUNDTRAP]: 17,
	[SK.RA_SENSITIVEKEEN]: 18,
	[SK.RA_WUGSTRIKE]: 19,
	[SK.RA_WUGDASH]: 20,
	[SK.RA_UNLIMIT]: 21,
	[SK.RA_COBALTTRAP]: 22,
	[SK.RA_WUGBITE]: 26,
	[SK.RA_MAIZETRAP]: 29,
	[SK.RA_VERDURETRAP]: 36,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.MECHANIC] = {
	list: 3,
	beforeJob: JobId.BLACKSMITH_H,
	[SK.NC_MADOLICENCE]: 2,
	[SK.NC_TRAININGAXE]: 5,
	[SK.NC_RESEARCHFE]: 6,
	[SK.NC_REPAIR]: 7,
	[SK.NC_BOOSTKNUCKLE]: 8,
	[SK.NC_ACCELERATION]: 9,
	[SK.NC_MAINFRAME]: 10,
	[SK.NC_AXETORNADO]: 11,
	[SK.NC_AXEBOOMERANG]: 12,
	[SK.NC_SILVERSNIPER]: 13,
	[SK.NC_PILEBUNKER]: 14,
	[SK.NC_VULCANARM]: 15,
	[SK.NC_HOVERING]: 16,
	[SK.NC_SHAPESHIFT]: 17,
	[SK.NC_SELFDESTRUCTION]: 18,
	[SK.NC_POWERSWING]: 19,
	[SK.NC_MAGICDECOY]: 20,
	[SK.NC_FLAMELAUNCHER]: 21,
	[SK.NC_COLDSLOWER]: 22,
	[SK.NC_F_SIDESLIDE]: 23,
	[SK.NC_INFRAREDSCAN]: 24,
	[SK.NC_EMERGENCYCOOL]: 25,
	[SK.NC_DISJOINT]: 26,
	[SK.NC_MAGMA_ERUPTION]: 27,
	[SK.NC_ARMSCANNON]: 29,
	[SK.NC_B_SIDESLIDE]: 30,
	[SK.NC_ANALYZE]: 31,
	[SK.NC_MAGNETICFIELD]: 32,
	[SK.NC_NEUTRALBARRIER]: 39,
	[SK.NC_STEALTHFIELD]: 40,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.SHADOW_CHASER] = {
	list: 3,
	beforeJob: JobId.ROGUE_H,
	[SK.SC_REPRODUCE]: 0,
	[SK.SC_SHADOWFORM]: 1,
	[SK.SC_FATALMENACE]: 2,
	[SK.SC_BODYPAINT]: 3,
	[SK.SC_TRIANGLESHOT]: 4,
	[SK.SC_MANHOLE]: 5,
	[SK.SC_STRIPACCESSARY]: 6,
	[SK.SC_AUTOSHADOWSPELL]: 7,
	[SK.SC_ENERVATION]: 9,
	[SK.SC_GROOMY]: 10,
	[SK.SC_IGNORANCE]: 11,
	[SK.SC_CHAOSPANIC]: 12,
	[SK.SC_DIMENSIONDOOR]: 13,
	[SK.SC_DEADLYINFECT]: 15,
	[SK.SC_LAZINESS]: 16,
	[SK.SC_WEAKNESS]: 17,
	[SK.SC_ESCAPE]: 18,
	[SK.SC_FEINTBOMB]: 19,
	[SK.SC_BLOODYLUST]: 20,
	[SK.SC_UNLUCKY]: 24,
	[SK.SC_INVISIBILITY]: 29,
	[SK.SC_MAELSTROM]: 33,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.ROYAL_GUARD] = {
	list: 3,
	beforeJob: JobId.CRUSADER_H,
	[SK.LG_MOONSLASHER]: 0,
	[SK.LG_BANISHINGPOINT]: 1,
	[SK.LG_FORCEOFVANGUARD]: 2,
	[SK.LG_TRAMPLE]: 3,
	[SK.LG_PIETY]: 4,
	[SK.LG_REFLECTDAMAGE]: 5,
	[SK.LG_SHIELDPRESS]: 6,
	[SK.LG_EXEEDBREAK]: 7,
	[SK.LG_PINPOINTATTACK]: 8,
	[SK.LG_RAGEBURST]: 9,
	[SK.LG_PRESTIGE]: 10,
	[SK.LG_RAYOFGENESIS]: 11,
	[SK.LG_EARTHDRIVE]: 12,
	[SK.LG_KINGS_GRACE]: 13,
	[SK.LG_CANNONSPEAR]: 14,
	[SK.LG_OVERBRAND]: 15,
	[SK.LG_BANDING]: 16,
	[SK.LG_SHIELDSPELL]: 19,
	[SK.LG_HESPERUSLIT]: 24,
	[SK.LG_INSPIRATION]: 26,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.MINSTREL] = {
	list: 3,
	beforeJob: JobId.BARD_H,
	[SK.WM_SEVERE_RAINSTORM]: 0,
	[SK.WM_REVERBERATION]: 1,
	[SK.WM_LESSON]: 3,
	[SK.WM_DOMINION_IMPULSE]: 8,
	[SK.WM_SIRCLEOFNATURE]: 9,
	[SK.WM_LULLABY_DEEPSLEEP]: 10,
	[SK.WM_POEMOFNETHERWORLD]: 11,
	[SK.WM_FRIGG_SONG]: 12,
	[SK.WM_METALICSOUND]: 15,
	[SK.WM_DEADHILLHERE]: 16,
	[SK.WM_VOICEOFSIREN]: 18,
	[SK.WM_RANDOMIZESPELL]: 19,
	[SK.WM_GREAT_ECHO]: 22,
	[SK.MI_HARMONIZE]: 23,
	[SK.MI_RUSH_WINDMILL]: 24,
	[SK.MI_ECHOSONG]: 25,
	[SK.WM_GLOOMYDAY]: 26,
	[SK.WM_DANCE_WITH_WUG]: 30,
	[SK.WM_SONG_OF_MANA]: 31,
	[SK.WM_LERADS_DEW]: 32,
	[SK.WM_SATURDAY_NIGHT_FEVER]: 37,
	[SK.WM_MELODYOFSINK]: 38,
	[SK.WM_BEYOND_OF_WARCRY]: 39,
	[SK.ALL_FULL_THROTTLE]: 41,
	[SK.WM_SOUND_OF_DESTRUCTION]: 45,
	[SK.WM_UNLIMITED_HUMMING_VOICE]: 46
};
SkillTreeView[JobId.KNIGHT_H] = {
	list: 2,
	beforeJob: JobId.KNIGHT,
	[SK.LK_BERSERK]: 4,
	[SK.LK_TENSIONRELAX]: 5,
	[SK.LK_PARRYING]: 7,
	[SK.LK_AURABLADE]: 11,
	[SK.LK_CONCENTRATION]: 12,
	[SK.LK_HEADCRUSH]: 19,
	[SK.LK_SPIRALPIERCE]: 25,
	[SK.LK_JOINTBEAT]: 26
};
SkillTreeView[JobId.WIZARD_H] = {
	list: 2,
	beforeJob: JobId.WIZARD,
	[SK.HW_GANBANTEIN]: 7,
	[SK.HW_MAGICCRASHER]: 12,
	[SK.HW_SOULDRAIN]: 13,
	[SK.HW_NAPALMVULCAN]: 19,
	[SK.HW_MAGICPOWER]: 20,
	[SK.HW_GRAVITATION]: 24
};
SkillTreeView[JobId.HUNTER_H] = {
	list: 2,
	beforeJob: JobId.HUNTER,
	[SK.SN_FALCONASSAULT]: 28,
	[SK.SN_SHARPSHOOTING]: 5,
	[SK.SN_SIGHT]: 26,
	[SK.SN_WINDWALK]: 12
};
SkillTreeView[JobId.GENETIC] = {
	list: 3,
	beforeJob: JobId.ALCHEMIST_H,
	[SK.GN_CHANGEMATERIAL]: 0,
	[SK.GN_TRAINING_SWORD]: 1,
	[SK.GN_S_PHARMACY]: 2,
	[SK.GN_REMODELING_CART]: 5,
	[SK.GN_MIX_COOKING]: 8,
	[SK.GN_THORNS_TRAP]: 9,
	[SK.GN_BLOOD_SUCKER]: 10,
	[SK.GN_SPORE_EXPLOSION]: 11,
	[SK.GN_CART_TORNADO]: 12,
	[SK.GN_WALLOFTHORN]: 16,
	[SK.GN_HELLS_PLANT]: 17,
	[SK.GN_DEMONIC_FIRE]: 18,
	[SK.GN_CARTCANNON]: 19,
	[SK.GN_CRAZYWEED]: 23,
	[SK.GN_MANDRAGORA]: 24,
	[SK.GN_FIRE_EXPANSION]: 25,
	[SK.GN_CARTBOOST]: 26,
	[SK.GN_ILLUSIONDOPING]: 30,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.MONK_H] = {
	list: 2,
	beforeJob: JobId.MONK,
	[SK.CH_PALMSTRIKE]: 11,
	[SK.CH_SOULCOLLECT]: 21,
	[SK.CH_TIGERFIST]: 25,
	[SK.CH_CHAINCRUSH]: 32
};
SkillTreeView[JobId.ROGUE_H] = {
	list: 2,
	beforeJob: JobId.ROGUE,
	[SK.ST_CHASEWALK]: 8,
	[SK.ST_FULLSTRIP]: 30,
	[SK.ST_PRESERVE]: 38,
	[SK.ST_REJECTSWORD]: 31
};
SkillTreeView[JobId.BARD_H] = {
	list: 2,
	beforeJob: JobId.BARD,
	[SK.CG_ARROWVULCAN]: 29,
	[SK.CG_MOONLIT]: 30,
	[SK.CG_MARIONETTE]: 31,
	[SK.CG_HERMODE]: 32,
	[SK.CG_LONGINGFREEDOM]: 38,
	[SK.CG_SPECIALSINGER]: 38,
	[SK.CG_TAROTCARD]: 39
};
SkillTreeView[JobId.SURA] = {
	list: 3,
	beforeJob: JobId.MONK_H,
	[SK.SR_POWERVELOCITY]: 0,
	[SK.SR_RIDEINLIGHTNING]: 1,
	[SK.SR_DRAGONCOMBO]: 2,
	[SK.SR_SKYNETBLOW]: 3,
	[SK.SR_CURSEDCIRCLE]: 4,
	[SK.SR_GENTLETOUCH_QUIET]: 6,
	[SK.SR_ASSIMILATEPOWER]: 7,
	[SK.SR_RAISINGDRAGON]: 8,
	[SK.SR_FALLENEMPIRE]: 9,
	[SK.SR_EARTHSHAKER]: 10,
	[SK.SR_WINDMILL]: 11,
	[SK.SR_GENTLETOUCH_CURE]: 13,
	[SK.SR_HOWLINGOFLION]: 14,
	[SK.SR_TIGERCANNON]: 16,
	[SK.SR_RAMPAGEBLASTER]: 17,
	[SK.SR_LIGHTNINGWALK]: 18,
	[SK.SR_CRESCENTELBOW]: 19,
	[SK.SR_GENTLETOUCH_ENERGYGAIN]: 20,
	[SK.SR_KNUCKLEARROW]: 25,
	[SK.SR_GENTLETOUCH_REVITALIZE]: 26,
	[SK.SR_GENTLETOUCH_CHANGE]: 27,
	[SK.SR_FLASHCOMBO]: 23,
	[SK.SR_GATEOFHELL]: 31,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.WARLOCK] = {
	list: 3,
	beforeJob: JobId.WIZARD_H,
	[SK.WL_MARSHOFABYSS]: 0,
	[SK.WL_RADIUS]: 1,
	[SK.WL_RELEASE]: 2,
	[SK.WL_SUMMONFB]: 3,
	[SK.WL_SUMMONWB]: 4,
	[SK.WL_SUMMONBL]: 5,
	[SK.WL_SUMMONSTONE]: 6,
	[SK.WL_FREEZE_SP]: 7,
	[SK.WL_DRAINLIFE]: 8,
	[SK.WL_READING_SB]: 9,
	[SK.WL_CRIMSONROCK]: 10,
	[SK.WL_FROSTMISTY]: 11,
	[SK.WL_CHAINLIGHTNING]: 12,
	[SK.WL_SIENNAEXECRATE]: 13,
	[SK.WL_SOULEXPANSION]: 14,
	[SK.WL_STASIS]: 15,
	[SK.WL_HELLINFERNO]: 17,
	[SK.WL_JACKFROST]: 18,
	[SK.WL_EARTHSTRAIN]: 20,
	[SK.WL_WHITEIMPRISON]: 21,
	[SK.WL_COMET]: 25,
	[SK.WL_TELEKINESIS_INTENSE]: 28,
	[SK.WL_RECOGNIZEDSPELL]: 30,
	[SK.WL_TETRAVORTEX]: 32,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.ARCHBISHOP] = {
	list: 3,
	beforeJob: JobId.PRIEST_H,
	[SK.AB_JUDEX]: 0,
	[SK.AB_CHEAL]: 1,
	[SK.AB_CLEMENTIA]: 2,
	[SK.AB_PRAEFATIO]: 3,
	[SK.AB_DUPLELIGHT]: 4,
	[SK.AB_LAUDAAGNUS]: 5,
	[SK.AB_CANTO]: 6,
	[SK.AB_RENOVATIO]: 8,
	[SK.AB_ANCILLA]: 9,
	[SK.AB_ORATIO]: 10,
	[SK.AB_LAUDARAMUS]: 12,
	[SK.AB_ADORAMUS]: 14,
	[SK.AB_HIGHNESSHEAL]: 15,
	[SK.AB_CONVENIO]: 17,
	[SK.AB_EXPIATIO]: 18,
	[SK.AB_CLEARANCE]: 19,
	[SK.AB_OFFERTORIUM]: 22,
	[SK.AB_EPICLESIS]: 23,
	[SK.AB_SILENTIUM]: 26,
	[SK.AB_VITUPERATUM]: 30,
	[SK.AB_SECRAMENT]: 32,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.GUILLOTINE_CROSS] = {
	list: 3,
	beforeJob: JobId.ASSASSIN_H,
	[SK.GC_CROSSIMPACT]: 0,
	[SK.GC_CLOAKINGEXCEED]: 1,
	[SK.GC_ROLLINGCUTTER]: 2,
	[SK.GC_WEAPONBLOCKING]: 3,
	[SK.GC_VENOMIMPRESS]: 4,
	[SK.GC_RESEARCHNEWPOISON]: 5,
	[SK.GC_DARKILLUSION]: 7,
	[SK.GC_CROSSRIPPERSLASHER]: 9,
	[SK.GC_WEAPONCRUSH]: 10,
	[SK.GC_COUNTERSLASH]: 11,
	[SK.GC_CREATENEWPOISON]: 12,
	[SK.GC_ANTIDOTE]: 13,
	[SK.GC_DARKCROW]: 14,
	[SK.GC_PHANTOMMENACE]: 15,
	[SK.GC_POISONINGWEAPON]: 19,
	[SK.GC_HALLUCINATIONWALK]: 22,
	[SK.GC_VENOMPRESSURE]: 25,
	[SK.GC_POISONSMOKE]: 26,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.STAR] = {
	list: 2,
	beforeJob: JobId.TAEKWON,
	[SK.SG_FEEL]: 0,
	[SK.SG_HATE]: 2,
	[SK.SG_DEVIL]: 4,
	[SK.SG_KNOWLEDGE]: 5,
	[SK.SG_SUN_WARM]: 7,
	[SK.SG_SUN_COMFORT]: 8,
	[SK.SG_SUN_ANGER]: 9,
	[SK.SG_SUN_BLESS]: 10,
	[SK.SG_FRIEND]: 11,
	[SK.SG_FUSION]: 12,
	[SK.SG_MOON_WARM]: 14,
	[SK.SG_MOON_COMFORT]: 15,
	[SK.SG_MOON_ANGER]: 16,
	[SK.SG_MOON_BLESS]: 17,
	[SK.SG_STAR_WARM]: 21,
	[SK.SG_STAR_COMFORT]: 22,
	[SK.SG_STAR_ANGER]: 23,
	[SK.SG_STAR_BLESS]: 24
};
SkillTreeView[JobId.LINKER] = {
	list: 2,
	beforeJob: JobId.TAEKWON,
	[SK.SL_ALCHEMIST]: 0,
	[SK.SL_STAR]: 1,
	[SK.SL_ASSASIN]: 2,
	[SK.SL_CRUSADER]: 3,
	[SK.SL_BARDDANCER]: 4,
	[SK.SL_SUPERNOVICE]: 5,
	[SK.SL_BLACKSMITH]: 7,
	[SK.SL_SOULLINKER]: 8,
	[SK.SL_ROGUE]: 9,
	[SK.SL_KNIGHT]: 10,
	[SK.SL_HUNTER]: 11,
	[SK.SL_HIGH]: 12,
	[SK.SL_MONK]: 14,
	[SK.SL_KAUPE]: 16,
	[SK.SL_SKE]: 17,
	[SK.SL_SAGE]: 18,
	[SK.SL_KAINA]: 19,
	[SK.SL_PRIEST]: 21,
	[SK.SL_SKA]: 22,
	[SK.SL_WIZARD]: 25,
	[SK.SL_KAITE]: 26,
	[SK.SL_KAAHI]: 28,
	[SK.SL_KAIZEL]: 29,
	[SK.SL_SWOO]: 30,
	[SK.SL_STIN]: 31,
	[SK.SL_STUN]: 32,
	[SK.SL_SMA]: 33
};
SkillTreeView[JobId.SORCERER] = {
	list: 3,
	beforeJob: JobId.SAGE_H,
	[SK.SO_VACUUM_EXTREME]: 0,
	[SK.SO_STRIKING]: 1,
	[SK.SO_ELECTRICWALK]: 2,
	[SK.SO_EL_ANALYSIS]: 3,
	[SK.SO_CLOUD_KILL]: 4,
	[SK.SO_WARMER]: 5,
	[SK.SO_EARTHGRAVE]: 6,
	[SK.SO_SPELLFIST]: 7,
	[SK.SO_DIAMONDDUST]: 8,
	[SK.SO_VARETYR_SPEAR]: 9,
	[SK.SO_EL_CONTROL]: 10,
	[SK.SO_POISON_BUSTER]: 11,
	[SK.SO_FIREWALK]: 12,
	[SK.SO_ARRULLO]: 13,
	[SK.SO_PSYCHIC_WAVE]: 14,
	[SK.SO_SUMMON_AQUA]: 15,
	[SK.SO_SUMMON_VENTUS]: 16,
	[SK.SO_EL_SYMPATHY]: 17,
	[SK.SO_EL_ACTION]: 18,
	[SK.SO_SUMMON_AGNI]: 19,
	[SK.SO_SUMMON_TERA]: 20,
	[SK.SO_WATER_INSIGNIA]: 22,
	[SK.SO_WIND_INSIGNIA]: 23,
	[SK.SO_EL_CURE]: 24,
	[SK.SO_FIRE_INSIGNIA]: 26,
	[SK.SO_EARTH_INSIGNIA]: 27,
	[SK.SO_ELEMENTAL_SHIELD]: 31,
	[SK.ALL_FULL_THROTTLE]: 41
};
SkillTreeView[JobId.WANDERER] = {
	list: 3,
	beforeJob: JobId.DANCER_H,
	[SK.WM_SEVERE_RAINSTORM]: 0,
	[SK.WM_REVERBERATION]: 1,
	[SK.WM_LESSON]: 3,
	[SK.WM_DOMINION_IMPULSE]: 8,
	[SK.WM_SIRCLEOFNATURE]: 9,
	[SK.WM_LULLABY_DEEPSLEEP]: 10,
	[SK.WM_POEMOFNETHERWORLD]: 11,
	[SK.WM_FRIGG_SONG]: 12,
	[SK.WM_METALICSOUND]: 15,
	[SK.WM_DEADHILLHERE]: 16,
	[SK.WM_VOICEOFSIREN]: 18,
	[SK.WM_RANDOMIZESPELL]: 19,
	[SK.WM_GREAT_ECHO]: 22,
	[SK.WA_SWING_DANCE]: 23,
	[SK.WA_SYMPHONY_OF_LOVER]: 24,
	[SK.WA_MOONLIT_SERENADE]: 25,
	[SK.WM_GLOOMYDAY]: 26,
	[SK.WM_DANCE_WITH_WUG]: 30,
	[SK.WM_SONG_OF_MANA]: 31,
	[SK.WM_LERADS_DEW]: 32,
	[SK.WM_SATURDAY_NIGHT_FEVER]: 37,
	[SK.WM_MELODYOFSINK]: 38,
	[SK.WM_BEYOND_OF_WARCRY]: 39,
	[SK.ALL_FULL_THROTTLE]: 41,
	[SK.WM_SOUND_OF_DESTRUCTION]: 45,
	[SK.WM_UNLIMITED_HUMMING_VOICE]: 46
};
SkillTreeView[JobId.CRUSADER_H] = {
	list: 2,
	beforeJob: JobId.CRUSADER,
	[SK.PA_PRESSURE]: 17,
	[SK.PA_SHIELDCHAIN]: 25,
	[SK.PA_GOSPEL]: 30,
	[SK.PA_SACRIFICE]: 36
};
SkillTreeView[JobId.SUPERNOVICE2] = {
	list: 2,
	beforeJob: JobId.SUPERNOVICE,
	[SK.MO_IRONHAND]: 0,
	[SK.CR_TRUST]: 1,
	[SK.CR_HOLYCROSS]: 2,
	[SK.PR_IMPOSITIO]: 3,
	[SK.RG_TUNNELDRIVE]: 4,
	[SK.RG_SNATCHER]: 5,
	[SK.AS_ENCHANTPOISON]: 6,
	[SK.MO_CALLSPIRITS]: 7,
	[SK.CR_AUTOGUARD]: 8,
	[SK.PR_SANCTUARY]: 9,
	[SK.PR_STRECOVERY]: 10,
	[SK.RG_BACKSTAP]: 11,
	[SK.RG_STEALCOIN]: 12,
	[SK.AS_POISONREACT]: 13,
	[SK.MO_ABSORBSPIRITS]: 14,
	[SK.CR_SHIELDCHARGE]: 15,
	[SK.PR_GLORIA]: 16,
	[SK.PR_ASPERSIO]: 17,
	[SK.RG_RAID]: 18,
	[SK.HW_MAGICCRASHER]: 19,
	[SK.AS_VENOMDUST]: 20,
	[SK.MO_EXPLOSIONSPIRITS]: 21,
	[SK.CR_SHIELDBOOMERANG]: 22,
	[SK.PR_MAGNIFICAT]: 23,
	[SK.AS_SPLASHER]: 27,
	[SK.CH_SOULCOLLECT]: 28,
	[SK.WZ_WATERBALL]: 29,
	[SK.WZ_JUPITEL]: 30,
	[SK.WZ_EARTHSPIKE]: 31,
	[SK.WZ_SIGHTRASHER]: 32,
	[SK.HT_SKIDTRAP]: 33,
	[SK.AM_AXEMASTERY]: 34,
	[SK.WZ_ICEWALL]: 36,
	[SK.WZ_VERMILION]: 37,
	[SK.WZ_HEAVENDRIVE]: 38,
	[SK.WZ_FIREPILLAR]: 39,
	[SK.HT_LANDMINE]: 40,
	[SK.BS_HILTBINDING]: 41,
	[SK.WZ_FROSTNOVA]: 43,
	[SK.WZ_STORMGUST]: 44,
	[SK.WZ_QUAGMIRE]: 45,
	[SK.WZ_METEOR]: 46,
	[SK.HT_BEASTBANE]: 47,
	[SK.BS_WEAPONRESEARCH]: 48,
	[SK.WZ_ESTIMATION]: 54,
	[SK.BS_REPAIRWEAPON]: 55,
	[SK.NV_BREAKTHROUGH]: 56,
	[SK.NV_HELPANGEL]: 57,
	[SK.NV_TRANSCENDENCE]: 58
};
SkillTreeView[JobId.KAGEROU] = {
	list: 2,
	beforeJob: JobId.NINJA,
	[SK.KO_YAMIKUMO]: 0,
	[SK.KO_ZANZOU]: 1,
	[SK.KO_GENWAKU]: 2,
	[SK.KO_KYOUGAKU]: 3,
	[SK.KO_JYUSATSU]: 4,
	[SK.KO_JYUMONJIKIRI]: 7,
	[SK.KG_KAGEHUMI]: 8,
	[SK.KO_KAHU_ENTEN]: 10,
	[SK.KO_HYOUHU_HUBUKI]: 11,
	[SK.KO_KAZEHU_SEIRAN]: 12,
	[SK.KO_DOHU_KOUKAI]: 13,
	[SK.KO_SETSUDAN]: 14,
	[SK.KG_KYOMU]: 15,
	[SK.KO_KAIHOU]: 17,
	[SK.KO_BAKURETSU]: 21,
	[SK.KG_KAGEMUSYA]: 22,
	[SK.KO_ZENKAI]: 24,
	[SK.KO_IZAYOI]: 25,
	[SK.KO_MEIKYOUSISUI]: 26,
	[SK.KO_HAPPOKUNAI]: 28,
	[SK.KO_MAKIBISHI]: 30,
	[SK.KO_RIGHT]: 33,
	[SK.KO_LEFT]: 34,
	[SK.KO_HUUMARANKA]: 36,
	[SK.KO_MUCHANAGE]: 37
};
SkillTreeView[JobId.OBORO] = {
	list: 2,
	beforeJob: JobId.NINJA,
	[SK.KO_YAMIKUMO]: 0,
	[SK.KO_ZANZOU]: 1,
	[SK.KO_GENWAKU]: 2,
	[SK.KO_KYOUGAKU]: 3,
	[SK.KO_JYUSATSU]: 4,
	[SK.KO_JYUMONJIKIRI]: 7,
	[SK.OB_ZANGETSU]: 9,
	[SK.KO_KAHU_ENTEN]: 10,
	[SK.KO_HYOUHU_HUBUKI]: 11,
	[SK.KO_KAZEHU_SEIRAN]: 12,
	[SK.KO_DOHU_KOUKAI]: 13,
	[SK.KO_SETSUDAN]: 14,
	[SK.OB_AKAITSUKI]: 16,
	[SK.KO_KAIHOU]: 17,
	[SK.KO_BAKURETSU]: 21,
	[SK.OB_OBOROGENSOU]: 23,
	[SK.KO_ZENKAI]: 24,
	[SK.KO_IZAYOI]: 25,
	[SK.KO_MEIKYOUSISUI]: 26,
	[SK.KO_HAPPOKUNAI]: 28,
	[SK.KO_MAKIBISHI]: 30,
	[SK.KO_RIGHT]: 33,
	[SK.KO_LEFT]: 34,
	[SK.KO_HUUMARANKA]: 36,
	[SK.KO_MUCHANAGE]: 37
};
SkillTreeView[JobId.REBELLION] = {
	list: 2,
	beforeJob: JobId.GUNSLINGER,
	[SK.RL_RICHS_COIN]: 0,
	[SK.RL_FLICKER]: 1,
	[SK.RL_S_STORM]: 2,
	[SK.RL_MASS_SPIRAL]: 3,
	[SK.RL_FALLEN_ANGEL]: 4,
	[SK.RL_H_MINE]: 5,
	[SK.RL_FIRE_RAIN]: 6,
	[SK.RL_P_ALTER]: 7,
	[SK.RL_B_TRAP]: 8,
	[SK.RL_BANISHING_BUSTER]: 9,
	[SK.RL_AM_BLAST]: 10,
	[SK.RL_FIREDANCE]: 11,
	[SK.RL_D_TAIL]: 12,
	[SK.RL_R_TRIP]: 13,
	[SK.RL_HEAT_BARREL]: 14,
	[SK.RL_SLUGSHOT]: 16,
	[SK.RL_HAMMER_OF_GOD]: 17,
	[SK.RL_C_MARKER]: 30,
	[SK.RL_QD_SHOT]: 31,
	[SK.RL_E_CHAIN]: 32
};
SkillTreeView[JobId.DO_SUMMONER] = {
	list: 1,
	beforeJob: null,
	[SK.SU_BASIC_SKILL]: 0,
	[SK.SU_BITE]: 1,
	[SK.SU_HIDE]: 2,
	[SK.SU_SCRATCH]: 3,
	[SK.SU_STOOP]: 4,
	[SK.SU_LOPE]: 5,
	[SK.SU_SPRITEMABLE]: 6,
	[SK.SU_FRESHSHRIMP]: 8,
	[SK.SU_SV_STEMSPEAR]: 9,
	[SK.SU_PICKYPECK]: 10,
	[SK.SU_SOULATTACK]: 13,
	[SK.SU_BUNCHOFSHRIMP]: 15,
	[SK.SU_SV_ROOTTWIST]: 16,
	[SK.SU_ARCLOUSEDASH]: 17,
	[SK.SU_TUNABELLY]: 22,
	[SK.SU_CN_METEOR]: 23,
	[SK.SU_SCAROFTAROU]: 24,
	[SK.SU_TUNAPARTY]: 29,
	[SK.SU_CN_POWDERING]: 30,
	[SK.SU_LUNATICCARROTBEAT]: 31,
	[SK.SU_POWEROFSEA]: 36,
	[SK.SU_POWEROFLAND]: 37,
	[SK.SU_POWEROFLIFE]: 38,
	[SK.SU_GROOMING]: 43,
	[SK.SU_CHATTERING]: 44,
	[SK.SU_HISS]: 45,
	[SK.SU_PURRING]: 50,
	[SK.SU_MEOWMEOW]: 51,
	[SK.SU_POWEROFFLOCK]: 52,
	[SK.SU_SHRIMPARTY]: 57,
	[SK.SU_NYANGGRASS]: 58,
	[SK.SU_SVG_SPIRIT]: 59,
	[SK.SU_SPIRITOFSEA]: 64,
	[SK.SU_SPIRITOFLAND]: 65,
	[SK.SU_SPIRITOFLIFE]: 66
};
SkillTreeView[JobId.STAR_EMPEROR] = {
	list: 2,
	beforeJob: JobId.STAR,
	[SK.SJ_DOCUMENT]: 1,
	[SK.SJ_PURIFY]: 4,
	[SK.SJ_SUNSTANCE]: 7,
	[SK.SJ_LUNARSTANCE]: 8,
	[SK.SJ_STARSTANCE]: 9,
	[SK.SJ_UNIVERSESTANCE]: 11,
	[SK.SJ_PROMINENCEKICK]: 14,
	[SK.SJ_NEWMOONKICK]: 15,
	[SK.SJ_FLASHKICK]: 16,
	[SK.SJ_NOVAEXPLOSING]: 18,
	[SK.SJ_GRAVITYCONTROL]: 19,
	[SK.SJ_SOLARBURST]: 21,
	[SK.SJ_FULLMOONKICK]: 22,
	[SK.SJ_FALLINGSTAR]: 23,
	[SK.SJ_STAREMPEROR]: 25,
	[SK.SJ_LIGHTOFSUN]: 28,
	[SK.SJ_LIGHTOFMOON]: 29,
	[SK.SJ_LIGHTOFSTAR]: 30,
	[SK.SJ_BOOKOFCREATINGSTAR]: 32,
	[SK.SJ_BOOKOFDIMENSION]: 33
};
SkillTreeView[JobId.SOUL_REAPER] = {
	list: 2,
	beforeJob: JobId.LINKER,
	[SK.SP_SOULCOLLECT]: 3,
	[SK.SP_SOULREAPER]: 7,
	[SK.SP_SOULCURSE]: 9,
	[SK.SP_SOULENERGY]: 10,
	[SK.SP_KAUTE]: 12,
	[SK.SP_SHA]: 14,
	[SK.SP_CURSEEXPLOSION]: 16,
	[SK.SP_SOULUNITY]: 17,
	[SK.SP_SOULREVOLVE]: 19,
	[SK.SP_SPA]: 21,
	[SK.SP_SOULSHADOW]: 24,
	[SK.SP_SOULFAIRY]: 25,
	[SK.SP_SOULFALCON]: 26,
	[SK.SP_SOULGOLEM]: 27,
	[SK.SP_SWHOO]: 28,
	[SK.SP_SOULDIVISION]: 29,
	[SK.SP_SOULEXPLOSION]: 32
};
SkillTreeView[JobId.DRAGON_KNIGHT] = {
	list: 4,
	beforeJob: JobId.RUNE_KNIGHT,
	[SK.DK_SERVANTWEAPON]: 1,
	[SK.DK_TWOHANDDEF]: 3,
	[SK.DK_CHARGINGPIERCE]: 5,
	[SK.DK_SERVANT_W_SIGN]: 8,
	[SK.DK_HACKANDSLASHER]: 11,
	[SK.DK_DRAGONIC_BREATH]: 13,
	[SK.DK_SERVANT_W_PHANTOM]: 15,
	[SK.DK_STORMSLASH]: 17,
	[SK.DK_MADNESS_CRUSHER]: 19,
	[SK.DK_SERVANT_W_DEMOL]: 22,
	[SK.DK_VIGOR]: 24,
	[SK.DK_DRAGONIC_AURA]: 26
};
SkillTreeView[JobId.ARCH_MAGE] = {
	list: 4,
	beforeJob: JobId.WARLOCK,
	[SK.AG_TWOHANDSTAFF]: 0,
	[SK.AG_FLORAL_FLARE_ROAD]: 3,
	[SK.AG_RAIN_OF_CRYSTAL]: 4,
	[SK.AG_TORNADO_STORM]: 5,
	[SK.AG_STRANTUM_TREMOR]: 6,
	[SK.AG_SOUL_VC_STRIKE]: 7,
	[SK.AG_CLIMAX]: 9,
	[SK.AG_CRIMSON_ARROW]: 10,
	[SK.AG_FROZEN_SLASH]: 11,
	[SK.AG_STORM_CANNON]: 12,
	[SK.AG_ROCK_DOWN]: 13,
	[SK.AG_MYSTERY_ILLUSION]: 14,
	[SK.AG_DEADLY_PROJECTION]: 15,
	[SK.AG_ALL_BLOOM]: 17,
	[SK.AG_CRYSTAL_IMPACT]: 18,
	[SK.AG_DESTRUCTIVE_HURRICANE]: 19,
	[SK.AG_VIOLENT_QUAKE]: 20,
	[SK.AG_ASTRAL_STRIKE]: 22
};
SkillTreeView[JobId.INQUISITOR] = {
	list: 4,
	beforeJob: JobId.SURA,
	[SK.IQ_WILL_OF_FAITH]: 1,
	[SK.IQ_SINCERE_FAITH]: 7,
	[SK.IQ_FIRM_FAITH]: 8,
	[SK.IQ_POWERFUL_FAITH]: 9,
	[SK.IQ_FIRST_BRAND]: 10,
	[SK.IQ_OLEUM_SANCTUM]: 13,
	[SK.IQ_FIRST_FAITH_POWER]: 17,
	[SK.IQ_JUDGE]: 18,
	[SK.IQ_THIRD_EXOR_FLAME]: 19,
	[SK.IQ_EXPOSION_BLASTER]: 20,
	[SK.IQ_SECOND_FAITH]: 24,
	[SK.IQ_SECOND_JUDGEMENT]: 25,
	[SK.IQ_SECOND_FLAME]: 26,
	[SK.IQ_MASSIVE_F_BLASTER]: 27,
	[SK.IQ_THIRD_PUNISH]: 31,
	[SK.IQ_THIRD_CONSECRATION]: 32,
	[SK.IQ_THIRD_FLAME_BOMB]: 33
};
SkillTreeView[JobId.IMPERIAL_GUARD] = {
	list: 4,
	beforeJob: JobId.ROYAL_GUARD,
	[SK.IG_SPEAR_SWORD_M]: 1,
	[SK.IG_SHIELD_MASTERY]: 4,
	[SK.IG_ATTACK_STANCE]: 8,
	[SK.IG_GUARD_STANCE]: 11,
	[SK.IG_CROSS_RAIN]: 12,
	[SK.IG_OVERSLASH]: 15,
	[SK.IG_SHIELD_SHOOTING]: 16,
	[SK.IG_REBOUND_SHIELD]: 17,
	[SK.IG_GUARDIAN_SHIELD]: 18,
	[SK.IG_HOLY_SHIELD]: 19,
	[SK.IG_GRAND_JUDGEMENT]: 22,
	[SK.IG_ULTIMATE_SACRIFICE]: 25,
	[SK.IG_JUDGEMENT_CROSS]: 26
};
SkillTreeView[JobId.SHADOW_CROSS] = {
	list: 4,
	beforeJob: JobId.GUILLOTINE_CROSS,
	[SK.SHC_SHADOW_SENSE]: 0,
	[SK.SHC_DANCING_KNIFE]: 8,
	[SK.SHC_SAVAGE_IMPACT]: 10,
	[SK.SHC_ENCHANTING_SHADOW]: 12,
	[SK.SHC_ETERNAL_SLASH]: 15,
	[SK.SHC_IMPACT_CRATER]: 17,
	[SK.SHC_POTENT_VENOM]: 19,
	[SK.SHC_SHADOW_STAB]: 22,
	[SK.SHC_SHADOW_EXCEED]: 25,
	[SK.SHC_FATAL_SHADOW_CROW]: 30
};
SkillTreeView[JobId.CARDINAL] = {
	list: 4,
	beforeJob: JobId.ARCHBISHOP,
	[SK.CD_DILECTIO_HEAL]: 1,
	[SK.CD_FIDUS_ANIMUS]: 4,
	[SK.CD_MACE_BOOK_M]: 6,
	[SK.CD_MEDIALE_VOTUM]: 8,
	[SK.CD_BENEDICTUM]: 9,
	[SK.CD_RELIGIO]: 10,
	[SK.CD_FRAMEN]: 11,
	[SK.CD_PETITIO]: 13,
	[SK.CD_REPARATIO]: 15,
	[SK.CD_ARBITRIUM]: 18,
	[SK.CD_EFFLIGO]: 20,
	[SK.CD_PRESENS_ACIES]: 21,
	[SK.CD_ARGUTUS_TELUM]: 22,
	[SK.CD_ARGUTUS_VITA]: 23,
	[SK.CD_PNEUMATICUS_PROCELLA]: 25,
	[SK.CD_COMPETENTIA]: 29
};
SkillTreeView[JobId.BIOLO] = {
	list: 4,
	beforeJob: JobId.GENETIC,
	[SK.BO_BIONIC_PHARMACY]: 0,
	[SK.BO_BIONICS_M]: 2,
	[SK.BO_THE_WHOLE_PROTECTION]: 7,
	[SK.BO_EXPLOSIVE_POWDER]: 8,
	[SK.BO_ACIDIFIED_ZONE_GROUND]: 9,
	[SK.BO_ACIDIFIED_ZONE_WIND]: 10,
	[SK.BO_CREEPER]: 12,
	[SK.BO_ADVANCE_PROTECTION]: 14,
	[SK.BO_MAYHEMIC_THORNS]: 15,
	[SK.BO_ACIDIFIED_ZONE_FIRE]: 16,
	[SK.BO_ACIDIFIED_ZONE_WATER]: 17,
	[SK.BO_WOODENWARRIOR]: 18,
	[SK.BO_WOODEN_FAIRY]: 19,
	[SK.BO_RESEARCHREPORT]: 24,
	[SK.BO_HELLTREE]: 25
};
SkillTreeView[JobId.WINDHAWK] = {
	list: 4,
	beforeJob: JobId.RANGER,
	[SK.WH_CRESCIVE_BOLT]: 0,
	[SK.WH_NATUREFRIENDLY]: 1,
	[SK.WH_ADVANCED_TRAP]: 3,
	[SK.WH_HAWK_M]: 5,
	[SK.WH_GALESTORM]: 7,
	[SK.WH_WIND_SIGN]: 8,
	[SK.WH_SOLIDTRAP]: 10,
	[SK.WH_DEEPBLINDTRAP]: 11,
	[SK.WH_HAWKRUSH]: 12,
	[SK.WH_FLAMETRAP]: 17,
	[SK.WH_SWIFTTRAP]: 18,
	[SK.WH_CALAMITYGALE]: 21,
	[SK.WH_HAWKBOOMERANG]: 26
};
SkillTreeView[JobId.TROUBADOUR] = {
	list: 4,
	beforeJob: JobId.MINSTREL,
	[SK.TR_RHYTHMSHOOTING]: 1,
	[SK.TR_STAGE_MANNER]: 3,
	[SK.TR_SOUNDBLEND]: 7,
	[SK.TR_RETROSPECTION]: 9,
	[SK.TR_GEF_NOCTURN]: 10,
	[SK.TR_AIN_RHAPSODY]: 11,
	[SK.TR_METALIC_FURY]: 14,
	[SK.TR_ROSEBLOSSOM]: 15,
	[SK.TR_JAWAII_SERENADE]: 17,
	[SK.TR_MUSICAL_INTERLUDE]: 18,
	[SK.TR_PRON_MARCH]: 19,
	[SK.TR_MYSTIC_SYMPHONY]: 22,
	[SK.TR_ROKI_CAPRICCIO]: 24,
	[SK.TR_NIPELHEIM_REQUIEM]: 25,
	[SK.TR_KVASIR_SONATA]: 31
};
SkillTreeView[JobId.TROUVERE] = {
	list: 4,
	beforeJob: JobId.WANDERER,
	[SK.TR_RHYTHMSHOOTING]: 1,
	[SK.TR_STAGE_MANNER]: 3,
	[SK.TR_SOUNDBLEND]: 7,
	[SK.TR_RETROSPECTION]: 9,
	[SK.TR_GEF_NOCTURN]: 10,
	[SK.TR_AIN_RHAPSODY]: 11,
	[SK.TR_METALIC_FURY]: 14,
	[SK.TR_ROSEBLOSSOM]: 15,
	[SK.TR_JAWAII_SERENADE]: 17,
	[SK.TR_MUSICAL_INTERLUDE]: 18,
	[SK.TR_PRON_MARCH]: 19,
	[SK.TR_MYSTIC_SYMPHONY]: 22,
	[SK.TR_ROKI_CAPRICCIO]: 24,
	[SK.TR_NIPELHEIM_REQUIEM]: 25,
	[SK.TR_KVASIR_SONATA]: 31
};
SkillTreeView[JobId.ABYSS_CHASER] = {
	list: 4,
	beforeJob: JobId.SHADOW_CHASER,
	[SK.ABC_DAGGER_AND_BOW_M]: 1,
	[SK.ABC_MAGIC_SWORD_M]: 5,
	[SK.ABC_ABYSS_DAGGER]: 8,
	[SK.ABC_CHAIN_REACTION_SHOT]: 10,
	[SK.ABC_FROM_THE_ABYSS]: 12,
	[SK.ABC_STRIP_SHADOW]: 14,
	[SK.ABC_UNLUCKY_RUSH]: 15,
	[SK.ABC_DEFT_STAB]: 16,
	[SK.ABC_FRENZY_SHOT]: 17,
	[SK.ABC_ABYSS_SQUARE]: 19,
	[SK.ABC_ABYSS_SLAYER]: 23,
	[SK.ABC_ABYSS_STRIKE]: 26
};
SkillTreeView[JobId.MEISTER] = {
	list: 4,
	beforeJob: JobId.MECHANIC,
	[SK.MT_TWOAXEDEF]: 1,
	[SK.MT_M_MACHINE]: 3,
	[SK.MT_AXE_STOMP]: 8,
	[SK.MT_A_MACHINE]: 9,
	[SK.MT_D_MACHINE]: 10,
	[SK.MT_ABR_M]: 11,
	[SK.MT_SPARK_BLASTER]: 13,
	[SK.MT_MIGHTY_SMASH]: 14,
	[SK.MT_RUSH_QUAKE]: 15,
	[SK.MT_SUMMON_ABR_BATTLE_WARIOR]: 18,
	[SK.MT_SUMMON_ABR_DUAL_CANNON]: 19,
	[SK.MT_TRIPLE_LASER]: 20,
	[SK.MT_SUMMON_ABR_MOTHER_NET]: 26,
	[SK.MT_SUMMON_ABR_INFINITY]: 33
};
SkillTreeView[JobId.ELEMENTAL_MASTER] = {
	list: 4,
	beforeJob: JobId.SORCERER,
	[SK.EM_MAGIC_BOOK_M]: 2,
	[SK.EM_ELEMENTAL_SPIRIT_M]: 5,
	[SK.EM_DIAMOND_STORM]: 7,
	[SK.EM_CONFLAGRATION]: 8,
	[SK.EM_LIGHTNING_LAND]: 9,
	[SK.EM_SPELL_ENCHANTING]: 10,
	[SK.EM_ELEMENTAL_VEIL]: 12,
	[SK.EM_TERRA_DRIVE]: 15,
	[SK.EM_VENOM_SWAMP]: 16,
	[SK.EM_ACTIVITY_BURN]: 17,
	[SK.EM_SUMMON_ELEMENTAL_DILUVIO]: 18,
	[SK.EM_SUMMON_ELEMENTAL_ARDOR]: 19,
	[SK.EM_SUMMON_ELEMENTAL_PROCELLA]: 20,
	[SK.EM_INCREASING_ACTIVITY]: 24,
	[SK.EM_SUMMON_ELEMENTAL_SERPENS]: 26,
	[SK.EM_SUMMON_ELEMENTAL_TERREMOTUS]: 27,
	[SK.EM_ELEMENTAL_BUSTER]: 33
};
SkillTreeView[JobId.SKY_EMPEROR] = {
	list: 3,
	beforeJob: JobId.STAR_EMPEROR,
	[SK.SKE_WAR_BOOK_MASTERY]: 1,
	[SK.SKE_SKY_MASTERY]: 3,
	[SK.SKE_RISING_SUN]: 8,
	[SK.SKE_RISING_MOON]: 10,
	[SK.SKE_TWINKLING_GALAXY]: 12,
	[SK.SKE_NOON_BLAST]: 15,
	[SK.SKE_MIDNIGHT_KICK]: 17,
	[SK.SKE_STAR_BURST]: 19,
	[SK.SKE_SUNSET_BLAST]: 22,
	[SK.SKE_DAWN_BREAK]: 24,
	[SK.SKE_STAR_CANNON]: 26,
	[SK.SKE_ALL_IN_THE_SKY]: 30,
	[SK.SKE_ENCHANTING_SKY]: 32
};
SkillTreeView[JobId.SOUL_ASCETIC] = {
	list: 3,
	beforeJob: JobId.SOUL_REAPER,
	[SK.SOA_SOUL_MASTERY]: 2,
	[SK.SOA_TALISMAN_MASTERY]: 4,
	[SK.SOA_SOUL_GATHERING]: 8,
	[SK.SOA_TALISMAN_OF_PROTECTION]: 11,
	[SK.SOA_TALISMAN_OF_WARRIOR]: 12,
	[SK.SOA_TALISMAN_OF_MAGICIAN]: 13,
	[SK.SOA_EXORCISM_OF_MALICIOUS_SOUL]: 14,
	[SK.SOA_TALISMAN_OF_SOUL_STEALING]: 16,
	[SK.SOA_TOTEM_OF_TUTELARY]: 17,
	[SK.SOA_TALISMAN_OF_FIVE_ELEMENTS]: 19,
	[SK.SOA_TALISMAN_OF_BLUE_DRAGON]: 22,
	[SK.SOA_TALISMAN_OF_WHITE_TIGER]: 23,
	[SK.SOA_TALISMAN_OF_RED_PHOENIX]: 24,
	[SK.SOA_TALISMAN_OF_BLACK_TORTOISE]: 25,
	[SK.SOA_TALISMAN_OF_FOUR_BEARING_GOD]: 31,
	[SK.SOA_CIRCLE_OF_DIRECTIONS_AND_ELEMENTALS]: 38,
	[SK.SOA_SOUL_OF_HEAVEN_AND_EARTH]: 40
};
SkillTreeView[JobId.NIGHT_WATCH] = {
	list: 3,
	beforeJob: JobId.REBELLION,
	[SK.NW_P_F_I]: 2,
	[SK.NW_GRENADE_MASTERY]: 5,
	[SK.NW_INTENSIVE_AIM]: 9,
	[SK.NW_HIDDEN_CARD]: 10,
	[SK.NW_BASIC_GRENADE]: 12,
	[SK.NW_GRENADE_FRAGMENT]: 13,
	[SK.NW_THE_VIGILANTE_AT_NIGHT]: 14,
	[SK.NW_ONLY_ONE_BULLET]: 15,
	[SK.NW_SPIRAL_SHOOTING]: 16,
	[SK.NW_MAGAZINE_FOR_ONE]: 17,
	[SK.NW_WILD_FIRE]: 18,
	[SK.NW_HASTY_FIRE_IN_THE_HOLE]: 19,
	[SK.NW_GRENADES_DROPPING]: 26,
	[SK.NW_AUTO_FIRING_LAUNCHER]: 27,
	[SK.NW_MISSION_BOMBARD]: 33
};
SkillTreeView[JobId.HYPER_NOVICE] = {
	list: 3,
	beforeJob: JobId.SUPERNOVICE2,
	[SK.HN_SELFSTUDY_TATICS]: 0,
	[SK.HN_SELFSTUDY_SOCERY]: 3,
	[SK.HN_DOUBLEBOWLINGBASH]: 7,
	[SK.HN_SHIELD_CHAIN_RUSH]: 8,
	[SK.HN_METEOR_STORM_BUSTER]: 10,
	[SK.HN_JUPITEL_THUNDER_STORM]: 11,
	[SK.HN_JACK_FROST_NOVA]: 12,
	[SK.HN_HELLS_DRIVE]: 13,
	[SK.HN_MEGA_SONIC_BLOW]: 14,
	[SK.HN_SPIRAL_PIERCE_MAX]: 15,
	[SK.HN_GROUND_GRAVITATION]: 17,
	[SK.HN_NAPALM_VULCAN_STRIKE]: 18,
	[SK.HN_BREAKINGLIMIT]: 21,
	[SK.HN_RULEBREAK]: 24
};
SkillTreeView[JobId.SPIRIT_HANDLER] = {
	list: 2,
	beforeJob: JobId.DO_SUMMONER,
	[SK.SH_MYSTICAL_CREATURE_MASTERY]: 3,
	[SK.SH_CHUL_HO_SONIC_CLAW]: 8,
	[SK.SH_KI_SUL_WATER_SPRAYING]: 10,
	[SK.SH_COLORS_OF_HYUN_ROK]: 12,
	[SK.SH_HOWLING_OF_CHUL_HO]: 15,
	[SK.SH_MARINE_FESTIVAL_OF_KI_SUL]: 17,
	[SK.SH_SANDY_FESTIVAL_OF_KI_SUL]: 18,
	[SK.SH_HYUN_ROKS_BREEZE]: 19,
	[SK.SH_HOGOGONG_STRIKE]: 22,
	[SK.SH_KI_SUL_RAMPAGE]: 24,
	[SK.SH_HYUN_ROK_CANNON]: 26,
	[SK.SH_COMMUNE_WITH_CHUL_HO]: 29,
	[SK.SH_COMMUNE_WITH_KI_SUL]: 31,
	[SK.SH_COMMUNE_WITH_HYUN_ROK]: 33,
	[SK.SH_TEMPORARY_COMMUNION]: 37,
	[SK.SH_BLESSING_OF_MYSTICAL_CREATURES]: 39
};
SkillTreeView[JobId.SHIRANUI] = {
	list: 3,
	beforeJob: JobId.OBORO,
	[SK.SS_SHINKIROU]: 0,
	[SK.SS_SEKIENHOU]: 6,
	[SK.SS_SHIMIRU]: 7,
	[SK.SS_KUNAIWAIKYOKU]: 9,
	[SK.SS_KAGEGARI]: 11,
	[SK.SS_REIKETSUHOU]: 13,
	[SK.SS_TOKEDASU]: 14,
	[SK.SS_KUNAIKAITEN]: 16,
	[SK.SS_FUUMASHOUAKU]: 17,
	[SK.SS_KAGENOMAI]: 18,
	[SK.SS_RAIDENPOU]: 20,
	[SK.SS_AKUMUKESU]: 21,
	[SK.SS_KUNAIKUSSETSU]: 23,
	[SK.SS_FUUMAKOUCHIKU]: 24,
	[SK.SS_KAGEGISSEN]: 25,
	[SK.SS_KINRYUUHOU]: 27,
	[SK.SS_HITOUAKUMU]: 30,
	[SK.SS_KAGEAKUMU]: 32,
	[SK.SS_ANTENPOU]: 34,
	[SK.SS_ANKOKURYUUAKUMU]: 41
};
SkillTreeView[JobId.SHINKIRO] = {
	list: 3,
	beforeJob: JobId.KAGEROU,
	[SK.SS_SHINKIROU]: 0,
	[SK.SS_SEKIENHOU]: 6,
	[SK.SS_SHIMIRU]: 7,
	[SK.SS_KUNAIWAIKYOKU]: 9,
	[SK.SS_KAGEGARI]: 11,
	[SK.SS_REIKETSUHOU]: 13,
	[SK.SS_TOKEDASU]: 14,
	[SK.SS_KUNAIKAITEN]: 16,
	[SK.SS_FUUMASHOUAKU]: 17,
	[SK.SS_KAGENOMAI]: 18,
	[SK.SS_RAIDENPOU]: 20,
	[SK.SS_AKUMUKESU]: 21,
	[SK.SS_KUNAIKUSSETSU]: 23,
	[SK.SS_FUUMAKOUCHIKU]: 24,
	[SK.SS_KAGEGISSEN]: 25,
	[SK.SS_KINRYUUHOU]: 27,
	[SK.SS_HITOUAKUMU]: 30,
	[SK.SS_KAGEAKUMU]: 32,
	[SK.SS_ANTENPOU]: 34,
	[SK.SS_ANKOKURYUUAKUMU]: 41
};

function duplicateEntry(origin) {
	const value = SkillTreeView[origin];
	for (let i = 1, count = arguments.length; i < count; ++i) {
		SkillTreeView[arguments[i]] = value;
	}
}

// Inherit
// baby
duplicateEntry(JobId.NOVICE, JobId.NOVICE_B);
duplicateEntry(JobId.SWORDMAN, JobId.SWORDMAN_B);
duplicateEntry(JobId.MAGICIAN, JobId.MAGICIAN_B);
duplicateEntry(JobId.ARCHER, JobId.ARCHER_B);
duplicateEntry(JobId.ACOLYTE, JobId.ACOLYTE_B);
duplicateEntry(JobId.MERCHANT, JobId.MERCHANT_B);
duplicateEntry(JobId.THIEF, JobId.THIEF_B);
duplicateEntry(JobId.KNIGHT, JobId.KNIGHT_B);
duplicateEntry(JobId.KNIGHT2, JobId.KNIGHT2_B);
duplicateEntry(JobId.PRIEST, JobId.PRIEST_B);
duplicateEntry(JobId.WIZARD, JobId.WIZARD_B);
duplicateEntry(JobId.BLACKSMITH, JobId.BLACKSMITH_B);
duplicateEntry(JobId.HUNTER, JobId.HUNTER_B);
duplicateEntry(JobId.ASSASSIN, JobId.ASSASSIN_B);
duplicateEntry(JobId.CRUSADER, JobId.CRUSADER_B);
duplicateEntry(JobId.CRUSADER2, JobId.CRUSADER2_B);
duplicateEntry(JobId.MONK, JobId.MONK_B);
duplicateEntry(JobId.SAGE, JobId.SAGE_B);
duplicateEntry(JobId.ROGUE, JobId.ROGUE_B);
duplicateEntry(JobId.ALCHEMIST, JobId.ALCHEMIST_B);
duplicateEntry(JobId.BARD, JobId.BARD_B);
duplicateEntry(JobId.DANCER, JobId.DANCER_B);
duplicateEntry(JobId.NINJA, JobId.NINJA_B);
duplicateEntry(JobId.KAGEROU, JobId.KAGEROU_B);
duplicateEntry(JobId.OBORO, JobId.OBORO_B);
duplicateEntry(JobId.TAEKWON, JobId.TAEKWON_B);
duplicateEntry(JobId.STAR_B, JobId.STAR_B);
duplicateEntry(JobId.STAR2_B, JobId.STAR2_B);
duplicateEntry(JobId.LINKER, JobId.LINKER_B);
duplicateEntry(JobId.GUNSLINGER, JobId.GUNSLINGER_B);
duplicateEntry(JobId.REBELLION, JobId.REBELLION_B);
duplicateEntry(JobId.STAR_EMPEROR, JobId.EMPEROR_B);
duplicateEntry(JobId.STAR_EMPEROR, JobId.EMPEROR2_B);
duplicateEntry(JobId.SOUL_REAPER, JobId.REAPER_B);

// High + Baby
duplicateEntry(JobId.NOVICE, JobId.NOVICE_H);
duplicateEntry(JobId.SWORDMAN, JobId.SWORDMAN_H);
duplicateEntry(JobId.MAGICIAN, JobId.MAGICIAN_H);
duplicateEntry(JobId.ARCHER, JobId.ARCHER_H);
duplicateEntry(JobId.ACOLYTE, JobId.ACOLYTE_H);
duplicateEntry(JobId.MERCHANT, JobId.MERCHANT_H);
duplicateEntry(JobId.THIEF, JobId.THIEF_H);
duplicateEntry(JobId.RUNE_KNIGHT, JobId.RUNE_KNIGHT_H, JobId.RUNE_KNIGHT_B);
duplicateEntry(JobId.RUNE_KNIGHT, JobId.RUNE_KNIGHT2, JobId.RUNE_KNIGHT2_H, JobId.RUNE_KNIGHT2_B);
duplicateEntry(JobId.WARLOCK, JobId.WARLOCK_H, JobId.WARLOCK_B);
duplicateEntry(JobId.RANGER, JobId.RANGER_H, JobId.RANGER_B);
duplicateEntry(JobId.RANGER, JobId.RANGER2, JobId.RANGER2_H, JobId.RANGER2_B);
duplicateEntry(JobId.ARCHBISHOP, JobId.ARCHBISHOP_H, JobId.ARCHBISHOP_B);
duplicateEntry(JobId.MECHANIC, JobId.MECHANIC_H, JobId.MECHANIC_B);
duplicateEntry(JobId.MECHANIC, JobId.MECHANIC2, JobId.MECHANIC2_H, JobId.MECHANIC2_B);
duplicateEntry(JobId.GUILLOTINE_CROSS, JobId.GUILLOTINE_CROSS_H, JobId.GUILLOTINE_CROSS_B);
duplicateEntry(JobId.ROYAL_GUARD, JobId.ROYAL_GUARD_H, JobId.ROYAL_GUARD_B);
duplicateEntry(JobId.ROYAL_GUARD, JobId.ROYAL_GUARD2, JobId.ROYAL_GUARD2_H, JobId.ROYAL_GUARD2_B);
duplicateEntry(JobId.SORCERER, JobId.SORCERER_H, JobId.SORCERER_B);
duplicateEntry(JobId.MINSTREL, JobId.MINSTREL_H, JobId.MINSTREL_B);
duplicateEntry(JobId.WANDERER, JobId.WANDERER_H, JobId.WANDERER_B);
duplicateEntry(JobId.SURA, JobId.SURA_H, JobId.SURA_B);
duplicateEntry(JobId.GENETIC, JobId.GENETIC_H, JobId.GENETIC_B);
duplicateEntry(JobId.SHADOW_CHASER, JobId.SHADOW_CHASER_H, JobId.SHADOW_CHASER_B);

duplicateEntry(JobId.DO_SUMMONER, JobId.DO_SUMMONER_B);

//MOUNTS
duplicateEntry(JobId.NOVICE, JobId.PORING_NOVICE, JobId.PORING_NOVICE_H, JobId.PORING_NOVICE_B);

duplicateEntry(JobId.ACOLYTE, JobId.SHEEP_ACO, JobId.SHEEP_ACO_H, JobId.SHEEP_ACO_B);
duplicateEntry(JobId.ARCHER, JobId.OSTRICH_ARCHER, JobId.OSTRICH_ARCHER_H, JobId.OSTRICH_ARCHER_B);
duplicateEntry(JobId.MAGICIAN, JobId.FOX_MAGICIAN, JobId.FOX_MAGICIAN_H, JobId.FOX_MAGICIAN_B);
duplicateEntry(JobId.MERCHANT, JobId.PIG_MERCHANT, JobId.PIG_MERCHANT_H, JobId.PIG_MERCHANT_B);
duplicateEntry(JobId.SWORDMAN, JobId.PECO_SWORD, JobId.PECO_SWORD_H, JobId.PECO_SWORD_B);
duplicateEntry(JobId.THIEF, JobId.DOG_THIEF, JobId.DOG_THIEF_H, JobId.DOG_THIEF_B);

duplicateEntry(JobId.PRIEST, JobId.SHEEP_PRIEST, JobId.SHEEP_PRIEST_B);
duplicateEntry(JobId.HUNTER, JobId.OSTRICH_HUNTER, JobId.OSTRICH_HUNTER_B);
duplicateEntry(JobId.WIZARD, JobId.FOX_WIZ, JobId.FOX_WIZ_B);
duplicateEntry(JobId.BLACKSMITH, JobId.PIG_BLACKSMITH, JobId.PIG_BLACKSMITH_B);
duplicateEntry(JobId.KNIGHT, JobId.LION_KNIGHT, JobId.LION_KNIGHT_B);
duplicateEntry(JobId.ASSASSIN, JobId.DOG_ASSASSIN, JobId.DOG_ASSASSIN_B);

duplicateEntry(JobId.MONK, JobId.SHEEP_MONK, JobId.SHEEP_MONK_B);
duplicateEntry(JobId.BARD, JobId.OSTRICH_BARD, JobId.OSTRICH_BARD_B);
duplicateEntry(JobId.DANCER, JobId.OSTRICH_DANCER, JobId.OSTRICH_DANCER_B);
duplicateEntry(JobId.SAGE, JobId.FOX_SAGE, JobId.FOX_SAGE_B);
duplicateEntry(JobId.ALCHEMIST, JobId.PIG_ALCHE, JobId.PIG_ALCHE_B);
duplicateEntry(JobId.CRUSADER, JobId.LION_CRUSADER, JobId.LION_CRUSADER_B);
duplicateEntry(JobId.ROGUE, JobId.DOG_ROGUE, JobId.DOG_ROGUE_B);

duplicateEntry(JobId.ARCHBISHOP, JobId.SHEEP_ARCB, JobId.SHEEP_ARCB_B);
duplicateEntry(JobId.RANGER, JobId.OSTRICH_RANGER, JobId.OSTRICH_RANGER_B);
duplicateEntry(JobId.WARLOCK, JobId.FOX_WARLOCK, JobId.FOX_WARLOCK_B);
duplicateEntry(JobId.MECHANIC, JobId.PIG_MECHANIC, JobId.PIG_MECHANIC_B);
duplicateEntry(JobId.KNIGHT, JobId.LION_RUNE_KNIGHT, JobId.LION_RUNE_KNIGHT_B);
duplicateEntry(JobId.GUILLOTINE_CROSS, JobId.DOG_G_CROSS, JobId.DOG_G_CROSS_B);

duplicateEntry(JobId.SURA, JobId.SHEEP_SURA, JobId.SHEEP_SURA_B);
duplicateEntry(JobId.MINSTREL, JobId.OSTRICH_MINSTREL, JobId.OSTRICH_MINSTREL_B);
duplicateEntry(JobId.WANDER, JobId.OSTRICH_WANDER, JobId.OSTRICH_WANDER_B);
duplicateEntry(JobId.SORCERER, JobId.FOX_SORCERER, JobId.FOX_SORCERER_B);
duplicateEntry(JobId.GENETIC, JobId.PIG_GENETIC, JobId.PIG_GENETIC_B);
duplicateEntry(JobId.ROYAL_GUARD, JobId.LION_ROYAL_GUARD, JobId.LION_ROYAL_GUARD_B);
duplicateEntry(JobId.SHADOW_CHASER, JobId.DOG_CHASER, JobId.DOG_CHASER_B);

duplicateEntry(
	JobId.SUPERNOVICE,
	JobId.PORING_SNOVICE,
	JobId.PORING_SNOVICE_B,
	JobId.PORING_SNOVICE2,
	JobId.PORING_SNOVICE2_B
);

duplicateEntry(JobId.NINJA, JobId.FROG_NINJA, JobId.FROG_NINJA_B);
duplicateEntry(JobId.GUNSLINGER, JobId.PECO_GUNNER, JobId.PECO_GUNNER_B);
duplicateEntry(JobId.TAEKWON, JobId.PORING_TAEKWON, JobId.PORING_TAEKWON_B);

duplicateEntry(JobId.STAR, JobId.PORING_STAR, JobId.PORING_STAR_B);
duplicateEntry(JobId.LINKER, JobId.FROG_LINKER, JobId.FROG_LINKER_B);

duplicateEntry(JobId.KAGEROU, JobId.FROG_KAGEROU, JobId.FROG_KAGEROU_B);
duplicateEntry(JobId.OBORO, JobId.FROG_OBORO, JobId.FROG_OBORO_B);
duplicateEntry(JobId.REBELLION, JobId.PECO_REBELLION, JobId.PECO_REBELLION_B);

// 4TH
duplicateEntry(JobId.WINDHAWK, JobId.WINDHAWK2);
duplicateEntry(JobId.MEISTER, JobId.MEISTER2);
duplicateEntry(JobId.DRAGON_KNIGHT, JobId.DRAGON_KNIGHT2);
duplicateEntry(JobId.IMPERIAL_GUARD, JobId.IMPERIAL_GUARD2);
duplicateEntry(JobId.SKY_EMPEROR, JobId.SKY_EMPEROR2);

export default SkillTreeView;
