// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#include "skill_factory_taekwon.hpp"

#include "../skill_impl.hpp"

// Include .cpp files into the TU to optimize compile time
// For reference see unity builds or amalgamated builds
#include "bookofcreatingstar.cpp"
#include "circleofdirectionsandelementals.cpp"
#include "counter.cpp"
#include "curseexplosion.cpp"
#include "documentofsunmoonandstar.cpp"
#include "downkick.cpp"
#include "esha.cpp"
#include "eska.cpp"
#include "eske.cpp"
#include "esma.cpp"
#include "espa.cpp"
#include "estin.cpp"
#include "estun.cpp"
#include "eswhoo.cpp"
#include "eswoo.cpp"
#include "exorcismofmalicioussoul.cpp"
#include "fairyssoul.cpp"
#include "falconssoul.cpp"
#include "fallingstar.cpp"
#include "feelingthesunmoonandstars.cpp"
#include "flashkick.cpp"
#include "fullmoonkick.cpp"
#include "golemssoul.cpp"
#include "gravitycontrol.cpp"
#include "hatredofthesunmoonandstars.cpp"
#include "highjump.cpp"
#include "jumpkick.cpp"
#include "kaahi.cpp"
#include "kaite.cpp"
#include "kaizel.cpp"
#include "kaupe.cpp"
#include "kaute.cpp"
#include "mission.cpp"
#include "newmoonkick.cpp"
#include "novaexplosion.cpp"
#include "prominencekick.cpp"
#include "run.cpp"
#include "sevenwind.cpp"
#include "shadowssoul.cpp"
#include "solarburst.cpp"
#include "soulcollect.cpp"
#include "soulcurse.cpp"
#include "souldivision.cpp"
#include "soulexplosion.cpp"
#include "soulgathering.cpp"
#include "soulofheavenandearth.cpp"
#include "soulrevolution.cpp"
#include "soulunity.cpp"
#include "spiritofrebirth.cpp"
#include "spiritofthealchemist.cpp"
#include "spiritoftheartist.cpp"
#include "spiritoftheassasin.cpp"
#include "spiritoftheblacksmith.cpp"
#include "spiritofthecrusader.cpp"
#include "spiritofthehunter.cpp"
#include "spiritoftheknight.cpp"
#include "spiritofthemonk.cpp"
#include "spiritofthepriest.cpp"
#include "spiritoftherogue.cpp"
#include "spiritofthesage.cpp"
#include "spiritofthesoullinker.cpp"
#include "spiritofthestargladiator.cpp"
#include "spiritofthesupernovice.cpp"
#include "spiritofthewizard.cpp"
#include "staremperoradvent.cpp"
#include "stormkick.cpp"
#include "talismanofblacktortoise.cpp"
#include "talismanofbluedragon.cpp"
#include "talismanoffiveelements.cpp"
#include "talismanoffourbearinggod.cpp"
#include "talismanofmagician.cpp"
#include "talismanofprotection.cpp"
#include "talismanofredphoenix.cpp"
#include "talismanofsoulstealing.cpp"
#include "talismanofwarrior.cpp"
#include "talismanofwhitetiger.cpp"
#include "totemoftutelary.cpp"
#include "turnkick.cpp"
#include "warmthofthemoon.cpp"
#include "warmthofthestars.cpp"
#include "warmthofthesun.cpp"

std::unique_ptr<const SkillImpl> SkillFactoryTaekwon::create(const e_skill skill_id) const {
	switch (skill_id) {
		case SG_FEEL:
			return std::make_unique<SkillFeelingtheSunMoonandStars>();
		case SG_FUSION:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case SG_HATE:
			return std::make_unique<SkillHatredoftheSunMoonandStars>();
		case SG_MOON_COMFORT:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SG_MOON_WARM:
			return std::make_unique<SkillWarmthoftheMoon>();
		case SG_STAR_COMFORT:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SG_STAR_WARM:
			return std::make_unique<SkillWarmthoftheStars>();
		case SG_SUN_COMFORT:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SG_SUN_WARM:
			return std::make_unique<SkillWarmthoftheSun>();
		case SJ_BOOKOFCREATINGSTAR:
			return std::make_unique<SkillBookofCreatingStar>();
		case SJ_BOOKOFDIMENSION:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SJ_DOCUMENT:
			return std::make_unique<SkillDocumentofSunMoonAndStar>();
		case SJ_FALLINGSTAR:
			return std::make_unique<SkillFallingStar>();
		case SJ_FALLINGSTAR_ATK:
			return std::make_unique<SkillFallingStarAttack>();
		case SJ_FALLINGSTAR_ATK2:
			return std::make_unique<SkillFallingStarAttack2>();
		case SJ_FLASHKICK:
			return std::make_unique<SkillFlashKick>();
		case SJ_FULLMOONKICK:
			return std::make_unique<SkillFullMoonKick>();
		case SJ_GRAVITYCONTROL:
			return std::make_unique<SkillGravityControl>();
		case SJ_LIGHTOFMOON:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SJ_LIGHTOFSTAR:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SJ_LIGHTOFSUN:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SJ_LUNARSTANCE:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case SJ_NEWMOONKICK:
			return std::make_unique<SkillNewMoonKick>();
		case SJ_NOVAEXPLOSING:
			return std::make_unique<SkillNovaExplosion>();
		case SJ_PROMINENCEKICK:
			return std::make_unique<SkillProminenceKick>();
		case SJ_SOLARBURST:
			return std::make_unique<SkillSolarBurst>();
		case SJ_STAREMPEROR:
			return std::make_unique<SkillStarEmperorAdvent>();
		case SJ_STARSTANCE:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case SJ_SUNSTANCE:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case SJ_UNIVERSESTANCE:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case SKE_DAWN_BREAK:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case SKE_ENCHANTING_SKY:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SKE_MIDNIGHT_KICK:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case SKE_RISING_MOON:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case SL_ALCHEMIST:
			return std::make_unique<SkillSpiritoftheAlchemist>();
		case SL_ASSASIN:
			return std::make_unique<SkillSpiritoftheAssasin>();
		case SL_BARDDANCER:
			return std::make_unique<SkillSpiritoftheArtist>();
		case SL_BLACKSMITH:
			return std::make_unique<SkillSpiritoftheBlacksmith>();
		case SL_CRUSADER:
			return std::make_unique<SkillSpiritoftheCrusader>();
		case SL_HIGH:
			return std::make_unique<SkillSpiritofRebirth>();
		case SL_HUNTER:
			return std::make_unique<SkillSpiritoftheHunter>();
		case SL_KAAHI:
			return std::make_unique<SkillKaahi>();
		case SL_KAITE:
			return std::make_unique<SkillKaite>();
		case SL_KAIZEL:
			return std::make_unique<SkillKaizel>();
		case SL_KAUPE:
			return std::make_unique<SkillKaupe>();
		case SL_KNIGHT:
			return std::make_unique<SkillSpiritoftheKnight>();
		case SL_MONK:
			return std::make_unique<SkillSpiritoftheMonk>();
		case SL_PRIEST:
			return std::make_unique<SkillSpiritofthePriest>();
		case SL_ROGUE:
			return std::make_unique<SkillSpiritoftheRogue>();
		case SL_SAGE:
			return std::make_unique<SkillSpiritoftheSage>();
		case SL_SKA:
			return std::make_unique<SkillEska>();
		case SL_SKE:
			return std::make_unique<SkillEske>();
		case SL_SMA:
			return std::make_unique<SkillEsma>();
		case SL_SOULLINKER:
			return std::make_unique<SkillSpiritoftheSoulLinker>();
		case SL_STAR:
			return std::make_unique<SkillSpiritoftheStarGladiator>();
		case SL_STIN:
			return std::make_unique<SkillEstin>();
		case SL_STUN:
			return std::make_unique<SkillEstun>();
		case SL_SUPERNOVICE:
			return std::make_unique<SkillSpiritoftheSupernovice>();
		case SL_SWOO:
			return std::make_unique<SkillEswoo>();
		case SL_WIZARD:
			return std::make_unique<SkillSpiritoftheWizard>();
		case SOA_CIRCLE_OF_DIRECTIONS_AND_ELEMENTALS:
			return std::make_unique<SkillCircleOfDirectionsAndElementals>();
		case SOA_EXORCISM_OF_MALICIOUS_SOUL:
			return std::make_unique<SkillExorcismOfMaliciousSoul>();
		case SOA_SOUL_GATHERING:
			return std::make_unique<SkillSoulGathering>();
		case SOA_SOUL_OF_HEAVEN_AND_EARTH:
			return std::make_unique<SkillSoulOfHeavenAndEarth>();
		case SOA_TALISMAN_OF_BLACK_TORTOISE:
			return std::make_unique<SkillTalismanOfBlackTortoise>();
		case SOA_TALISMAN_OF_BLUE_DRAGON:
			return std::make_unique<SkillTalismanOfBlueDragon>();
		case SOA_TALISMAN_OF_FIVE_ELEMENTS:
			return std::make_unique<SkillTalismanOfFiveElements>();
		case SOA_TALISMAN_OF_FOUR_BEARING_GOD:
			return std::make_unique<SkillTalismanOfFourBearingGod>();
		case SOA_TALISMAN_OF_MAGICIAN:
			return std::make_unique<SkillTalismanOfMagician>();
		case SOA_TALISMAN_OF_PROTECTION:
			return std::make_unique<SkillTalismanOfProtection>();
		case SOA_TALISMAN_OF_RED_PHOENIX:
			return std::make_unique<SkillTalismanOfRedPhoenix>();
		case SOA_TALISMAN_OF_SOUL_STEALING:
			return std::make_unique<SkillTalismanOfSoulStealing>();
		case SOA_TALISMAN_OF_WARRIOR:
			return std::make_unique<SkillTalismanOfWarrior>();
		case SOA_TALISMAN_OF_WHITE_TIGER:
			return std::make_unique<SkillTalismanOfWhiteTiger>();
		case SOA_TOTEM_OF_TUTELARY:
			return std::make_unique<SkillTotemOfTutelary>();
		case SP_CURSEEXPLOSION:
			return std::make_unique<SkillCurseExplosion>();
		case SP_KAUTE:
			return std::make_unique<SkillKaute>();
		case SP_SHA:
			return std::make_unique<SkillEsha>();
		case SP_SOULCOLLECT:
			return std::make_unique<SkillSoulCollect>();
		case SP_SOULCURSE:
			return std::make_unique<SkillSoulCurse>();
		case SP_SOULDIVISION:
			return std::make_unique<SkillSoulDivision>();
		case SP_SOULEXPLOSION:
			return std::make_unique<SkillSoulExplosion>();
		case SP_SOULFAIRY:
			return std::make_unique<SkillFairysSoul>();
		case SP_SOULFALCON:
			return std::make_unique<SkillFalconsSoul>();
		case SP_SOULGOLEM:
			return std::make_unique<SkillGolemsSoul>();
		case SP_SOULREAPER:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SP_SOULREVOLVE:
			return std::make_unique<SkillSoulRevolution>();
		case SP_SOULSHADOW:
			return std::make_unique<SkillShadowsSoul>();
		case SP_SOULUNITY:
			return std::make_unique<SkillSoulUnity>();
		case SP_SPA:
			return std::make_unique<SkillEspa>();
		case SP_SWHOO:
			return std::make_unique<SkillEswhoo>();
		case TK_COUNTER:
			return std::make_unique<SkillCounter>();
		case TK_DODGE:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case TK_DOWNKICK:
			return std::make_unique<SkillDownKick>();
		case TK_HIGHJUMP:
			return std::make_unique<SkillHighJump>();
		case TK_JUMPKICK:
			return std::make_unique<SkillJumpKick>();
		case TK_MISSION:
			return std::make_unique<SkillMission>();
		case TK_READYCOUNTER:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case TK_READYDOWN:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case TK_READYSTORM:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case TK_READYTURN:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case TK_RUN:
			return std::make_unique<SkillRun>();
		case TK_SEVENWIND:
			return std::make_unique<SkillSevenWind>();
		case TK_STORMKICK:
			return std::make_unique<SkillStormKick>();
		case TK_TURNKICK:
			return std::make_unique<SkillTurnKick>();

		default:
			return nullptr;
	}
}
