ALTER TABLE `picklog`
	CHANGE COLUMN `option_id0` `option_id0` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `card3`,
	CHANGE COLUMN `option_val0` `option_val0` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `option_id0`,
	CHANGE COLUMN `option_parm0` `option_parm0` TINYINT(3) NOT NULL DEFAULT '0' AFTER `option_val0`,
	CHANGE COLUMN `option_id1` `option_id1` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `option_parm0`,
	CHANGE COLUMN `option_val1` `option_val1` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `option_id1`,
	CHANGE COLUMN `option_parm1` `option_parm1` TINYINT(3) NOT NULL DEFAULT '0' AFTER `option_val1`,
	CHANGE COLUMN `option_id2` `option_id2` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `option_parm1`,
	CHANGE COLUMN `option_val2` `option_val2` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `option_id2`,
	CHANGE COLUMN `option_parm2` `option_parm2` TINYINT(3) NOT NULL DEFAULT '0' AFTER `option_val2`,
	CHANGE COLUMN `option_id3` `option_id3` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `option_parm2`,
	CHANGE COLUMN `option_val3` `option_val3` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `option_id3`,
	CHANGE COLUMN `option_parm3` `option_parm3` TINYINT(3) NOT NULL DEFAULT '0' AFTER `option_val3`,
	CHANGE COLUMN `option_id4` `option_id4` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `option_parm3`,
	CHANGE COLUMN `option_val4` `option_val4` SMALLINT(5) NOT NULL DEFAULT '0' AFTER `option_id4`,
	CHANGE COLUMN `option_parm4` `option_parm4` TINYINT(3) NOT NULL DEFAULT '0' AFTER `option_val4`;