ALTER TABLE `homunculus`
	CHANGE COLUMN `char_id` `char_id` INT(11) UNSIGNED NOT NULL,
	CHANGE COLUMN `sp` `sp` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	CHANGE COLUMN `max_sp` `max_sp` INT(11) UNSIGNED NOT NULL DEFAULT '0';
