-- Drop table to able to use enum for activity column
DROP TABLE IF EXISTS `interlog`;

CREATE TABLE IF NOT EXISTS `interlog` (
	`time` DATETIME NULL DEFAULT NULL,
	`activity` enum('ADD MEMBER','DEL MEMBER','ADD ALLIANCE','DEL ALLIANCE','ADD ANTAGONIST','DEL ANTAGONIST','CREATE GUILD','BREAK GUILD','OCCUPY','ABANDON','CHANGE MASTER') NULL DEFAULT 'CREATE GUILD',
	`guild_id` INT(11) NULL DEFAULT NULL,
	`origin` VARCHAR(255) NULL DEFAULT NULL,
	`target` VARCHAR(255) NULL DEFAULT NULL,
	`castle_id` INT(11) NULL DEFAULT NULL
)
ENGINE=MyISAM;