#!/bin/sh
# checking-doc script by trojal
# modified by lighta

case $1 in
    'script')
	#find which script commands are missing from doc/script_commands.txt
	echo "Missing script documentation for function :"
	awk '/BUILDIN_DEF\(.*\),/ {b=match($0,"BUILDIN_DEF(.*),");c=match($0,",");print substr($0,b+12,c-b-12);}' ../src/map/script.c | xargs -I{} sh -c '! grep -Lq {} ../doc/script_commands.txt && echo {}'
	awk '/BUILDIN_DEF2\(.*\),/ {b=match($0,"BUILDIN_DEF2(.*),");c=match($0,",");d=match($0 ,"\",\"");print substr($0,c+2,d-c-2);}' ../src/map/script.c | xargs -I{} sh -c '! grep -Lq {} ../doc/script_commands.txt && echo {}'
	;;

    'atc')
	#find which atcommands are missing from doc/atcommands.txt
	echo "Missing atcommand documentation for function :"
	awk '/ACMD_DEF\(.*\),/ {b=match($0,"ACMD_DEF(.*),");c=match($0,",");print substr($0,b+9,c-b-10);}' ../src/map/atcommand.c | xargs -I{} sh -c '! grep -Lq {} ../doc/atcommands.txt && echo {}'
	awk '/ACMD_DEF2\(.*\),/ {b=match($0,"ACMD_DEF2(.*),");c=match($0,",");print substr($0,b+10,c-b-10);}' ../src/map/atcommand.c | xargs -I{} sh -c '! grep -Lq {} ../doc/atcommands.txt && echo {}'
	;;
     'both')
	$0 script
	$0 atc
	;;

	*)
        	echo "Usage: check-doc { script | atc | both }"
        	read -p "Enter a valid option: " readEnterKey
        	$0 $readEnterKey
	;;
esac

