name: Lint and Format

concurrency:
    group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
    push:
        branches:
            - master

permissions:
    contents: write

jobs:
    quality:
        name: Lint + Format
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '24'

            - name: Install dependencies
              run: npm i

            - name: Run ESLint
              run: npm run lint -- --fix

            - name: Run Prettier
              run: npx prettier . --write

            - name: Commit changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add -A
                  git reset .github/workflows/

                  git diff --cached --quiet || git commit -m "code-quality: auto lint + format"
                  git push
