name: Build rAthena Renewal Terbaru (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zlib1g-dev libpcre3-dev gcc g++ make

      - name: Configure (Renewal + Packet terbaru)
        run: |
          ./configure --enable-prere=no

      - name: Compile (make server)
        run: make -j$(nproc) server

      - name: Upload binaries (ARM64)
        uses: actions/upload-artifact@v4
        with:
          name: rathena-renewal-arm64
          path: |
            login-server
            char-server
            map-server
