name: Build servers with CMake and GCC on Linux

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      # Always trigger all Github Actions if an action or something CI related was changed
      - '.github/workflows/**'
      - 'tools/ci/**'
      # This workflow should run when a file in a source directory has been modified.
      - 'src/**'
      - '3rdparty/**'
      # This workflow should run whenever a CMake related file has been modified
      - '**/CMakeLists.txt'

jobs:
  build:
    # Github Actions checks for '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]', or '[actions skip]' but not a hyphenated version.
    # It's a catch-all incase a Pull Request has been opened and someone is on auto-pilot.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest]
          gcc: ['9', '10', '11', '12', '13', '14']

    steps:
      - uses: actions/checkout@v4

      - name: Update & Install compilers
        run: |
          sudo apt update
          sudo apt install zlib1g-dev libpcre3-dev gcc-${{matrix.gcc}} g++-${{matrix.gcc}}

      - name: Configure CMake
        run: CXX=g++-${{matrix.gcc}} CC=gcc-${{matrix.gcc}} cmake -B build

      - name: Build
        run: cmake --build build -j $(nproc) --target all
