name: Cross-Compile rAthena ARM64 (Renewal)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Multiarch & Install ARM64 Compiler
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt install -y libpcre3-dev:arm64 zlib1g-dev:arm64
          sudo apt install -y pkg-config

      - name: Configure (Renewal, Packet Terbaru)
        env:
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
        run: |
          ./configure --host=aarch64-linux-gnu --disable-prere

      - name: Compile
        run: make -j$(nproc) server

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rathena-renewal-arm64
          path: |
            login-server
            char-server
            map-server
