name: "Build All Nightly"
on:
    schedule:
        - cron: "0 0 * * *"
jobs:
    build-all:
        runs-on: ubuntu-latest
        steps:
            - name: Invoke build-all
              uses: benc-uk/workflow-dispatch@v1
              with:
                  workflow: Build and publish all images to Docker Hub
                  token: ${{ secrets.PERSONAL_TOKEN }}
                  inputs: '{ "image_name_prefix": "rathena", "image_tag": "nightly", "ref" : "main"}'
