// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#include "skill_factory_mage.hpp"

#include "../skill_impl.hpp"

// Include .cpp files into the TU to optimize compile time
// For reference see unity builds or amalgamated builds
#include "activityburn.cpp"
#include "ageofice.cpp"
#include "allbloom.cpp"
#include "astralstrike.cpp"
#include "avalanche.cpp"
#include "beastlyhypnosis.cpp"
#include "castcancel.cpp"
#include "chainlightning.cpp"
#include "classchange.cpp"
#include "coldbolt.cpp"
#include "coldforce.cpp"
#include "coma.cpp"
#include "comet.cpp"
#include "conflagration.cpp"
#include "createelementalconverter.cpp"
#include "crimsonarrow.cpp"
#include "crimsonrock.cpp"
#include "crystalarmor.cpp"
#include "crystalimpact.cpp"
#include "deadlypoison.cpp"
#include "deadlyprojection.cpp"
#include "deeppoisoning.cpp"
#include "deluge.cpp"
#include "destructivehurricane.cpp"
#include "diamondstorm.cpp"
#include "dispell.cpp"
#include "drainlife.cpp"
#include "earthcare.cpp"
#include "earthspike.cpp"
#include "earthstrain.cpp"
#include "elementalbuster.cpp"
#include "elementalchangeearth.cpp"
#include "elementalchangefire.cpp"
#include "elementalchangewater.cpp"
#include "elementalchangewind.cpp"
#include "elementalveil.cpp"
#include "endowblaze.cpp"
#include "endowquake.cpp"
#include "endowtornado.cpp"
#include "endowtsunami.cpp"
#include "energycoat.cpp"
#include "energyconversion.cpp"
#include "eyesofstorm.cpp"
#include "fireball.cpp"
#include "firebolt.cpp"
#include "firepillar.cpp"
#include "firewall.cpp"
#include "flamearmor.cpp"
#include "flamerock.cpp"
#include "flametechnic.cpp"
#include "floralflareroad.cpp"
#include "frostdiver.cpp"
#include "frostnova.cpp"
#include "frostymisty.cpp"
#include "frozenslash.cpp"
#include "ganbantein.cpp"
#include "golddigger.cpp"
#include "gracebreeze.cpp"
#include "gravitationfield.cpp"
#include "gravity.cpp"
#include "grimreaper.cpp"
#include "heavensdrive.cpp"
#include "hellinferno.cpp"
#include "hindsight.cpp"
#include "hocuspocus.cpp"
#include "icewall.cpp"
#include "increasingactivity.cpp"
#include "jackfrost.cpp"
#include "jupitelthunder.cpp"
#include "leveling.cpp"
#include "lightningbolt.cpp"
#include "lightningland.cpp"
#include "lordofvermilion.cpp"
#include "magicrod.cpp"
#include "magneticearth.cpp"
#include "meteorstorm.cpp"
#include "monocell.cpp"
#include "monsterchant.cpp"
#include "mysteryillusion.cpp"
#include "napalmbeat.cpp"
#include "napalmvulcan.cpp"
#include "poisonshield.cpp"
#include "psychicstream.cpp"
#include "quagmire.cpp"
#include "questioning.cpp"
#include "rainofcrystal.cpp"
#include "readingspellbook.cpp"
#include "rejuvenation.cpp"
#include "release.cpp"
#include "rockdown.cpp"
#include "safetywall.cpp"
#include "sense.cpp"
#include "siennaexecrate.cpp"
#include "sight.cpp"
#include "sightblaster.cpp"
#include "sightrasher.cpp"
#include "soulexpansion.cpp"
#include "soulstrike.cpp"
#include "soulvulcanstrike.cpp"
#include "spellbreaker.cpp"
#include "stasis.cpp"
#include "stonecurse.cpp"
#include "stormcannon.cpp"
#include "stormgust.cpp"
#include "stormwind.cpp"
#include "strantumtremor.cpp"
#include "strongprotection.cpp"
#include "suicide.cpp"
#include "summonelementalardor.cpp"
#include "summonelementaldiluvio.cpp"
#include "summonelementalprocella.cpp"
#include "summonelementalserpens.cpp"
#include "summonelementalterremotus.cpp"
#include "summonfireball.cpp"
#include "summonlightningball.cpp"
#include "summonstone.cpp"
#include "summonwaterball.cpp"
#include "terradrive.cpp"
#include "tetravortex.cpp"
#include "thunderstorm.cpp"
#include "tornadostorm.cpp"
#include "venomswamp.cpp"
#include "violentquake.cpp"
#include "volcano.cpp"
#include "waterball.cpp"
#include "whirlwind.cpp"
#include "whiteimprison.cpp"

std::unique_ptr<const SkillImpl> SkillFactoryMage::create(const e_skill skill_id) const {
	switch (skill_id) {
		case AG_ALL_BLOOM:
			return std::make_unique<SkillAllBloom>();
		case AG_ALL_BLOOM_ATK:
			return std::make_unique<SkillAllBloomAttack>();
		case AG_ALL_BLOOM_ATK2:
			return std::make_unique<SkillAllBloomAttack2>();
		case AG_ASTRAL_STRIKE:
			return std::make_unique<SkillAstralStrike>();
		case AG_ASTRAL_STRIKE_ATK:
			return std::make_unique<SkillAstralStrikeAttack>();
		case AG_CLIMAX:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case AG_CRIMSON_ARROW:
			return std::make_unique<SkillCrimsonArrow>();
		case AG_CRIMSON_ARROW_ATK:
			return std::make_unique<SkillCrimsonArrowAttack>();
		case AG_CRYSTAL_IMPACT:
			return std::make_unique<SkillCrystalImpact>();
		case AG_CRYSTAL_IMPACT_ATK:
			return std::make_unique<SkillCrystalImpactAttack>();
		case AG_DEADLY_PROJECTION:
			return std::make_unique<SkillDeadlyProjection>();
		case AG_DESTRUCTIVE_HURRICANE:
			return std::make_unique<SkillDestructiveHurricane>();
		case AG_DESTRUCTIVE_HURRICANE_CLIMAX:
			return std::make_unique<SkillDestructiveHurricaneClimax>();
		case AG_ENERGY_CONVERSION:
			return std::make_unique<SkillEnergyConversion>();
		case AG_FLORAL_FLARE_ROAD:
			return std::make_unique<SkillFloralFlareRoad>();
		case AG_FROZEN_SLASH:
			return std::make_unique<SkillFrozenSlash>();
		case AG_MYSTERY_ILLUSION:
			return std::make_unique<SkillMysteryIllusion>();
		case AG_RAIN_OF_CRYSTAL:
			return std::make_unique<SkillRainOfCrystal>();
		case AG_ROCK_DOWN:
			return std::make_unique<SkillRockDown>();
		case AG_SOUL_VC_STRIKE:
			return std::make_unique<SkillSoulVulcanStrike>();
		case AG_STORM_CANNON:
			return std::make_unique<SkillStormCannon>();
		case AG_STRANTUM_TREMOR:
			return std::make_unique<SkillStrantumTremor>();
		case AG_TORNADO_STORM:
			return std::make_unique<SkillTornadoStorm>();
		case AG_VIOLENT_QUAKE:
			return std::make_unique<SkillViolentQuake>();
		case AG_VIOLENT_QUAKE_ATK:
			return std::make_unique<SkillViolentQuakeAttack>();
		case EM_ACTIVITY_BURN:
			return std::make_unique<SkillActivityBurn>();
		case EM_CONFLAGRATION:
			return std::make_unique<SkillConflagration>();
		case EM_DIAMOND_STORM:
			return std::make_unique<SkillDiamondStorm>();
		case EM_ELEMENTAL_BUSTER:
			return std::make_unique<SkillElementalBuster>();
		case EM_ELEMENTAL_BUSTER_FIRE:
			return std::make_unique<SkillElementalBusterFire>();
		case EM_ELEMENTAL_BUSTER_GROUND:
			return std::make_unique<SkillElementalBusterGround>();
		case EM_ELEMENTAL_BUSTER_POISON:
			return std::make_unique<SkillElementalBusterPoison>();
		case EM_ELEMENTAL_BUSTER_WATER:
			return std::make_unique<SkillElementalBusterWater>();
		case EM_ELEMENTAL_BUSTER_WIND:
			return std::make_unique<SkillElementalBusterWind>();
		case EM_ELEMENTAL_VEIL:
			return std::make_unique<SkillElementalVeil>();
		case EM_EL_AGE_OF_ICE:
			return std::make_unique<SkillAgeOfIce>();
		case EM_EL_AVALANCHE:
			return std::make_unique<SkillAvalanche>();
		case EM_EL_COLD_FORCE:
			return std::make_unique<SkillColdForce>();
		case EM_EL_CRYSTAL_ARMOR:
			return std::make_unique<SkillCrystalArmor>();
		case EM_EL_DEADLY_POISON:
			return std::make_unique<SkillDeadlyPoison>();
		case EM_EL_DEEP_POISONING:
			return std::make_unique<SkillDeepPoisoning>();
		case EM_EL_EARTH_CARE:
			return std::make_unique<SkillEarthCare>();
		case EM_EL_EYES_OF_STORM:
			return std::make_unique<SkillEyesOfStorm>();
		case EM_EL_FLAMEARMOR:
			return std::make_unique<SkillFlameArmor>();
		case EM_EL_FLAMEROCK:
			return std::make_unique<SkillFlameRock>();
		case EM_EL_FLAMETECHNIC:
			return std::make_unique<SkillFlameTechnic>();
		case EM_EL_GRACE_BREEZE:
			return std::make_unique<SkillGraceBreeze>();
		case EM_EL_POISON_SHIELD:
			return std::make_unique<SkillPoisonShield>();
		case EM_EL_STORM_WIND:
			return std::make_unique<SkillStormWind>();
		case EM_EL_STRONG_PROTECTION:
			return std::make_unique<SkillStrongProtection>();
		case EM_INCREASING_ACTIVITY:
			return std::make_unique<SkillIncreasingActivity>();
		case EM_LIGHTNING_LAND:
			return std::make_unique<SkillLightningLand>();
		case EM_PSYCHIC_STREAM:
			return std::make_unique<SkillPsychicStream>();
		case EM_SPELL_ENCHANTING:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case EM_SUMMON_ELEMENTAL_ARDOR:
			return std::make_unique<SkillSummonElementalArdor>();
		case EM_SUMMON_ELEMENTAL_DILUVIO:
			return std::make_unique<SkillSummonElementalDiluvio>();
		case EM_SUMMON_ELEMENTAL_PROCELLA:
			return std::make_unique<SkillSummonElementalProcella>();
		case EM_SUMMON_ELEMENTAL_SERPENS:
			return std::make_unique<SkillSummonElementalSerpens>();
		case EM_SUMMON_ELEMENTAL_TERREMOTUS:
			return std::make_unique<SkillSummonElementalTerremotus>();
		case EM_TERRA_DRIVE:
			return std::make_unique<SkillTerraDrive>();
		case EM_VENOM_SWAMP:
			return std::make_unique<SkillVenomSwamp>();
		case HW_GANBANTEIN:
			return std::make_unique<SkillGanbantein>();
		case HW_GRAVITATION:
			return std::make_unique<SkillGravitationField>();
		case HW_MAGICCRASHER:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case HW_MAGICPOWER:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case HW_NAPALMVULCAN:
			return std::make_unique<SkillNapalmVulcan>();
		case MG_COLDBOLT:
			return std::make_unique<SkillColdBolt>();
		case MG_ENERGYCOAT:
			return std::make_unique<SkillEnergyCoat>();
		case MG_FIREBALL:
			return std::make_unique<SkillFireBall>();
		case MG_FIREBOLT:
			return std::make_unique<SkillFireBolt>();
		case MG_FIREWALL:
			return std::make_unique<SkillFireWall>();
		case MG_FROSTDIVER:
			return std::make_unique<SkillFrostDiver>();
		case MG_LIGHTNINGBOLT:
			return std::make_unique<SkillLightningBolt>();
		case MG_NAPALMBEAT:
			return std::make_unique<SkillNapalmBeat>();
		case MG_SAFETYWALL:
			return std::make_unique<SkillSafetyWall>();
		case MG_SIGHT:
			return std::make_unique<SkillSight>();
		case MG_SOULSTRIKE:
			return std::make_unique<SkillSoulStrike>();
		case MG_STONECURSE:
			return std::make_unique<SkillStoneCurse>();
		case MG_THUNDERSTORM:
			return std::make_unique<SkillThunderStorm>();
		case PF_DOUBLECASTING:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case PF_MEMORIZE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SA_ABRACADABRA:
			return std::make_unique<SkillHocusPocus>();
		case SA_AUTOSPELL:
			return std::make_unique<SkillHindsight>();
		case SA_CASTCANCEL:
			return std::make_unique<SkillCastCancel>();
		case SA_CLASSCHANGE:
			return std::make_unique<SkillClassChange>();
		case SA_COMA:
			return std::make_unique<SkillComa>();
		case SA_CREATECON:
			return std::make_unique<SkillCreateElementalConverter>();
		case SA_DEATH:
			return std::make_unique<SkillGrimReaper>();
		case SA_DELUGE:
			return std::make_unique<SkillDeluge>();
		case SA_DISPELL:
			return std::make_unique<SkillDispell>();
		case SA_ELEMENTFIRE:
			return std::make_unique<SkillElementalChangeFire>();
		case SA_ELEMENTGROUND:
			return std::make_unique<SkillElementalChangeEarth>();
		case SA_ELEMENTWATER:
			return std::make_unique<SkillElementalChangeWater>();
		case SA_ELEMENTWIND:
			return std::make_unique<SkillElementalChangeWind>();
		case SA_FLAMELAUNCHER:
			return std::make_unique<SkillEndowBlaze>();
		case SA_FORTUNE:
			return std::make_unique<SkillGoldDigger>();
		case SA_FROSTWEAPON:
			return std::make_unique<SkillEndowTsunami>();
		case SA_FULLRECOVERY:
			return std::make_unique<SkillRejuvenation>();
		case SA_GRAVITY:
			return std::make_unique<SkillGravity>();
		case SA_INSTANTDEATH:
			return std::make_unique<SkillSuicide>();
		case SA_LANDPROTECTOR:
			return std::make_unique<SkillMagneticEarth>();
		case SA_LEVELUP:
			return std::make_unique<SkillLeveling>();
		case SA_LIGHTNINGLOADER:
			return std::make_unique<SkillEndowTornado>();
		case SA_MAGICROD:
			return std::make_unique<SkillMagicRod>();
		case SA_MONOCELL:
			return std::make_unique<SkillMonocell>();
		case SA_QUESTION:
			return std::make_unique<SkillQuestioning>();
		case SA_REVERSEORCISH:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SA_SEISMICWEAPON:
			return std::make_unique<SkillEndowQuake>();
		case SA_SPELLBREAKER:
			return std::make_unique<SkillSpellBreaker>();
		case SA_SUMMONMONSTER:
			return std::make_unique<SkillMonsterChant>();
		case SA_TAMINGMONSTER:
			return std::make_unique<SkillBeastlyHypnosis>();
		case SA_VIOLENTGALE:
			return std::make_unique<SkillWhirlwind>();
		case SA_VOLCANO:
			return std::make_unique<SkillVolcano>();
		case WL_CHAINLIGHTNING:
			return std::make_unique<SkillChainLightning>();
		case WL_CHAINLIGHTNING_ATK:
			return std::make_unique<SkillChainLightningAttack>();
		case WL_COMET:
			return std::make_unique<SkillComet>();
		case WL_CRIMSONROCK:
			return std::make_unique<SkillCrimsonRock>();
		case WL_DRAINLIFE:
			return std::make_unique<SkillDrainLife>();
		case WL_EARTHSTRAIN:
			return std::make_unique<SkillEarthStrain>();
		case WL_FROSTMISTY:
			return std::make_unique<SkillFrostyMisty>();
		case WL_HELLINFERNO:
			return std::make_unique<SkillHellInferno>();
		case WL_JACKFROST:
			return std::make_unique<SkillJackFrost>();
		case WL_MARSHOFABYSS:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WL_READING_SB_READING:
			return std::make_unique<SkillReadingSpellbook>();
		case WL_RECOGNIZEDSPELL:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WL_RELEASE:
			return std::make_unique<SkillRelease>();
		case WL_SIENNAEXECRATE:
			return std::make_unique<SkillSiennaExecrate>();
		case WL_SOULEXPANSION:
			return std::make_unique<SkillSoulExpansion>();
		case WL_STASIS:
			return std::make_unique<SkillStasis>();
		case WL_SUMMONBL:
			return std::make_unique<SkillSummonLightningBall>();
		case WL_SUMMONFB:
			return std::make_unique<SkillSummonFireBall>();
		case WL_SUMMONSTONE:
			return std::make_unique<SkillSummonStone>();
		case WL_SUMMONWB:
			return std::make_unique<SkillSummonWaterBall>();
		case WL_SUMMON_ATK_FIRE:
			return std::make_unique<SkillSummonAttackFire>();
		case WL_SUMMON_ATK_GROUND:
			return std::make_unique<SkillSummonAttackEarth>();
		case WL_SUMMON_ATK_WATER:
			return std::make_unique<SkillSummonAttackWater>();
		case WL_SUMMON_ATK_WIND:
			return std::make_unique<SkillSummonAttackWind>();
		case WL_TELEKINESIS_INTENSE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WL_TETRAVORTEX:
			return std::make_unique<SkillTetraVortex>();
		case WL_TETRAVORTEX_FIRE:
			return std::make_unique<SkillTetraVortexFire>();
		case WL_TETRAVORTEX_GROUND:
			return std::make_unique<SkillTetraVortexEarth>();
		case WL_TETRAVORTEX_WATER:
			return std::make_unique<SkillTetraVortexWater>();
		case WL_TETRAVORTEX_WIND:
			return std::make_unique<SkillTetraVortexWind>();
		case WL_WHITEIMPRISON:
			return std::make_unique<SkillWhiteImprison>();
		case WZ_EARTHSPIKE:
			return std::make_unique<SkillEarthSpike>();
		case WZ_ESTIMATION:
			return std::make_unique<SkillSense>();
		case WZ_FIREPILLAR:
			return std::make_unique<SkillFirePillar>();
		case WZ_FROSTNOVA:
			return std::make_unique<SkillFrostNova>();
		case WZ_HEAVENDRIVE:
			return std::make_unique<SkillHeavensDrive>();
		case WZ_ICEWALL:
			return std::make_unique<SkillIceWall>();
		case WZ_JUPITEL:
			return std::make_unique<SkillJupitelThunder>();
		case WZ_METEOR:
			return std::make_unique<SkillMeteorStorm>();
		case WZ_QUAGMIRE:
			return std::make_unique<SkillQuagmire>();
		case WZ_SIGHTBLASTER:
			return std::make_unique<SkillSightBlaster>();
		case WZ_SIGHTRASHER:
			return std::make_unique<SkillSightRasher>();
		case WZ_STORMGUST:
			return std::make_unique<SkillStormGust>();
		case WZ_VERMILION:
			return std::make_unique<SkillLordOfVermilion>();
		case WZ_WATERBALL:
			return std::make_unique<SkillWaterBall>();

		default:
			return nullptr;
	}
}
