// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#include "skill_factory_mage.hpp"

#include "../skill_impl.hpp"

// Include .cpp files into the TU to optimize compile time
// For reference see unity builds or amalgamated builds
#include "allbloom.cpp"
#include "astralstrike.cpp"
#include "coldbolt.cpp"
#include "crimsonarrow.cpp"
#include "crystalimpact.cpp"
#include "deadlyprojection.cpp"
#include "destructivehurricane.cpp"
#include "earthspike.cpp"
#include "energycoat.cpp"
#include "energyconversion.cpp"
#include "fireball.cpp"
#include "firebolt.cpp"
#include "firepillar.cpp"
#include "firewall.cpp"
#include "floralflareroad.cpp"
#include "frostdiver.cpp"
#include "frostnova.cpp"
#include "frozenslash.cpp"
#include "ganbantein.cpp"
#include "gravitationfield.cpp"
#include "heavensdrive.cpp"
#include "icewall.cpp"
#include "jupitelthunder.cpp"
#include "lightningbolt.cpp"
#include "lordofvermilion.cpp"
#include "meteorstorm.cpp"
#include "mysteryillusion.cpp"
#include "napalmbeat.cpp"
#include "napalmvulcan.cpp"
#include "quagmire.cpp"
#include "rainofcrystal.cpp"
#include "rockdown.cpp"
#include "safetywall.cpp"
#include "sense.cpp"
#include "sight.cpp"
#include "sightblaster.cpp"
#include "sightrasher.cpp"
#include "soulstrike.cpp"
#include "soulvulcanstrike.cpp"
#include "stonecurse.cpp"
#include "stormcannon.cpp"
#include "stormgust.cpp"
#include "strantumtremor.cpp"
#include "thunderstorm.cpp"
#include "tornadostorm.cpp"
#include "violentquake.cpp"
#include "waterball.cpp"

std::unique_ptr<const SkillImpl> SkillFactoryMage::create(const e_skill skill_id) const {
	switch (skill_id) {
		case AG_ALL_BLOOM:
			return std::make_unique<SkillAllBloom>();
		case AG_ALL_BLOOM_ATK:
			return std::make_unique<SkillAllBloomAttack>();
		case AG_ALL_BLOOM_ATK2:
			return std::make_unique<SkillAllBloomAttack2>();
		case AG_ASTRAL_STRIKE:
			return std::make_unique<SkillAstralStrike>();
		case AG_ASTRAL_STRIKE_ATK:
			return std::make_unique<SkillAstralStrikeAttack>();
		case AG_CLIMAX:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case AG_CRIMSON_ARROW:
			return std::make_unique<SkillCrimsonArrow>();
		case AG_CRIMSON_ARROW_ATK:
			return std::make_unique<SkillCrimsonArrowAttack>();
		case AG_CRYSTAL_IMPACT:
			return std::make_unique<SkillCrystalImpact>();
		case AG_CRYSTAL_IMPACT_ATK:
			return std::make_unique<SkillCrystalImpactAttack>();
		case AG_DEADLY_PROJECTION:
			return std::make_unique<SkillDeadlyProjection>();
		case AG_DESTRUCTIVE_HURRICANE:
			return std::make_unique<SkillDestructiveHurricane>();
		case AG_DESTRUCTIVE_HURRICANE_CLIMAX:
			return std::make_unique<SkillDestructiveHurricaneClimax>();
		case AG_ENERGY_CONVERSION:
			return std::make_unique<SkillEnergyConversion>();
		case AG_FLORAL_FLARE_ROAD:
			return std::make_unique<SkillFloralFlareRoad>();
		case AG_FROZEN_SLASH:
			return std::make_unique<SkillFrozenSlash>();
		case AG_MYSTERY_ILLUSION:
			return std::make_unique<SkillMysteryIllusion>();
		case AG_RAIN_OF_CRYSTAL:
			return std::make_unique<SkillRainOfCrystal>();
		case AG_ROCK_DOWN:
			return std::make_unique<SkillRockDown>();
		case AG_SOUL_VC_STRIKE:
			return std::make_unique<SkillSoulVulcanStrike>();
		case AG_STORM_CANNON:
			return std::make_unique<SkillStormCannon>();
		case AG_STRANTUM_TREMOR:
			return std::make_unique<SkillStrantumTremor>();
		case AG_TORNADO_STORM:
			return std::make_unique<SkillTornadoStorm>();
		case AG_VIOLENT_QUAKE:
			return std::make_unique<SkillViolentQuake>();
		case AG_VIOLENT_QUAKE_ATK:
			return std::make_unique<SkillViolentQuakeAttack>();
		case EM_SPELL_ENCHANTING:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case HW_GANBANTEIN:
			return std::make_unique<SkillGanbantein>();
		case HW_GRAVITATION:
			return std::make_unique<SkillGravitationField>();
		case HW_MAGICCRASHER:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case HW_MAGICPOWER:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case HW_NAPALMVULCAN:
			return std::make_unique<SkillNapalmVulcan>();
		case MG_SAFETYWALL:
			return std::make_unique<SkillSafetyWall>();
		case MG_SIGHT:
			return std::make_unique<SkillSight>();
		case MG_SOULSTRIKE:
			return std::make_unique<SkillSoulStrike>();
		case MG_STONECURSE:
			return std::make_unique<SkillStoneCurse>();
		case MG_LIGHTNINGBOLT:
			return std::make_unique<SkillLightningBolt>();
		case MG_NAPALMBEAT:
			return std::make_unique<SkillNapalmBeat>();
		case MG_FIREWALL:
			return std::make_unique<SkillFireWall>();
		case MG_FIREBOLT:
			return std::make_unique<SkillFireBolt>();
		case MG_FROSTDIVER:
			return std::make_unique<SkillFrostDiver>();
		case MG_ENERGYCOAT:
			return std::make_unique<SkillEnergyCoat>();
		case MG_FIREBALL:
			return std::make_unique<SkillFireBall>();
		case MG_COLDBOLT:
			return std::make_unique<SkillColdBolt>();
		case MG_THUNDERSTORM:
			return std::make_unique<SkillThunderStorm>();
		case PF_DOUBLECASTING:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case PF_MEMORIZE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SA_REVERSEORCISH:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WL_MARSHOFABYSS:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WL_RECOGNIZEDSPELL:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WL_TELEKINESIS_INTENSE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WZ_EARTHSPIKE:
			return std::make_unique<SkillEarthSpike>();
		case WZ_ESTIMATION:
			return std::make_unique<SkillSense>();
		case WZ_FIREPILLAR:
			return std::make_unique<SkillFirePillar>();
		case WZ_FROSTNOVA:
			return std::make_unique<SkillFrostNova>();
		case WZ_HEAVENDRIVE:
			return std::make_unique<SkillHeavensDrive>();
		case WZ_ICEWALL:
			return std::make_unique<SkillIceWall>();
		case WZ_JUPITEL:
			return std::make_unique<SkillJupitelThunder>();
		case WZ_VERMILION:
			return std::make_unique<SkillLordOfVermilion>();
		case WZ_METEOR:
			return std::make_unique<SkillMeteorStorm>();
		case WZ_QUAGMIRE:
			return std::make_unique<SkillQuagmire>();
		case WZ_SIGHTBLASTER:
			return std::make_unique<SkillSightBlaster>();
		case WZ_SIGHTRASHER:
			return std::make_unique<SkillSightRasher>();
		case WZ_STORMGUST:
			return std::make_unique<SkillStormGust>();
		case WZ_WATERBALL:
			return std::make_unique<SkillWaterBall>();

		default:
			return nullptr;
	}
}
